/* eslint-disable */
import { link, type EvPageSpec } from "./build";

const d = (
  eyebrow: string,
  h2: string,
  lead: string,
  scenario: string,
  steps: EvPageSpec["demo"]["steps"],
  uiLabel: string,
  uiRows: EvPageSpec["demo"]["uiRows"],
  takeaway: string,
  primaryCtaLabel?: string,
  secondaryCtaLabel?: string,
  variant?: EvPageSpec["demo"]["variant"],
): EvPageSpec["demo"] => ({
  eyebrow, h2, lead, scenario, steps, uiLabel, uiRows, takeaway, primaryCtaLabel, secondaryCtaLabel, variant,
});
const s = (label: string, detail: string) => ({ label, detail });
const r = (left: string, right: string, status?: string) => ({ left, right, status });

/** EV-09 → EV-16 */
export const evSpecsPart2: EvPageSpec[] = [
  {
    id: "EV-09",
    key: "collectivites",
    path: "/espace-vert/collectivites",
    type: "audience",
    primaryKw: "logiciel espaces verts collectivités",
    seoTitle: "Logiciel espaces verts collectivités — marchés & preuves",
    seoDesc: "DST / régie / prestataire marchés publics EV : tournées, reporting passages, zones sensibles, export pour élus. Essai 15 jours — support FR.",
    crumbLabel: "Collectivités",
    h1Lead: "Espaces verts pour collectivités",
    h1: "planning d’exécution et reporting sans tableur de fin de mois",
    sub: "Sophie, DST d’une commune de 18 000 hab., pilote un marché EV à 3 lots. Elle ne veut pas un SaaS « PME » : elle veut savoir si le cimetière sud et les 8 terre-pleins ont été faits avant le comité de quartier.",
    claimBefore: "De l’exécution terrain au",
    claimHighlight: "reporting",
    claimSub: "espaces verts collectivités",
    productStrip: "Collectivités · marchés · reporting",
    empathyH2: "Le marché se défend avec des preuves, pas avec une réunion",
    empathyBody: "Élus, usagers, prestataire, régie interne : tout le monde a une version. Sans historique de passages par site/zone, Sophie passe ses lundis à reconstituer la semaine sur des mails. Le logiciel doit parler marché public et terrain — pas « digitalisation des équipes ».",
    showcaseTitle: "Portefeuille communal lisible",
    showcaseSub: "Écoles, parcs, cimetières, voiries végétalisées — statuts d’exécution.",
    showcaseBadgeLeft: { title: "Commune 18k", sub: "64 sites" },
    showcaseBadgeRight: "Report prêt",
    proofH2: "Ce que demande une collectivité",
    proofQuote: "Pas un discours SaaS : une exécution traçable et un reporting simple.",
    proofItems: [
      { title: "Sites publics", text: "Parc, écoles, cimetières, ronds-points — chacun avec ses consignes." },
      { title: "Équipes / régie", text: "Affectation claire, y compris absences et astreintes saisonnières." },
      { title: "Preuve d’exécution", text: "Historique pour réunions, contrôles et renouvellement de marché." },
    ],
    vsTitle: "Tableur de régie vs suivi d’exécution EV",
    demo: d(
      "Démo produit · collectivités",
      "Préparer le reporting hebdo pour la direction des services techniques",
      "Walkthrough : extraire l’état d’avancement d’un marché d’entretien sur 64 sites.",
      "Commune 18 000 hab. Marché d’entretien pluriannuel. Lundi 9h : DST demande le point avant conseil municipal. Il faut du factuel, pas une impression.",
      [
        s("Filtrer le marché", "Sites du marché M-2024-EV + période S18."),
        s("Statuts", "Fait / reporté météo / non fait — totaux par typologie (écoles, parcs…)."),
        s("Exceptions", "Lister les 5 retards avec motif (engin, absence, accès)."),
        s("Partage", "Vue historique exploitable en réunion — sans reconstruire Excel."),
      ],
      "Reporting · Marché communal S18",
      [
        r("Écoles — 12 sites", "12/12 passages faits", "OK"),
        r("Parcs & squares — 9", "8 faits · 1 report pluie", "Partiel"),
        r("Cimetière sud", "Désherbage non fait · absence", "Alerte"),
        r("Ronds-points — 15", "15/15", "OK"),
      ],
      "Le reporting cesse d’être une nuit blanche : il découle du planning et des pointages.",
      "Essai — sites communaux",
      "Voir preuves de passage",
      "split"
    ),
    bodySections: [
      {
        h2: "Cas — Marché 3 lots, reporting comité de quartier",
        body: "Lot 1 cimetières, lot 2 voiries végétalisées, lot 3 parcs. Sophie filtre la semaine : retards, motifs météo, photos des points de contrôle du CCTP. Le prestataire et la régie voient la même vérité.",
        bullets: [
          "Sites/zones alignés sur le bordereau",
          "Export passages pour élus / commission",
          "Écarts visibles avant la polémique Facebook locale",
        ],
        h3: [
          {
            title: "≠ page écoles ou cimetières seule",
            body: "Ici vision marché / DST transverse. Les niches (écoles, cimetières) ont leurs pages pour l’intent de recherche dédié.",
          },
        ],
      },
      {
        h2: "Journée type DST",
        body: "8h revue retards, 11h validation reports orage, 16h export PDF pour l’élu de secteur, 17h point téléphonique prestataire sur 2 zones critiques.",
      },
      {
        h2: "Objection « Excel filtrable suffit »",
        body: "Excel ne reçoit pas le pointage terrain à 9h12 ni la photo du point noir. Le filtre ne crée pas la preuve.",
      }
    ],
    faq: [
      {
        q: "Régie municipale ou prestataire : ça marche pour les deux ?",
        a: "Oui. La collectivité peut exiger le reporting ; le prestataire exécute et pointe dans le même référentiel sites/zones.",
      },
      {
        q: "Peut-on coller au CCTP / bordereau ?",
        a: "Les prestations et fréquences se paramètrent par site. Ce n’est pas un outil de rédaction de marché : c’est l’exécution tracée.",
      },
      {
        q: "Accès élus / lecture seule ?",
        a: "En pratique on exporte ou on partage un reporting périodique — évite de donner le planning opérationnel brut.",
      },
      {
        q: "Lien avec zéro phyto ?",
        a: "Consignes méthode + preuves photo sur désherbage — voir aussi page désherbage.",
      },
      {
        q: "Puis-je tester PROGESTI sur mon cas « logiciel espaces verts collectivités » ?",
        a: "15 jours — chargez un lot pilote (ex. cimetières + 5 terre-pleins).",
      },
    ],
    gridItems: [
      link("Grands parcs", "Sites étendus & zones", "/espace-vert/grands-parcs"),
      link("Preuves de passage", "Trace pour contrôles", "/espace-vert/preuves-passages"),
      link("Cimetières & voiries", "Niches publiques", "/espace-vert/cimetieres-voirie"),
      link("Contrats annuels", "Exécution sur la durée", "/espace-vert/contrats-annuels"),
    ],
    ctaPrimaryLabel: "Essai — portefeuille communal",
    ctaSecondaryLabel: "Démo reporting DST",
  },
  {
    id: "EV-10",
    key: "syndics-coproprietes",
    path: "/espace-vert/syndics-coproprietes",
    type: "audience",
    primaryKw: "espaces verts syndics copropriétés",
    seoTitle: "Espaces verts syndics & copropriétés — preuves conseils",
    seoDesc: "Prestataires EV pour syndics : passages prouvés, photos AV/AP, accès digicodes, dossier conseil syndical. ≠ solution syndic globale. Essai 15 j.",
    crumbLabel: "Syndics & copropriétés",
    h1Lead: "Espaces verts pour syndics & copropriétés",
    h1: "des preuves de passage que le conseil syndical peut lire",
    sub: "Nadia, conductrice de travaux pour un cabinet de syndic, ne gère pas les AG : elle doit prouver que la haie des Tilleuls a bien été faite avant le mail agressif de 17h.",
    claimBefore: "Des passages",
    claimHighlight: "prouvables",
    claimSub: "EV syndics & copropriétés",
    productStrip: "Syndics · copro · preuves EV",
    empathyH2: "Le conseil syndical ne croit pas WhatsApp",
    empathyBody: "« Vous n’êtes pas venus » est le message le plus cher du métier. Digicodes qui changent, résidences multi-bâtiments, photos perdues : le syndic veut un dossier, pas une conversation. Attention : ce n’est pas /solutions/syndics (propreté / autre verticale).",
    showcaseTitle: "Résidence suivie, syndic rassuré",
    showcaseSub: "Fréquences, pointages, historique — prêts à être partagés.",
    showcaseBadgeLeft: { title: "Résidence 120 lots", sub: "Bihebdo" },
    showcaseBadgeRight: "Preuve envoyée",
    proofH2: "Ce que le syndic achète vraiment",
    proofQuote: "Moins de réclamations, plus de faits, un interlocuteur qui maîtrise son portefeuille.",
    proofItems: [
      { title: "Preuves", text: "Qui est passé, quand — consultable en deux clics." },
      { title: "Multi-résidences", text: "Portefeuille syndic / cabinets gérés sans tout mélanger." },
      { title: "Saisonnalité", text: "Ajuster les fréquences au printemps sans improvisation." },
    ],
    vsTitle: "Réponse WhatsApp vs preuve structurée pour syndic",
    demo: d(
      "Démo produit · syndics EV",
      "Répondre à une réclamation copropriétaire en 2 minutes",
      "Cas cliquable : le syndic forward une plainte — vous renvoyez l’historique de passages.",
      "Résidence Les Tilleuls. Plaintes pelouse. Le syndic demande une preuve avant le conseil. Votre équipe a bien tondu le 02/05 et le 09/05 — mais c’était « dans la tête » du chef d’équipe.",
      [
        s("Ouvrir le site", "Fiche Résidence Les Tilleuls."),
        s("Historique", "Filtres tonte · 30 derniers jours."),
        s("Preuve", "Pointages 02/05 08:17 et 09/05 08:41 + opérateur."),
        s("Réponse", "Transmettre le fait au syndic — fin de la guerre de paroles."),
      ],
      "Site · Les Tilleuls",
      [
        r("Tonte 09/05", "Pointé 08:41 · Équipe A", "Prouvé"),
        r("Tonte 02/05", "Pointé 08:17 · Équipe A", "Prouvé"),
        r("Taille haies", "Prochaine : S22", "Planifié"),
        r("Réclamation", "Clos avec historique", "Traité"),
      ],
      "Le renouvellement se joue sur ces micro-moments : prouver calmement, sans dossier bricolé.",
      "Essai — résidences syndic",
      "Voir page preuves",
      "checklist"
    ),
    bodySections: [
      {
        h2: "Cas — Mail syndic 17h02, Résidence des Tilleuls",
        body: "Nadia ouvre le site : derniers pointages, motif du report S17, photo AP haies S18, prochaine tonte. Réponse en un écran. Le commercial n’est plus otage du chef d’équipe introuvable.",
        bullets: [
          "Preuve horodatée + visuelle",
          "Consignes d’accès à jour (digicode, local)",
          "Dossier renew pour le syndic en novembre",
        ],
      },
      {
        h2: "≠ preuves génériques / ≠ page sites privés",
        body: "Angle syndic/copro et conseil syndical. Les sites tertiaires B2B ont leur page. Les preuves « litige » pures ont la page preuves-passages.",
      },
      {
        h2: "Livrable conseil syndical",
        body: "Historique des passages de la saison + photos clés + exceptions (accès refusé, météo).",
      }
    ],
    faq: [
      {
        q: "C’est le même produit que pour les syndics propreté ?",
        a: "Non : cette page est 100 % espaces verts (tonte, haies, désherbage). Pas de mélange de verticale.",
      },
      {
        q: "Le syndic peut-il avoir un accès ?",
        a: "Souvent on partage un reporting périodique. L’essai permet de tester le format de preuve qu’il exige.",
      },
      {
        q: "Accès refusé / véhicule gênant ?",
        a: "Statut tracé + photo : protège le prestataire au moment du litige.",
      },
      {
        q: "Photos AV/AP obligatoires ?",
        a: "Sur haies et massifs, fortement recommandées — page photos dédiée.",
      },
      {
        q: "L’essai couvre-t-il vraiment « logiciel espaces verts collectivités » ?",
        a: "15 jours — 5 résidences pilotes suffisent.",
      },
    ],
    gridItems: [
      link("Preuves de passage", "Process anti-litige", "/espace-vert/preuves-passages"),
      link("Photos AV/AP", "Preuves visuelles", "/espace-vert/photos-avant-apres"),
      link("Entretien EV", "Fréquences multi-prestations", "/espace-vert/entretien-espaces-verts"),
      link("Entreprises & sites privés", "Autre audience B2B", "/espace-vert/entreprises-sites-prives"),
    ],
    ctaPrimaryLabel: "Essai — portefeuille syndic",
    ctaSecondaryLabel: "Démo réponse réclamation",
  },
  {
    id: "EV-11",
    key: "entreprises-sites-prives",
    path: "/espace-vert/entreprises-sites-prives",
    type: "audience",
    primaryKw: "entretien espaces verts entreprises",
    seoTitle: "Entretien EV sites privés entreprises — multi-sites B2B",
    seoDesc: "Sièges, ZA, parkings d’entreprise : planning abords, consignes sécurité, preuves pour facility. Essai 15 jours sans CB.",
    crumbLabel: "Entreprises & sites privés",
    h1Lead: "Espaces verts pour entreprises & sites privés",
    h1: "sièges, ZA et sites sensibles — un planning digne de vos clients B2B",
    sub: "Olivier entretient 17 sites tertiaires (sièges + ZA). Le facility manager juge sur l’entrée visiteurs — et sur le parking PL que personne ne montre sur Instagram.",
    claimBefore: "Des sites B2B",
    claimHighlight: "maîtrisés",
    claimSub: "EV entreprises & sites privés",
    productStrip: "B2B · ZA · sièges · accès",
    empathyH2: "Le B2B privé ne parle pas comme un syndic",
    empathyBody: "Badges, horaires de livraison, zones hexagone sécurité, interlocuteur facility qui change tous les 18 mois : si vos consignes vivent dans la tête du chef d’équipe, le premier remplacement casse la qualité perçue.",
    showcaseTitle: "Fiches sites B2B exploitables",
    showcaseSub: "Accès, horaires, consignes, historique — dans la poche du terrain.",
    showcaseBadgeLeft: { title: "Siège client", sub: "Créneau 6h–8h" },
    showcaseBadgeRight: "Accès OK",
    proofH2: "Le B2B privé juge sur la fiabilité",
    proofQuote: "Respecter les accès et prouver les passages : le minimum pour garder le contrat.",
    proofItems: [
      { title: "Consignes d’accès", text: "Horaires, contacts, zones engins — sur la fiche site." },
      { title: "Multi-sites groupe", text: "Plusieurs établissements d’un même client sans chaos." },
      { title: "Facturation propre", text: "Forfaits et ponctuels alignés sur le réalisé." },
    ],
    vsTitle: "SMS au gardien vs consignes dans le planning",
    demo: d(
      "Démo produit · sites privés",
      "Préparer une tournée sièges / ZA avec contraintes d’accès",
      "Cas : 5 sites d’un même groupe (3 bureaux, 1 entrepôt, 1 showroom), créneaux différents.",
      "Client groupe industriel. Clause : pas d’engins thermiques après 9h près des bureaux. L’entrepôt n’ouvre qu’à 5h30. Le showroom exige photos mensuelles des massifs d’entrée.",
      [
        s("Fiches", "Consignes d’accès par établissement."),
        s("Planning", "Bureaux tôt le matin ; entrepôt créneau ouverture ; showroom + photo mensuelle."),
        s("Terrain", "L’équipe lit les consignes sur mobile avant d’arriver."),
        s("Preuve", "Pointages + photo massif entrée showroom."),
      ],
      "Client · Groupe Horizon",
      [
        r("Siège Toulouse", "6h–8h · pas d’engin après 9h", "Consignes"),
        r("Entrepôt Blagnac", "Ouverture 5h30", "Planifié"),
        r("Showroom", "Tonte + photo massif / mois", "Preuve"),
        r("Facturation groupe", "Forfait 5 sites", "Mensuel"),
      ],
      "Vos clients B2B n’achètent pas « de la tonte » : ils achètent l’absence de friction à l’entrée du site.",
      "Essai — sites B2B",
      "Voir multi-sites",
      "board"
    ),
    bodySections: [
      {
        h2: "Cas — Campus HexaTech, 2 passages / semaine",
        body: "Zones : entrée visiteurs, patio RH, parking PL, noue paysagère. Horaires 6h–8h hors flux salariés. Preuve mensuelle envoyée au facility (passages + 4 photos points de contrôle).",
        bullets: [
          "Consignes sécurité / badge sur la fiche site",
          "Zones inégales en criticité visuelle",
          "Reporting facility ≠ dossier conseil syndical",
        ],
      },
      {
        h2: "≠ hôpitaux / ≠ écoles",
        body: "Même famille « sites contraints », mais protocoles santé et créneaux scolaires ont leurs pages.",
      },
      {
        h2: "Objection « comme un syndic »",
        body: "Le facility veut de la prévisibilité et zéro friction d’accès, rarement une photo de chaque haie. Adaptez le livrable.",
      }
    ],
    faq: [
      {
        q: "Multi-sites d’un même groupe ?",
        a: "Oui — portefeuille filtrable par client / commune / type de zone.",
      },
      {
        q: "Astreinte espaces verts ?",
        a: "Interventions ponctuelles traçables hors forfait (casse, sinistre tempête).",
      },
      {
        q: "Lien devis annuel ?",
        a: "Page contrats annuels pour le cycle renew ; ici l’exécution sites privés.",
      },
      {
        q: "Peut-on joindre des photos pour « logiciel espaces verts collectivités » ?",
        a: "4 points de contrôle par site souvent suffisent en B2B.",
      },
      {
        q: "Comment démarrer un essai orienté logiciel espaces verts collectivités ?",
        a: "15 jours — 3 sites d’un même client facility.",
      },
    ],
    gridItems: [
      link("Multi-sites", "Portefeuille sous contrôle", "/espace-vert/multi-sites"),
      link("Photos AV/AP", "Image des massifs d’entrée", "/espace-vert/photos-avant-apres"),
      link("Aménageurs / promoteurs", "Autre audience B2B", "/espace-vert/amenageurs-promoteurs"),
      link("Planning équipes", "Respecter les créneaux", "/espace-vert/planning-equipes"),
    ],
    ctaPrimaryLabel: "Essai — sites privés",
    ctaSecondaryLabel: "Démo consignes d’accès",
  },
  {
    id: "EV-12",
    key: "planning-equipes",
    path: "/espace-vert/planning-equipes",
    type: "process",
    primaryKw: "planning équipes espaces verts",
    seoTitle: "Planning équipes espaces verts — multi-chantiers & compétences",
    seoDesc: "Affectez tonte, haies, élagage : compétences, engins, secteurs. Finis les doublons WhatsApp. Essai 15 jours.",
    crumbLabel: "Planning équipes",
    h1Lead: "Planning équipes espaces verts",
    h1: "multi-chantiers, contraintes engins, absences — un seul écran",
    sub: "Le lundi de Mai, Julie (planificatrice, 34 collaborateurs) a 3 équipes à coller sur 51 interventions. Le grimpeur ne tond pas ; l’autoportée ne taille pas les haies en 4 m.",
    claimBefore: "Des équipes",
    claimHighlight: "au bon endroit",
    claimSub: "planning équipes espaces verts",
    productStrip: "Planning · équipes · multi-chantiers",
    empathyH2: "Planifier sans compétences, c’est inventer des conflits",
    empathyBody: "Le tableau blanc du bureau est joli jusqu’à 6h50. Ensuite, quelqu’un est au mauvais endroit avec le mauvais engin. Le planning EV doit connaître les savoir-faire et les contraintes — pas seulement des cases colorées.",
    showcaseTitle: "Semaine d’équipes EV",
    showcaseSub: "Affectations, sites, statuts — modifiables sans tout casser.",
    showcaseBadgeLeft: { title: "3 équipes", sub: "52 interventions" },
    showcaseBadgeRight: "À jour",
    proofH2: "Un planning EV digne de ce nom",
    proofQuote: "Visible bureau + terrain, ajustable, lié aux preuves et à la facture.",
    proofItems: [
      { title: "Affectation", text: "Équipes / sites / types de prestation." },
      { title: "Ajustements", text: "Météo, absences, urgences client." },
      { title: "Continuité", text: "Le terrain voit la même vérité que le bureau." },
    ],
    vsTitle: "Tableau blanc & Excel vs planning EV live",
    demo: d(
      "Démo produit · planning équipes",
      "Réaffecter une équipe après un arrêt maladie à 6h50",
      "Walkthrough minute par minute du mardi matin typique.",
      "Équipe B (tonte secteur est) : conducteur en arrêt. 11 sites prévus. Une seule personne formée autoportée en réserve.",
      [
        s("Alerte", "Marquer l’absence sur l’équipe B."),
        s("Backup", "Basculer le conducteur réserve + 1 ouvrier de l’équipe C (haies reportables)."),
        s("Arbitrer", "Reporter 3 tailles de haies non urgentes ; garder les 2 syndics sensibles."),
        s("Push terrain", "Nouveau planning visible sur mobile avant 7h15."),
      ],
      "Planning · Mardi 6h58",
      [
        r("Équipe B — conducteur", "Arrêt maladie", "Absent"),
        r("Backup autoportée", "M. Leroy réaffecté", "OK"),
        r("Haies secteur ouest", "3 sites reportés mercredi", "Report"),
        r("Syndics sensibles", "Maintenus mardi", "Priorité"),
      ],
      "Le planning n’est utile que s’il survit au premier imprévu de la semaine.",
      "Essai — mon planning équipes",
      "Voir absences & remplacements",
      "board"
    ),
    bodySections: [
      {
        h2: "Cas — Semaine 18, 51 interventions, 3 équipes",
        body: "Filtres : compétence grimpe, permis nacelle, secteur nord. Julie détecte un double booking autoportée et un trou sur la tournée haies après un arrêt maladie. Ajustement avant 7h30, sync mobile.",
        bullets: [
          "Compétences sur les personnes",
          "Conflits engins visibles",
          "Une seule semaine partagée bureau ↔ terrain",
        ],
      },
      {
        h2: "≠ absences (page sœur) ≠ engins seuls",
        body: "Absences/remplacements = trou d’équipe last minute. Engins = ressource machine. Ici : construction de la semaine multi-contraintes.",
      },
      {
        h2: "Journée type planificatrice",
        body: "16h veille : brouillon. 6h45 : arbitrages. 7h15 : gel de la tournée. 17h : retours terrain → seeds du lendemain.",
      }
    ],
    faq: [
      {
        q: "Peut-on bloquer une affectation incompatible (grimpe) ?",
        a: "Vous voyez les compétences ; l’outil vous aide à ne pas affecter « au feeling ». La responsabilité reste humaine.",
      },
      {
        q: "Planning glissant vs semaine fixe ?",
        a: "Semaine EV + reports : le plus lisible pour le terrain. Évitez le chaos du « on verra demain matin » permanent.",
      },
      {
        q: "Peut-on gérer l’intérim pour « logiciel espaces verts collectivités » ?",
        a: "Créez le backup avec consignes sites ; limitez les sites sensibles le premier jour.",
      },
      {
        q: "Quel lien avec le pointage pour « logiciel espaces verts collectivités » ?",
        a: "Oui — page pointage terrain pour la capture ; ici l’affectation.",
      },
      {
        q: "Y a-t-il un essai sans engagement pour logiciel espaces verts collectivités ?",
        a: "15 jours — rejouez une vraie semaine chargée.",
      },
    ],
    gridItems: [
      link("Absences & remplacements", "Trous d’équipe", "/espace-vert/absences-remplacements"),
      link("Engins & matériel", "Contraintes ressources", "/espace-vert/engins-materiel"),
      link("Replanif météo", "Bascules de tournée", "/espace-vert/replanification-meteo"),
      link("Pointage terrain", "Boucler la boucle", "/espace-vert/pointage-terrain"),
    ],
    ctaPrimaryLabel: "Essai — planning équipes",
    ctaSecondaryLabel: "Démo réaffectation",
  },
  {
    id: "EV-13",
    key: "pointage-terrain",
    path: "/espace-vert/pointage-terrain",
    type: "process",
    primaryKw: "pointage terrain espaces verts",
    seoTitle: "Pointage terrain espaces verts — mobile, horodatage, preuves",
    seoDesc: "Arrivée/départ chantier EV sur mobile : qui, où, quand. Base des preuves et de la facture. Essai 15 jours sans CB.",
    crumbLabel: "Pointage terrain",
    h1Lead: "Pointage terrain espaces verts",
    h1: "qui est intervenu, où, quand — sans feuille papier",
    sub: "Sans pointage, votre « on est passé » est une opinion. Avec pointage, c’est un fait horodaté — celui que le syndic et la facture réclament.",
    claimBefore: "Du terrain à la",
    claimHighlight: "preuve horodatée",
    claimSub: "pointage espaces verts",
    productStrip: "Pointage · mobile · preuves",
    empathyH2: "Le pointage n’est pas du flicage : c’est une ceinture de sécurité",
    empathyBody: "Les équipes détestent les usines à gaz. Elles acceptent un geste simple qui évite les appels du gérant à 18h. Arrivée, départ, éventuellement photo : si le planning est juste, le pointage devient naturel.",
    showcaseTitle: "Pointage sur site, historique au bureau",
    showcaseSub: "Arrivée / départ, site concerné, remontée immédiate.",
    showcaseBadgeLeft: { title: "Mobile", sub: "Arrivée 08:12" },
    showcaseBadgeRight: "Sync OK",
    proofH2: "Pourquoi le pointage EV n’est pas du « contrôle flic »",
    proofQuote: "C’est une protection mutuelle : salarié, entreprise, client.",
    proofItems: [
      { title: "Heures plus justes", text: "Moins de zones grises en fin de mois." },
      { title: "Preuve client", text: "Base factuelle des passages." },
      { title: "Moins d’appels", text: "Le bureau voit l’avancement sans harceler le terrain." },
    ],
    vsTitle: "Feuille papier vs pointage mobile EV",
    demo: d(
      "Démo produit · pointage",
      "Suivre une tournée en live depuis le bureau",
      "Cas : 1 équipe, 8 sites de tonte — le responsable voit les pointages remonter.",
      "Jeudi après-midi. Un syndic appelle : « ils sont où ? ». Au lieu d’appeler le chef d’équipe au téléphone au milieu d’une haie, vous ouvrez les pointages du jour.",
      [
        s("Vue jour", "Équipe Nord · 8 interventions."),
        s("Live", "5 pointages « fait », 1 en cours, 2 à venir."),
        s("Détail", "Site en cours : Résidence Saule · arrivée 14:02."),
        s("Réponse client", "« Ils sont sur site depuis 14h02 » — factuel."),
      ],
      "Pointages · Jeudi",
      [
        r("Lotissement Bleuets", "08:10–09:40", "Fait"),
        r("Mairie annexe", "10:05–11:00", "Fait"),
        r("Résidence Saule", "Arrivée 14:02", "En cours"),
        r("ZA Les Pins", "Prévu 15:30", "À faire"),
      ],
      "Le pointage n’ajoute pas une corvée : il supprime les appels et les litiges d’heures.",
      "Essai — pointage équipes",
      "Voir preuves de passage",
      "timeline"
    ),
    bodySections: [
      {
        h2: "Cas — Binôme tonte, 9 sites, journée type",
        body: "Chaque arrivée timestampée. Un oubli de pointage au site 4 apparaît en alerte bureau à 15h — relance immédiate. Le soir, la facturation périodique s’appuie sur du réel.",
        bullets: [
          "Geste mobile < 15 secondes",
          "Alerte oublis avant la facture",
          "Couplage naturel avec preuves / photos",
        ],
      },
      {
        h2: "≠ page preuves litige",
        body: "Ici capture terrain. La page preuves-passages assemble le dossier quand le mail agressif arrive.",
      },
      {
        h2: "Objection « les gars ne pointeront pas »",
        body: "Ils ne pointeront pas un process absurde. Ils pointeront ce qui réduit les coups de fil et les accusations.",
      }
    ],
    faq: [
      {
        q: "Hors-ligne / réseau faible ?",
        a: "Le geste doit rester simple ; en pratique les équipes pointent dès qu’elles ont du réseau en sortie de site. On paramètre les exigences selon vos zones.",
      },
      {
        q: "Géoloc obligatoire ?",
        a: "L’horodatage + site planifié suffisent souvent. Évitez le flicage excessif qui tue l’adoption.",
      },
      {
        q: "Lien paie ?",
        a: "PROGESTI n’est pas un SIRH. Le pointage sert d’abord opération et preuve client.",
      },
      {
        q: "Photo au pointage ?",
        a: "Optionnelle par type d’intervention (haies oui, tonte parfois).",
      },
      {
        q: "Puis-je essayer avant d’engager mon équipe sur logiciel espaces verts collectivités ?",
        a: "15 jours — 1 équipe pilote suffit pour mesurer l’adoption.",
      },
    ],
    gridItems: [
      link("Preuves de passage", "Exploitations des pointages", "/espace-vert/preuves-passages"),
      link("Planning équipes", "Avant le pointage", "/espace-vert/planning-equipes"),
      link("Devis & facturation", "Après le réalisé", "/espace-vert/devis-facturation"),
      link("Remplacer Excel", "Sortir du papier", "/espace-vert/remplacer-excel"),
    ],
    ctaPrimaryLabel: "Essai — pointage mobile",
    ctaSecondaryLabel: "Démo live tournée",
  },
  {
    id: "EV-14",
    key: "devis-facturation",
    path: "/espace-vert/devis-facturation",
    type: "process",
    primaryKw: "devis facturation espaces verts",
    seoTitle: "Devis & facturation espaces verts — du réalisé à la facture",
    seoDesc: "Devis entretien ou chantier, avenants, facture alignée sur le réalisé pointé. Moins d’oublis de prestations ponctuelles. Essai 15 j.",
    crumbLabel: "Devis & facturation",
    h1Lead: "Devis & facturation espaces verts",
    h1: "ce qui est vendu, planifié, fait — puis facturé",
    sub: "Chaque mois, Samia (administrative + commerciale) reconstruit la facturation depuis le groupe WhatsApp. Les haies d’urgence de la semaine 12 ont disparu — pas la marge.",
    claimBefore: "Du devis à la",
    claimHighlight: "facture",
    claimSub: "devis facturation espaces verts",
    productStrip: "Devis · réalisé · facture EV",
    empathyH2: "Si ce n’est pas dans le planning, ce ne sera pas dans la facture",
    empathyBody: "Le réalisé doit pousser la facture. Sinon vous facturez le forfait théorique et vous offrez le ponctuel. Les clients sympas en profitent ; les autres contestent le forfait.",
    showcaseTitle: "Flux devis → planning → facture",
    showcaseSub: "Moins de ressaisie, moins d’oublis, plus de marge maîtrisée.",
    showcaseBadgeLeft: { title: "Facture M+1", sub: "Alignée réalisé" },
    showcaseBadgeRight: "Sans Excel",
    proofH2: "La facturation EV n’est pas un sujet « compta only »",
    proofQuote: "Elle commence dans le planning et les pointages.",
    proofItems: [
      { title: "Forfaits", text: "Contrats d’entretien périodiques." },
      { title: "Ponctuels", text: "Élagage, création, prestations flash." },
      { title: "Avenants", text: "Le supplémentaire documenté pour être facturable." },
    ],
    vsTitle: "Facturer depuis Excel vs facturer depuis le réalisé",
    demo: d(
      "Démo produit · devis/factu",
      "Facturer un mois d’entretien + 2 ponctuels sans oublier une ligne",
      "Cas admin : fin de mois sur un portefeuille mixte forfaits + chantiers.",
      "32 contrats d’entretien mensuels + 2 élagages + 1 désherbage flash facturable. L’assistante ne veut plus croiser 3 tableurs et la mémoire du chef d’équipe.",
      [
        s("Base forfaits", "Contrats actifs du mois."),
        s("Ajouter réalisé ponctuel", "2 élagages pointés + 1 flash."),
        s("Contrôle", "Sites suspendus exclus ; avenants inclus."),
        s("Émission", "Factures alignées — prêt export / suivi."),
      ],
      "Facturation · Mois en cours",
      [
        r("Forfaits entretien", "32 contrats", "Prêts"),
        r("Élagage Villa X", "Réalisé 12/05", "À facturer"),
        r("Élagage ZA Y", "Réalisé 18/05", "À facturer"),
        r("Site Z — suspendu travaux", "Exclu ce mois", "Hors scope"),
      ],
      "La marge se joue souvent sur les lignes oubliées — pas sur le prix affiché du forfait.",
      "Essai — devis & factures",
      "Voir tarifs PROGESTI",
      "timeline"
    ),
    bodySections: [
      {
        h2: "Cas — Fin de mois, 6 ponctuels « oubliés »",
        body: "Samia ouvre les interventions clôturées hors forfait : 3 haies d’urgence, 1 évacuation benne, 2 reprises plantations. Ticket facture généré depuis le réel. Le gérant arrête de « se souvenir » le dimanche.",
        bullets: [
          "Forfait vs ponctuel clairement séparés",
          "Avenants tracés",
          "Moins de leakage de marge silencieux",
        ],
      },
      {
        h2: "≠ contrats annuels renew",
        body: "Le renew commercial est une autre page. Ici : produire les pièces devis/facture depuis l’exécution.",
      },
      {
        h2: "Objection « mon outil compta suffit »",
        body: "La compta facture ce qu’on lui dit. Elle ne sait pas ce qui s’est passé sur le parking PL mardi.",
      }
    ],
    faq: [
      {
        q: "Export comptable ?",
        a: "Oui dans la logique PROGESTI — l’essai montre le flux aligné sur votre organisation.",
      },
      {
        q: "Devis chantier création vs entretien ?",
        a: "Deux modèles : jalons/avancement vs périodique forfait + ponctuels.",
      },
      {
        q: "Avenants météo / volume ?",
        a: "Tracez l’exception dans le planning puis facturez si le contrat le prévoit.",
      },
      {
        q: "Comment suivre les impayés liés à « logiciel espaces verts collectivités » ?",
        a: "Suivi dans le module — sans tableur parallèle.",
      },
      {
        q: "L’essai suffit-il pour valider mon besoin logiciel espaces verts collectivités ?",
        a: "15 jours — rejouez votre dernier mois sur 15 sites.",
      },
    ],
    gridItems: [
      link("Contrats annuels", "Exécution des forfaits", "/espace-vert/contrats-annuels"),
      link("Paysagisme", "Devis chantier", "/espace-vert/paysagisme"),
      link("Pointage terrain", "Alimenter le réalisé", "/espace-vert/pointage-terrain"),
      link("Logiciel EV", "Vue pilier", "/logiciel-espace-vert"),
    ],
    ctaPrimaryLabel: "Essai — facturer mon réalisé",
    ctaSecondaryLabel: "Voir les tarifs",
  },
  {
    id: "EV-15",
    key: "saison-printemps",
    path: "/espace-vert/saison-printemps",
    type: "saisonnier",
    primaryKw: "organisation espaces verts printemps",
    seoTitle: "Saison printemps espaces verts — monte en charge planning",
    seoDesc: "Mars–juin : densifiez tournées, embauches saisonnières, priorités clients. Playbook de montée en charge EV. Essai 15 jours.",
    crumbLabel: "Saison printemps",
    h1Lead: "Haute saison espaces verts",
    h1: "tenir avril–juin sans transformer l’entreprise en pompier",
    sub: "Mi-mars, la pousse ne négocie pas. Vertigo passe de 2 à 4 équipes en 3 semaines. Sans playbook, le planning devient une salle d’urgence.",
    claimBefore: "Un printemps",
    claimHighlight: "sous contrôle",
    claimSub: "haute saison espaces verts",
    productStrip: "Printemps · pic · fréquences",
    empathyH2: "Le printemps ne crée pas de nouveaux clients : il révèle le chaos",
    empathyBody: "Les fréquences passent hebdo, les saisonniers arrivent, les engins vieillissent d’un coup. Si votre système était déjà juste l’hiver, il casse au premier week-end de beau temps.",
    showcaseTitle: "Plan de charge printemps",
    showcaseSub: "Fréquences accélérées, équipes renforcées, priorités clients.",
    showcaseBadgeLeft: { title: "S16–S26", sub: "Pic tonte+haies" },
    showcaseBadgeRight: "Charge OK",
    proofH2: "Anticiper le pic plutôt que le subir",
    proofQuote: "Le printemps se prépare en février dans le logiciel — pas le lundi matin sous la pluie.",
    proofItems: [
      { title: "Fréquences", text: "Basculer mensuel → hebdo sur les sites qui le demandent." },
      { title: "Effectifs", text: "Intégrer saisonniers dans les équipes sans perdre le fil." },
      { title: "Arbitrages", text: "Prioriser syndics / collectivités sensibles." },
    ],
    vsTitle: "Survie printemps vs plan de charge EV",
    demo: d(
      "Démo produit · printemps",
      "Basculer 40 sites en fréquence hebdomadaire avant le pic",
      "Cas d’anticipation : mi-mars, préparer S16.",
      "Portefeuille 40 pelouses en bihebdo hiver. Clients prévenus du passage en hebdo dès la pousse. Il faut appliquer le changement sans éditer site par site dans la panique.",
      [
        s("Sélection", "Filtrer sites « tonte bihebdo — éligibles accélération »."),
        s("Basculer", "Nouvelle fréquence hebdo à partir de S16."),
        s("Charge", "Vérifier que 3 équipes + 2 saisonniers couvrent le volume."),
        s("Priorités", "Tagger 8 clients sensibles non reportables."),
      ],
      "Préparation · Pic printemps",
      [
        r("40 sites → hebdo", "À partir S16", "Planifié"),
        r("2 saisonniers", "Intégrés équipes A/B", "RH"),
        r("8 clients sensibles", "Non reportables météo légère", "Priorité"),
        r("Charge S18", "97% — seuil d’alerte", "Watch"),
      ],
      "Le printemps se gagne deux semaines avant la première tonte « de trop ».",
      "Préparer mon pic de saison",
      "Voir tonte multi-sites",
      "board"
    ),
    bodySections: [
      {
        h2: "Cas — Passage bihebdo → hebdo sur 28 pelouses",
        body: "Julie active le profil saisonnier : densification automatique des occurrences, priorisation clients renew, intégration de 2 saisonniers avec sites « faciles » la première semaine.",
        bullets: [
          "Densification des fréquences sans tout retaper",
          "Onboarding saisonniers guidé",
          "Buffer météo plus large qu’en hiver",
        ],
      },
      {
        h2: "≠ saison automne-hiver",
        body: "L’autre page traite feuilles, tailles, baisse de cadence, maintenance engins. Ici : montée en charge.",
      },
      {
        h2: "Livrable interne",
        body: "Plan de charge 8 semaines + liste sites critiques + besoins engins.",
      }
    ],
    faq: [
      {
        q: "Peut-on pré-planifier mars en janvier ?",
        a: "Oui — préparez les fréquences et validez en S9–S10.",
      },
      {
        q: "Saisonniers sans smartphone ?",
        a: "Binôme avec un titulaire qui pointe ; consignes papier en secours la première semaine seulement.",
      },
      {
        q: "Prioriser quels clients ?",
        a: "Renew < 90 j, sites « visibles », marchés publics à reporting.",
      },
      {
        q: "Lien absences ?",
        a: "Les arrêts explosent aussi au printemps — page remplacements.",
      },
      {
        q: "Puis-je tester PROGESTI sur mon cas « logiciel espaces verts collectivités » ?",
        a: "Idéal en février–mars sur une vraie montée.",
      },
    ],
    gridItems: [
      link("Tonte pelouse", "Volume n°1 du printemps", "/espace-vert/tonte-pelouse"),
      link("Taille de haies", "Second poste de charge", "/espace-vert/taille-haies"),
      link("Automne–hiver", "L’autre saison EV", "/espace-vert/saison-automne-hiver"),
      link("Absences & remplacements", "Saisonniers & trous", "/espace-vert/absences-remplacements"),
    ],
    ctaPrimaryLabel: "Essai avant la haute saison",
    ctaSecondaryLabel: "Démo plan de charge",
  },
  {
    id: "EV-16",
    key: "saison-automne-hiver",
    path: "/espace-vert/saison-automne-hiver",
    type: "saisonnier",
    primaryKw: "entretien espaces verts automne hiver",
    seoTitle: "Saison automne-hiver EV — feuilles, tailles, cadence basse",
    seoDesc: "Ramassage feuilles, tailles hors pousse, maintenance engins, baisses de fréquence. Pilotez la basse saison sans perdre les sites. Essai 15 j.",
    crumbLabel: "Automne & hiver",
    h1Lead: "Automne & hiver espaces verts",
    h1: "ramassage, tailles et suivi — la saison où l’on perd les contrats silencieux",
    sub: "Novembre : la tonte ralentit, les feuilles explosent, les tailles se concentrent. Ceux qui « improvisent la basse saison » perdent des forfaits au renew.",
    claimBefore: "Une basse saison",
    claimHighlight: "active",
    claimSub: "espaces verts automne hiver",
    productStrip: "Automne · hiver · suivi contrats",
    empathyH2: "La basse saison n’est pas une pause : c’est un autre métier",
    empathyBody: "Ramassage, soufflage, évacuation, tailles structurelles, inventaire engins : si vous laissez le planning en mode printemps, vous surstaffez les pelouses et sous-staffez les feuilles — puis vous expliquez au syndic pourquoi l’allée est un tapis jaune.",
    showcaseTitle: "Plan automne–hiver",
    showcaseSub: "Ramassages, tailles, chantiers reportés, relances contrats.",
    showcaseBadgeLeft: { title: "S44–S8", sub: "Feuilles + tailles" },
    showcaseBadgeRight: "Contrats suivis",
    proofH2: "L’hiver est commercial autant qu’opérationnel",
    proofQuote: "Exécuter les prestations froides + préparer le carnet de printemps.",
    proofItems: [
      { title: "Ramassage feuilles", text: "Fréquences dédiées, sites prioritaires (écoles, résidences)." },
      { title: "Tailles", text: "Planifier hors période de nidification / selon vos règles métier." },
      { title: "Relances", text: "Devis et renouvellements avant le rush d’avril." },
    ],
    vsTitle: "Mode ralenti vs basse saison pilotée",
    demo: d(
      "Démo produit · automne-hiver",
      "Construire le plan feuilles + tailles de novembre",
      "Cas d’usage : 25 sites feuilles hebdo pendant 6 semaines + 10 tailles de haies hors pousse.",
      "Entreprise EV 22 salariés. Novembre : charge tonte en baisse, pression feuilles + tailles + renew. Le responsable d’exploitation fige le plan S44–S50.",
      [
        s("Prestations feuilles", "Fréquence hebdo S44–S50 sur sites concernés."),
        s("Tailles", "Créneaux stables pour équipes réduites."),
        s("Chantiers reportés", "Reprendre les plantations / créations non faites en juin."),
        s("Commercial", "Liste contrats à renouveler avant février."),
      ],
      "Plan · Novembre",
      [
        r("Ramassage feuilles — 25 sites", "Hebdo", "Actif"),
        r("Taille haies — 10 sites", "Planifié S45–S48", "OK"),
        r("Plantation reportée Villa M", "Reprise S47", "Chantier"),
        r("Renouvellements 2027", "12 contrats à relancer", "Commercial"),
      ],
      "La basse saison bien tenue finance la tranquillité du printemps.",
      "Essai — plan automne",
      "Voir contrats annuels",
      "list"
    ),
    bodySections: [
      {
        h2: "Cas — 3 semaines de feuilles, 18 résidences",
        body: "Profil automne : cadence tonte réduite, tournées feuilles bihebdo, fenêtres de taille, créneaux atelier engins. Les sites sensibles (escalier nord, parking) ont une priorité usagers.",
        bullets: [
          "Changement de profil saisonnier global",
          "Évacuation déchets verts liée",
          "Atelier engins planifié hors urgence",
        ],
      },
      {
        h2: "≠ printemps",
        body: "Montée vs redescente. Ne fusionnez pas les playbooks.",
      },
      {
        h2: "Livrable renew novembre",
        body: "Bilan d’exécution saison + photos avant/après tailles + dossier pour le syndic.",
      }
    ],
    faq: [
      {
        q: "Ramassage feuilles dans le forfait ?",
        a: "Selon contrats : certains forfaits l’incluent, d’autres non. Tracez pour facturer le juste.",
      },
      {
        q: "Neige / déblaiement ?",
        a: "Si vous le proposez, créez des interventions ponctuelles ; ce n’est pas le cœur de cette page.",
      },
      {
        q: "Maintenance engins ?",
        a: "Bloquez des créneaux atelier — évite la panne du premier lundi de mars.",
      },
      {
        q: "Lien déchets verts ?",
        a: "Oui — rotations benne saturées en automne.",
      },
      {
        q: "L’essai couvre-t-il vraiment « logiciel espaces verts collectivités » ?",
        a: "15 jours — basculez 10 sites en profil automne.",
      },
    ],
    gridItems: [
      link("Saison printemps", "Préparer le pic", "/espace-vert/saison-printemps"),
      link("Taille de haies", "Poste typique hors pousse", "/espace-vert/taille-haies"),
      link("Contrats annuels", "Renouvellements", "/espace-vert/contrats-annuels"),
      link("Devis & facturation", "Chantiers reportés", "/espace-vert/devis-facturation"),
    ],
    ctaPrimaryLabel: "Essai — basse saison active",
    ctaSecondaryLabel: "Démo plan novembre",
  },
];
