/* eslint-disable */
import { link, type EvPageSpec } from "./build";

const d = (
  eyebrow: string,
  h2: string,
  lead: string,
  scenario: string,
  steps: EvPageSpec["demo"]["steps"],
  uiLabel: string,
  uiRows: EvPageSpec["demo"]["uiRows"],
  takeaway: string,
  primaryCtaLabel?: string,
  secondaryCtaLabel?: string,
  variant?: EvPageSpec["demo"]["variant"],
): EvPageSpec["demo"] => ({
  eyebrow, h2, lead, scenario, steps, uiLabel, uiRows, takeaway, primaryCtaLabel, secondaryCtaLabel, variant,
});
const s = (label: string, detail: string) => ({ label, detail });
const r = (left: string, right: string, status?: string) => ({ left, right, status });

/** EV-33 → EV-36 — niches SEO additionnelles */
export const evSpecsPart5: EvPageSpec[] = [
  {
    id: "EV-33",
    key: "dechets-verts",
    path: "/espace-vert/dechets-verts",
    type: "service",
    primaryKw: "évacuation déchets verts espaces verts",
    seoTitle: "Évacuation déchets verts — bennes liées aux chantiers coupe",
    seoDesc: "Rotations benne après élagage/haies : pas de branches 48h chez le syndic. Coûts déchèterie tracés. Essai 15 jours.",
    crumbLabel: "Déchets verts",
    h1Lead: "Évacuation des déchets verts",
    h1: "ne laissez pas les branches 48 h devant le syndic",
    sub: "S15 : 12 chantiers de coupe, 3 rotations benne. Oublier la benne, c’est offrir un litige gratuit — et une cour pleine de branches.",
    claimBefore: "De la coupe à l’",
    claimHighlight: "évacuation",
    claimSub: "déchets verts · planning logistique EV",
    productStrip: "Déchets verts · bennes · chantiers",
    empathyH2: "La coupe n’est finie que quand le camion est parti",
    empathyBody: "≠ élagage (la coupe). Ici la logistique déchets : rotations, saturation printemps, coûts. Souvent négligée dans les logiciels « planning vert » génériques.",
    showcaseTitle: "Coupes et rotations de benne sur une même semaine",
    showcaseSub: "Reliez interventions produisant des déchets et créneaux d’évacuation.",
    showcaseBadgeLeft: {"title":"S15","sub":"12 sites · 3 bennes"},
    showcaseBadgeRight: "Évacué",
    proofH2: "Ce que change un planning déchets verts",
    proofQuote: "Moins de tas oubliés, moins de courses improvisées, plus de sérénité client.",
    proofItems: [{"title":"Lien coupe → benne","text":"Les chantiers générateurs de volume portent une tâche d’évacuation."},{"title":"Priorités client","text":"Syndics et écoles d’abord — pas de branches 48 h sur parking."},{"title":"Charge visible","text":"Évitez de planifier 8 élagages le même jour sans rotation."}],
    vsTitle: "Course improvisée vs évacuation planifiée",
    demo: d(
      "Démo produit · déchets verts",
      "Planifier 3 rotations de benne liées aux chantiers de coupe",
      "Walkthrough : une semaine de haies/élagage où chaque volume a son créneau d’évacuation.",
      "S15 haute saison. 12 sites de taille/élagage. 1 benne 20 m³ + 2 rotations déchèterie. Objectif : aucun tas > 24 h sur site syndic.",
      [
        s("Lister les coupes", "Filtrer interventions haies/élagage de la semaine avec volume estimé."),
        s("Créer les évacuations", "Tâches liées : benne + site + créneau + équipe conducteur."),
        s("Prioriser", "Syndics et écoles en tête ; sites privés plus tolérants ensuite."),
        s("Clôturer", "Pointer l’évacuation — preuve si le client rappelle."),
      ],
      "Logistique · Déchets S15",
      [
        r("Tilleuls — haies", "Benne A · mar 10h", "Planifié"),
        r("ZA Pins — élagage", "Benne A · mar 14h", "Planifié"),
        r("École Jules Ferry", "Rotation déchèterie mer 8h", "Prioritaire"),
        r("Villa Martin", "Jeudi · toléré 48h", "OK"),
      ],
      "La coupe et l’évacuation vivent dans le même planning — plus de trou logistique.",
      "Essai — mes tournées déchets",
      "Voir élagage & haies",
      "timeline",
    ),
    bodySections: [
      {
        h2: "Cas — 12 sites coupe, 3 rotations benne S15",
        body: "Chaque intervention coupe génère une tâche benne liée. Alerte si benne non planifiée sous 48h. Coût rotation visible pour le gérant.",
        bullets: [
          "Lien coupe → évacuation",
          "Engagement délai client",
          "Charge printemps anticipée",
        ],
      },
      {
        h2: "Objection « c’est de la logistique »",
        body: "Oui — et sans elle votre belle taille de haies devient un scandale syndic.",
      },
      {
        h2: "Livrable",
        body: "Planning rotations + sites en attente d’évacuation.",
      }
    ],
    faq: [
      {
        q: "Bennes louées vs parc propre ?",
        a: "Les deux : ressource « benne loc » sur période.",
      },
      {
        q: "Déchèterie / traçabilité ?",
        a: "Notez rotation et site ; documents légaux restent votre process.",
      },
      {
        q: "Facturation évacuation ?",
        a: "Souvent hors forfait — poussez vers facture du réalisé.",
      },
      {
        q: "Saturation novembre feuilles ?",
        a: "Oui — couplez avec saison automne.",
      },
      {
        q: "Puis-je tester PROGESTI sur mon cas « évacuation déchets verts espaces verts » ?",
        a: "15 jours — liez benne à votre prochaine tournée haies.",
      },
    ],
    gridItems: [
      link("Élagage", "La coupe qui génère le volume", "/espace-vert/elagage"),
      link("Taille de haies", "Volume récurrent", "/espace-vert/taille-haies"),
      link("Planning équipes", "Affecter conducteurs / bennes", "/espace-vert/planning-equipes"),
    ],
    ctaPrimaryLabel: "Essai 15 j — déchets verts",
    ctaSecondaryLabel: "Parler logistique EV",
  },
  {
    id: "EV-34",
    key: "plantations-massifs",
    path: "/espace-vert/plantations-massifs",
    type: "service",
    primaryKw: "logiciel plantations massifs paysagiste",
    seoTitle: "Plantations & massifs — livraison plants, pose, reprises",
    seoDesc: "Chantier plantation : fenêtre, fournitures, pose, contrôle reprise J+21. Pour conducteurs travaux massifs/engazonnement. Essai 15 j.",
    crumbLabel: "Plantations & massifs",
    h1Lead: "Plantations et massifs",
    h1: "de la livraison des plants au contrôle de reprise",
    sub: "Plants livrés mardi, pose mercredi–jeudi, reprise J+21. Si la livraison glisse et que personne n’ajuste, vous plantez dans le stress — ou trop tard.",
    claimBefore: "Du plant livré à la",
    claimHighlight: "reprise tenue",
    claimSub: "plantations · massifs · engazonnement",
    productStrip: "Plantations · pose · reprise",
    empathyH2: "Une plantation, c’est une chaîne d’approvisionnement miniature",
    empathyBody: "≠ devis paysagisme global. Focus massifs/plantations/engazonnement et garantie reprises. One-shot, oui — mais un one-shot mal tracé coûte une saison.",
    showcaseTitle: "Jalons plantation sur un chantier résidence",
    showcaseSub: "Livraison → pose → arrosages de reprise → contrôle.",
    showcaseBadgeLeft: {"title":"Massif nord","sub":"4 jalons"},
    showcaseBadgeRight: "Reprise OK",
    proofH2: "Ce qu’un suivi plantation change",
    proofQuote: "Moins de plants morts « mystérieux », plus de preuves de suivi.",
    proofItems: [{"title":"Fenêtres","text":"Pose calée sur météo et disponibilité équipe."},{"title":"Reprise","text":"Passages d’arrosage / contrôle planifiés, pas oubliés."},{"title":"Preuve","text":"Photos et pointages pour clôturer sereinement."}],
    vsTitle: "Pose one-shot vs chantier plantation suivi",
    demo: d(
      "Démo produit · plantations",
      "Suivre un massif de la livraison au contrôle J+21",
      "Walkthrough d’un chantier plantation résidence avec jalons et preuves.",
      "Résidence Les Tilleuls — massif entrée. Plants livrés mardi. Pose mercredi-jeudi. Deux arrosages de reprise. Contrôle J+21 avant facture finale.",
      [
        s("Créer le chantier", "Lier devis plantation + site + consignes accès."),
        s("Jalons", "Livraison, pose J1/J2, reprise, contrôle."),
        s("Météo", "Reporter la pose si gel/pluie — sans perdre les jalons suivants."),
        s("Clôturer", "Photos reprise + facture du réalisé."),
      ],
      "Chantier · Massif Tilleuls",
      [
        r("Livraison plants", "Mar 10h · quai", "Fait"),
        r("Pose massif", "Mer–Jeu · équipe C", "En cours"),
        r("Arrosage reprise", "S+1 et S+2", "Planifié"),
        r("Contrôle J+21", "Photo + validation", "À faire"),
      ],
      "La plantation devient un fil d’interventions — pas un souvenir de chantier.",
      "Essai — mes plantations",
      "Voir paysagisme",
      "checklist",
    ),
    bodySections: [
      {
        h2: "Cas — Massifs résidence, livraison → pose → J+21",
        body: "Jalon fournitures. Blocage pose si plants absents. Photos pose. Contrôle reprise planifié. Écarts tracés pour le client.",
        bullets: [
          "Dépendance livraison",
          "Fenêtre de pose",
          "Garantie reprises",
        ],
      },
      {
        h2: "≠ irrigation",
        body: "Après la pose, l’eau = page arrosage. Ici la mise en place.",
      },
      {
        h2: "Livrable",
        body: "Dossier plantation + photos + date contrôle reprise.",
      }
    ],
    faq: [
      {
        q: "Fournitures client vs entreprise ?",
        a: "Notez la responsabilité sur le jalon livraison pour éviter le flou.",
      },
      {
        q: "Report gel / canicule ?",
        a: "Motif météo sur la fenêtre de pose — comme un playbook.",
      },
      {
        q: "Engazonnement inclus ?",
        a: "Oui comme jalon distinct si besoin.",
      },
      {
        q: "Lien aménageurs ?",
        a: "Souvent — réception promoteur s’appuie sur ces jalons.",
      },
      {
        q: "L’essai couvre-t-il vraiment « évacuation déchets verts espaces verts » ?",
        a: "15 jours — 1 chantier plantation réel.",
      },
    ],
    gridItems: [
      link("Paysagisme", "Devis & chantiers création", "/espace-vert/paysagisme"),
      link("Arrosage", "Reprises et contrôles", "/espace-vert/arrosage-irrigation"),
      link("Photos AV/AP", "Preuves visuelles", "/espace-vert/photos-avant-apres"),
    ],
    ctaPrimaryLabel: "Essai 15 j — plantations",
    ctaSecondaryLabel: "Démo chantier plantation",
  },
  {
    id: "EV-35",
    key: "hopitaux-cliniques",
    path: "/espace-vert/hopitaux-cliniques",
    type: "audience",
    primaryKw: "entretien espaces verts hôpital clinique",
    seoTitle: "Espaces verts hôpitaux & cliniques — créneaux et zones interdites",
    seoDesc: "EV sites santé : tonte 6h–8h, zones hélistation interdites, preuves direction achats. Contraintes ≠ site privé classique. Essai 15 j.",
    crumbLabel: "Hôpitaux & cliniques",
    h1Lead: "Espaces verts en établissements de santé",
    h1: "créneaux stricts, zones sensibles, preuves pour les achats",
    sub: "Clinique des Cèdres : tonte avant 8h, hélistation intouchable, badge, silence engins près des chambres. Un site privé « normal » n’a pas ces règles.",
    claimBefore: "Des abords soignés sans",
    claimHighlight: "perturber le soin",
    claimSub: "hôpitaux · cliniques · EHPAD",
    productStrip: "Santé · accès · preuves EV",
    empathyH2: "Au mauvais endroit à la mauvaise heure, vous sortez du site",
    empathyBody: "Protocoles accès, horaires stricts, image/hygiène des abords, interlocuteur achats : la page sites privés ne suffit pas. Intent santé dédié.",
    showcaseTitle: "Sites santé avec contraintes visibles",
    showcaseSub: "Créneaux, zones interdites, preuves pour le donneur d’ordre.",
    showcaseBadgeLeft: {"title":"Clinique","sub":"6h–8h only"},
    showcaseBadgeRight: "Conforme",
    proofH2: "Ce qu’attend un établissement de santé",
    proofQuote: "Discrétion, ponctualité, traçabilité — pas un discours SaaS.",
    proofItems: [{"title":"Créneaux","text":"Passages hors pics de consultation / repos patients."},{"title":"Zones","text":"Hélistation, urgences, accès ambulances : consignes explicites."},{"title":"Preuves","text":"Historique pour marchés et contrôles qualité."}],
    vsTitle: "Site privé générique vs site santé contraint",
    demo: d(
      "Démo produit · sites santé",
      "Planifier une clinique avec créneau 6h–8h et zone hélistation",
      "Walkthrough d’une tournée abords cliniques sous contraintes d’accès.",
      "Clinique 180 lits. Tonte + haies. Passage autorisé 6h–8h en semaine. Zone hélistation interdite aux engins. Direction achats demande preuve mensuelle.",
      [
        s("Fiche site", "Créneaux, contacts sécurité, zones interdites."),
        s("Planifier", "Équipe A mardi 6h15 — hors réveil patients étage jardin."),
        s("Pointer", "Arrivée/départ + photo haie entrée."),
        s("Reporting", "Export mensuel pour le marché."),
      ],
      "Site · Clinique des Cèdres",
      [
        r("Tonte parkings", "Mar 6h15–7h40", "OK"),
        r("Haie entrée", "Mar 7h40 · photo", "OK"),
        r("Zone hélistation", "Interdit engins", "Contrainte"),
        r("Report achats", "Mensuel S18", "Prêt"),
      ],
      "Les contraintes santé sont dans le planning — plus dans la tête du seul chef d’équipe.",
      "Essai — sites santé",
      "Voir sites privés",
      "board",
    ),
    bodySections: [
      {
        h2: "Cas — Planning clinique avec zones interdites",
        body: "Créneau 6h–8h. Zone hélistation bloquée software-side (consigne forte). Preuve mensuelle pour la direction des achats. Intérim briefé via fiche site.",
        bullets: [
          "Créneaux non négociables",
          "Zones interdites visibles",
          "Reporting achats",
        ],
      },
      {
        h2: "≠ écoles (créneaux enfants)",
        body: "Même famille contraintes, autre régulateur (récré vs soins/héliport).",
      },
      {
        h2: "Objection « comme un site privé »",
        body: "Jusqu’au premier refus d’accès pour non-respect d’horaire.",
      }
    ],
    faq: [
      {
        q: "EHPAD inclus ?",
        a: "Oui — mêmes logiques de créneaux et discrétion.",
      },
      {
        q: "Hygiène / déchets verts près des bâtiments ?",
        a: "Évacuation rapide — lier page déchets verts.",
      },
      {
        q: "Astreinte tempête ?",
        a: "Interventions ponctuelles hors créneau avec validation site.",
      },
      {
        q: "Multi-établissements d’un groupe santé ?",
        a: "Portefeuille client avec règles par site.",
      },
      {
        q: "Comment démarrer un essai orienté évacuation déchets verts espaces verts ?",
        a: "15 jours — 1 clinique pilote avec vraies consignes.",
      },
    ],
    gridItems: [
      link("Sites privés", "Autres B2B contraints", "/espace-vert/entreprises-sites-prives"),
      link("Preuves de passage", "Pour les achats", "/espace-vert/preuves-passages"),
      link("Collectivités", "Marchés publics proches", "/espace-vert/collectivites"),
    ],
    ctaPrimaryLabel: "Essai 15 j — EV santé",
    ctaSecondaryLabel: "Parler contraintes accès",
  },
  {
    id: "EV-36",
    key: "ecoles-etablissements",
    path: "/espace-vert/ecoles-etablissements",
    type: "audience",
    primaryKw: "entretien espaces verts écoles collèges",
    seoTitle: "Espaces verts écoles & établissements — hors récré, vacances",
    seoDesc: "Écoles, collèges, lycées, crèches : tonte hors récréation, densification vacances, sécurité enfants. ≠ collectivités global. Essai 15 j.",
    crumbLabel: "Écoles & établissements",
    h1Lead: "Espaces verts des établissements scolaires",
    h1: "intervenir hors récré, densifier les vacances",
    sub: "12 écoles : tonte mercredi AM, zéro engin pendant la récré, planning vacances densifié. La page collectivités est trop large pour cet intent.",
    claimBefore: "Des cours entretenues sans",
    claimHighlight: "engins à la récré",
    claimSub: "écoles · collèges · crèches",
    productStrip: "Scolaire · créneaux · vacances",
    empathyH2: "Le créneau scolaire est une contrainte dure — pas une préférence",
    empathyBody: "Sécurité enfants, bruit, vacances : si votre planning traite une école comme une ZA, vous allez au conflit direction / parents. Intent dédié.",
    showcaseTitle: "Tournée scolaire calée sur la vie de l’établissement",
    showcaseSub: "Mercredis, matins tôt, vacances — pas de conflit avec les enfants.",
    showcaseBadgeLeft: {"title":"12 écoles","sub":"Vacances OK"},
    showcaseBadgeRight: "Sécurisé",
    proofH2: "Ce qu’attend un établissement",
    proofQuote: "Sécurité des enfants d’abord, pelouse ensuite — dans cet ordre.",
    proofItems: [{"title":"Hors récré","text":"Créneaux visibles pour chaque établissement."},{"title":"Vacances","text":"Charge densifiée quand le site est vide."},{"title":"Trace","text":"Utile pour la régie et les élus parents."}],
    vsTitle: "Passage « quand on peut » vs planning scolaire",
    demo: d(
      "Démo produit · écoles",
      "Construire la tournée de 12 écoles hors récréation",
      "Walkthrough : créneaux mercredi / matin tôt + sprint vacances de février.",
      "Commune : 12 écoles. Interdiction engins pendant récré et sortie. Tonte préférée mercredi matin ou 6h30. Vacances = semaine dense.",
      [
        s("Consignes", "Horaires récré / sortie par école."),
        s("Tournée type", "Mercredi AM : 6 écoles · vendredi 6h30 : 3 autres."),
        s("Vacances", "Basculer charge restante sur la zone."),
        s("Preuve", "Pointages pour la régie."),
      ],
      "Scolaire · Semaine type",
      [
        r("Jules Ferry", "Mer 7h–9h · hors récré", "OK"),
        r("Maternelle Pins", "Ven 6h30", "OK"),
        r("Collège Vigny", "Vacances fév. · dense", "Planifié"),
        r("Crèche Centre", "Accès jardin verrouillé", "Consignes"),
      ],
      "Le calendrier scolaire devient une contrainte de planning — plus une surprise terrain.",
      "Essai — tournée écoles",
      "Voir collectivités",
      "split",
    ),
    bodySections: [
      {
        h2: "Cas — 12 écoles, mercredi AM + vacances",
        body: "Fenêtres hors récré. Vacances : densification tonte/haies. Jour de rentrée : sites prioritaires faits. Consignes déposées sur chaque fiche établissement.",
        bullets: [
          "Horaires scolaires",
          "Densification vacances",
          "Zéro engin en récré",
        ],
      },
      {
        h2: "≠ collectivités transverse",
        body: "La collectivité page couvre le marché. Ici l’opérationnel établissements.",
      },
      {
        h2: "Livrable direction / DST",
        body: "Calendrier interventions aligné vacances + preuves périodes sensibles.",
      }
    ],
    faq: [
      {
        q: "Crèches / centres de loisirs ?",
        a: "Oui — mêmes règles de créneaux et discrétion.",
      },
      {
        q: "Vacances scolaires différentes selon zones ?",
        a: "Profils calendaires par établissement.",
      },
      {
        q: "Travaux lourds élagage ?",
        a: "Uniquement hors présence élèves — créneau bloqué.",
      },
      {
        q: "Lien cimetières/voirie ?",
        a: "Autre niche ; maillage possible via hub.",
      },
      {
        q: "Y a-t-il un essai sans engagement pour évacuation déchets verts espaces verts ?",
        a: "15 jours — 3 écoles pilotes + 1 période de vacances.",
      },
    ],
    gridItems: [
      link("Collectivités", "Cadre marchés / régie", "/espace-vert/collectivites"),
      link("Cimetières & voirie", "Autres sites publics", "/espace-vert/cimetieres-voirie"),
      link("Planning équipes", "Affectation créneaux", "/espace-vert/planning-equipes"),
    ],
    ctaPrimaryLabel: "Essai 15 j — EV scolaire",
    ctaSecondaryLabel: "Parler créneaux écoles",
  },
];
