/* eslint-disable */
import { link, type EvPageSpec } from "./build";

const d = (
  eyebrow: string,
  h2: string,
  lead: string,
  scenario: string,
  steps: EvPageSpec["demo"]["steps"],
  uiLabel: string,
  uiRows: EvPageSpec["demo"]["uiRows"],
  takeaway: string,
  primaryCtaLabel?: string,
  secondaryCtaLabel?: string,
  variant?: EvPageSpec["demo"]["variant"],
  extra?: Pick<EvPageSpec["demo"], "uiToolbar" | "uiAlert" | "uiHint" | "uiSplitLabels" | "uiColumns">,
): EvPageSpec["demo"] => ({
  eyebrow, h2, lead, scenario, steps, uiLabel, uiRows, takeaway,
  primaryCtaLabel, secondaryCtaLabel, variant, ...extra,
});

const s = (label: string, detail: string) => ({ label, detail });

/** EV-37 → EV-39 — gaps SEO */
export const evSpecsPart6: EvPageSpec[] = [
  {
    id: "EV-37",
    key: "zero-phyto-biodiversite",
    path: "/espace-vert/zero-phyto-biodiversite",
    type: "service",
    primaryKw: "zéro phyto espaces verts logiciel",
    seoTitle: "Zéro phyto & biodiversité — planning EV sans chimie",
    seoDesc: "Désherbage mécanique/thermique, fauche différenciée, reporting zéro phyto pour marchés et syndics. Intent réglementaire + terrain. Essai 15 j.",
    crumbLabel: "Zéro phyto & biodiversité",
    h1Lead: "Zéro phyto & fauche différenciée",
    h1: "prouver la méthode, pas seulement tondre moins",
    sub: "Depuis le zéro phyto, vos marchés demandent une méthode et une preuve — pas une promesse. La fauche différenciée ajoute des zones « laissez faire » à piloter.",
    claimBefore: "De la consigne",
    claimHighlight: "à la preuve",
    claimSub: "zéro phyto · biodiversité · marchés",
    productStrip: "Méthodes · zones · reporting",
    empathyH2: "Le zéro phyto sans traçabilité, c’est du slogan",
    empathyBody: "Élus et syndics demandent : quelle méthode, où, quand. Si la réponse est « on fait de notre mieux », vous perdez le renew. Intent distinct du désherbage opérationnel pur.",
    showcaseTitle: "Zones différenciées lisibles pour le terrain",
    showcaseSub: "Mécanique, thermique, fauche tardive — consignes sur la carte opérationnelle.",
    showcaseBadgeLeft: {"title":"Zéro phyto","sub":"Méthode tracée"},
    showcaseBadgeRight: "Reporting OK",
    proofH2: "Ce que le donneur d’ordre veut voir",
    proofQuote: "Méthode + zone + date + photo du point de contrôle.",
    proofItems: [{"title":"Méthode par zone","text":"Mécanique, thermique, fauche différenciée — pas un flou « on évite les produits »."},{"title":"Preuves marché","text":"Export pour DST / élus sur la période."},{"title":"Formation terrain","text":"Consignes visibles pour saisonniers."}],
    vsTitle: "Promesse zéro phyto vs exécution tracée",
    demo: d(
      "Démo · zéro phyto",
      "Audit méthode : zones, consignes, export DST",
      "Montrez en un écran que le zéro phyto n’est pas un slogan.",
      "DST demande un export S16–S18. L’exploitation filtre par méthode et joint 3 photos de points de contrôle (école, cimetière, terre-plein).",
      [
        s("Zones & méthodes", "Mécanique / thermique / fauche différenciée sur la fiche zone."),
        s("Exécution", "Terrain voit la consigne ; coche zone par zone."),
        s("Preuves", "Photos points de contrôle exigés au marché."),
        s("Export", "PDF méthodes + dates pour le DST."),
      ],
      "Zéro phyto · Audit S16–S18",
      [
        { left: "École — mécanique", right: "12 passages", status: "OK", meta: "Photo contrôle OK", tone: "ok" },
        { left: "Cimetière — manuel", right: "8 passages", status: "OK", meta: "Zéro thermique near monuments", tone: "ok" },
        { left: "Noue — fauche différenciée", right: "Fenêtre tardive", status: "Respectée", meta: "Pas de tonte précoce", tone: "ok" },
        { left: "Terre-plein RD — photo", right: "Point contrôle", status: "Manquant", meta: "Bloque export", tone: "danger" },
      ],
      "Le renew marché se défend avec des méthodes datées, pas avec une présentation PowerPoint.",
      "Essayer sur mon marché",
      "Voir désherbage opérationnel",
      "checklist",
      {"uiToolbar":"Marché · Méthodes · Export DST","uiAlert":"3 points de contrôle photo manquants avant export — bloquant audit","uiHint":"Slogan → preuve · zones biodiversité protégées du « tondu par erreur »"},
    ),
    bodySections: [
    {
      h2: "Cas — Marché communal, audit méthode S18",
      body: "Chaque zone a une méthode. Les saisonniers voient la consigne. Le DST reçoit l’export : 42 interventions mécaniques, 11 thermiques, 6 fauches différenciées.",
      bullets: ["Consignes méthode","Zones biodiversité","Export audit"],
    },
    {
      h2: "≠ page désherbage seule",
      body: "Désherbage = exécuter. Ici = prouver le cadre zéro phyto / biodiversité.",
    },
    {
      h2: "Livrable",
      body: "Rapport méthodes + cartes zones + photos points de contrôle.",
    },
    ],
    faq: [
    { q: "Remplace-t-il un plan de gestion différenciée ?", a: "Non — il exécute et prouve. Le plan reste votre document cadre." },
    { q: "Fauche tardive / biodiversité ?", a: "Zones marquées « différenciées » avec fenêtre de fauche — le terrain ne tond pas par erreur." },
    { q: "Produits de biocontrôle ?", a: "Notez la méthode autorisée sur la zone ; traçabilité d’usage selon vos process." },
    { q: "Lien cimetières ?", a: "Souvent prioritaire en zéro phyto — maillage utile." },
    { q: "Puis-je tester PROGESTI sur mon cas « zéro phyto espaces verts logiciel » ?", a: "15 jours — 1 marché ou 5 résidences en méthode tracée." },
    ],
    gridItems: [
      link("Désherbage opérationnel", "Tournées zones", "/espace-vert/desherbage"),
      link("Collectivités", "Reporting marchés", "/espace-vert/collectivites"),
      link("Cimetières & voirie", "Zones sensibles", "/espace-vert/cimetieres-voirie"),
    ],
    ctaPrimaryLabel: "Essai 15 jours — mes sites",
    ctaSecondaryLabel: "Parler à un humain",
  },
  {
    id: "EV-38",
    key: "marches-publics",
    path: "/espace-vert/marches-publics",
    type: "process",
    primaryKw: "marché public espaces verts logiciel",
    seoTitle: "Marchés publics espaces verts — exécution & reporting bordereau",
    seoDesc: "Réponse opérationnelle aux marchés publics EV : bordereau, lots, preuves, pénalités évitées. Pour prestataires et régies. Essai 15 j.",
    crumbLabel: "Marchés publics EV",
    h1Lead: "Exécuter un marché public EV",
    h1: "du bordereau aux preuves, sans pénalités surprises",
    sub: "Vous avez gagné le marché. Maintenant il faut l’exécuter sans pénalité. Le bordereau n’est pas un Excel mort : c’est le planning.",
    claimBefore: "Du CCTP à",
    claimHighlight: "l’exécution",
    claimSub: "marchés publics · lots · reporting",
    productStrip: "Lots · fréquences · preuves marché",
    empathyH2: "Gagner le marché est une étape — ne pas le perdre en est une autre",
    empathyBody: "Lots, fréquences CCTP, points de contrôle, reports motivés : la page collectivités parle DST. Ici l’angle prestataire / exécution marché public et anti-pénalités.",
    showcaseTitle: "Bordereau vivant",
    showcaseSub: "Chaque ligne du marché devient des occurrences planifiées et prouvables.",
    showcaseBadgeLeft: {"title":"Lot 2","sub":"Voirie végétale"},
    showcaseBadgeRight: "Conforme",
    proofH2: "Anti-pénalités par la trace",
    proofQuote: "Retard motivé > retard silencieux.",
    proofItems: [{"title":"Lots & sites","text":"Structurez comme le marché, pas comme votre tournée historique."},{"title":"Preuves CCTP","text":"Points de contrôle photographiés."},{"title":"Reporting","text":"Exports périodiques pour le pouvoir adjudicateur."}],
    vsTitle: "Excel de suivi de marché vs exécution vivante",
    demo: d(
      "Démo · marchés publics",
      "Conformité lot 2 : retards motivés avant la réunion de chantier",
      "Transformez le bordereau en occurrences + preuves.",
      "Réunion de chantier jeudi. Le chef de projet ouvre le lot 2 : 2 retards orage motivés, 1 accès refusé photographié, export prêt.",
      [
        s("Mapper le lot", "Sites/zones = lignes du bordereau."),
        s("Exécuter", "Tournées + pointages."),
        s("Motiver les écarts", "Météo / accès — jamais le silence."),
        s("Exporter", "PDF conformité pour le pouvoir adjudicateur."),
      ],
      "Marché · Lot 2 · Conformité",
      [
        { left: "Terre-plein RD12", right: "Report orage", status: "Motif OK", meta: "Annexe météo", tone: "warn" },
        { left: "Square Hugo", right: "Accès refusé", status: "Photo", meta: "Véhicule chantier ville", tone: "warn" },
        { left: "Parc Central", right: "Conforme S18", status: "OK", meta: "Points CCTP", tone: "ok" },
        { left: "Export réunion", right: "PDF prêt", status: "Envoyé", meta: "J-1", tone: "ok" },
      ],
      "Un écart motivé se défend ; un écart silencieux se pénalise.",
      "Essayer sur mon marché",
      "Voir angle collectivités",
      "split",
      {"uiToolbar":"MP · Lot 2 · Réunion chantier jeu.","uiAlert":"2 retards motivés orage — export annexé avant réunion","uiHint":"Anti-pénalités · bordereau vivant · pas un Excel mort","uiSplitLabels":["Écarts","Défense"]},
    ),
    bodySections: [
    {
      h2: "Cas — Prestataire, marché 3 lots, mois 2",
      body: "Écarts sur lot 2 terre-pleins. Reports orage documentés. Export envoyé avant la réunion de chantier. Pénalité évitée faute de silence.",
      bullets: ["Structure lots","Motifs opposables","Réunion de chantier préparée"],
    },
    {
      h2: "≠ collectivités (audience DST)",
      body: "Même famille, intent prestataire / anti-pénalités / bordereau.",
    },
    {
      h2: "Livrable",
      body: "Tableau conformité période + annexes photo.",
    },
    ],
    faq: [
    { q: "Rédige-t-on les mémoires techniques ?", a: "Non — on exécute et on prouve après notification." },
    { q: "Pénalités de retard ?", a: "La traçabilité des motifs (météo, accès) est votre première défense." },
    { q: "Comment gérer la sous-traitance sur un marché public EV ?", a: "Affectez clairement qui exécute quel lot/site." },
    { q: "Différence renew privé ?", a: "Page contrats annuels pour le privé ; ici formalisme marché public." },
    { q: "L’essai couvre-t-il vraiment « zéro phyto espaces verts logiciel » ?", a: "15 jours — 1 lot pilote de votre marché en cours." },
    ],
    gridItems: [
      link("Collectivités", "Angle DST", "/espace-vert/collectivites"),
      link("Zéro phyto", "Méthodes tracées", "/espace-vert/zero-phyto-biodiversite"),
      link("Contrats annuels", "Renew privé", "/espace-vert/contrats-annuels"),
    ],
    ctaPrimaryLabel: "Essai 15 jours — mes sites",
    ctaSecondaryLabel: "Parler à un humain",
  },
  {
    id: "EV-39",
    key: "ouverture-saison",
    path: "/espace-vert/ouverture-saison",
    type: "guide",
    primaryKw: "ouverture saison espaces verts planning",
    seoTitle: "Ouverture de saison espaces verts — check-list mars",
    seoDesc: "Check-list ouverture de saison EV : engins, fréquences, saisonniers, clients critiques. Pont entre hiver et sprint printemps. Essai 15 j.",
    crumbLabel: "Ouverture de saison",
    h1Lead: "Ouverture de saison EV",
    h1: "la check-list de février qui sauve le mois de mars",
    sub: "Fin février : avant la bascule hebdo, vérifiez engins, fréquences, digicodes, saisonniers. L’ouverture de saison ratée se paie jusqu’à juin.",
    claimBefore: "Préparer la",
    claimHighlight: "montée",
    claimSub: "ouverture saison · engins · fréquences",
    productStrip: "Check-list · engins · saisonniers",
    empathyH2: "Le printemps commence en février — sur une check-list",
    empathyBody: "La page printemps traite la montée en charge. Ici le rituel d’ouverture : atelier engins, audit digicodes, profils saisonniers, clients renew. Intent « préparer la saison » souvent cherché tel quel.",
    showcaseTitle: "Rituel d’ouverture lisible",
    showcaseSub: "Engins, sites, équipes, clients critiques — cochés avant la pousse.",
    showcaseBadgeLeft: {"title":"Février","sub":"S8–S9"},
    showcaseBadgeRight: "Prêt mars",
    proofH2: "Ce que vous validez avant S10",
    proofQuote: "Autoportée OK, digicodes OK, fréquences densifiées, saisonniers briefés.",
    proofItems: [{"title":"Engins","text":"Atelier avant la panne du premier beau lundi."},{"title":"Fréquences","text":"Profil printemps prêt à activer."},{"title":"Humains","text":"Saisonniers + backups absences."}],
    vsTitle: "Improviser mars vs ouvrir la saison en février",
    demo: d(
      "Démo · ouverture saison",
      "Check-list S8–S9 : engins, digicodes, densification",
      "Le rituel qui évite le chaos du premier beau lundi.",
      "Fin février, Julie ouvre la check-list : autoportée #2 encore chez le mécano, 6 digicodes obsolètes, profil printemps prêt, 2 saisonniers briefés.",
      [
        s("Atelier engins", "Clos ou date de retour claire."),
        s("Audit accès", "Digicodes / badges mis à jour."),
        s("Profil fréquences", "Densification prête à activer S10."),
        s("Brief humains", "Saisonniers + backups absences."),
      ],
      "Ouverture saison · Check-list S9",
      [
        { left: "Atelier autoportée #1", right: "OK", status: "Fait", meta: "S8", tone: "ok" },
        { left: "Autoportée #2", right: "Mécano", status: "Risque", meta: "Retour S11 ?", tone: "danger" },
        { left: "Digicodes (38 sites)", right: "6 obsolètes corrigés", status: "Fait", meta: "Audit S9", tone: "ok" },
        { left: "Profil printemps", right: "Densification prête", status: "Armé", meta: "Activation S10", tone: "info" },
      ],
      "Si la check-list est verte en S9, mars redevient un plan — plus une salle d’urgence.",
      "Lancer ma check-list",
      "Voir montée printemps",
      "checklist",
      {"uiToolbar":"Février · S9 · Go mars","uiAlert":"Autoportée #2 toujours mécano — capacité tonte limitée semaine 10","uiHint":"Rituel février · sprint mars · ≠ page printemps charge"},
    ),
    bodySections: [
    {
      h2: "Check-list ouverture (ordre)",
      body: "1) Atelier engins. 2) Audit accès/digicodes. 3) Activer profil fréquences. 4) Brief saisonniers. 5) Liste clients renew < 90 j. 6) Buffer météo élargi.",
      bullets: ["S8 atelier","S9 paramétrage","S10 go densification"],
    },
    {
      h2: "≠ page printemps",
      body: "Printemps = vivre la charge. Ouverture = rituel avant le sprint.",
    },
    {
      h2: "Livrable interne",
      body: "Check-list cochée + responsables + dates.",
    },
    ],
    faq: [
    { q: "Quand démarrer l’ouverture ?", a: "S7–S9 selon région — en Occitanie souvent fin février." },
    { q: "Et si on découvre une panne engins trop tard ?", a: "C’est exactement ce que la check-list évite — bloquez l’atelier en S8." },
    { q: "Saisonniers pas encore recrutés ?", a: "Préparez les fiches sites / backups ; intégrez dès J1 recrutement." },
    { q: "Lien guide organiser entretien ?", a: "Le guide est structure permanente ; l’ouverture est le rituel saisonnier." },
    { q: "Comment démarrer un essai orienté zéro phyto espaces verts logiciel ?", a: "15 jours en février — cocher la check-list sur le vrai portefeuille." },
    ],
    gridItems: [
      link("Saison printemps", "Montée en charge", "/espace-vert/saison-printemps"),
      link("Engins", "Conflits & atelier", "/espace-vert/engins-materiel"),
      link("Absences", "Backups", "/espace-vert/absences-remplacements"),
    ],
    ctaPrimaryLabel: "Essai 15 jours — mes sites",
    ctaSecondaryLabel: "Parler à un humain",
  },
];
