/* eslint-disable */
import { link, type EvPageSpec } from "./build";

const d = (
  eyebrow: string,
  h2: string,
  lead: string,
  scenario: string,
  steps: EvPageSpec["demo"]["steps"],
  uiLabel: string,
  uiRows: EvPageSpec["demo"]["uiRows"],
  takeaway: string,
  primaryCtaLabel?: string,
  secondaryCtaLabel?: string,
  variant?: EvPageSpec["demo"]["variant"],
): EvPageSpec["demo"] => ({
  eyebrow, h2, lead, scenario, steps, uiLabel, uiRows, takeaway, primaryCtaLabel, secondaryCtaLabel, variant,
});
const s = (label: string, detail: string) => ({ label, detail });
const r = (left: string, right: string, status?: string) => ({ left, right, status });

/** EV-17 → EV-24 */
export const evSpecsPart3: EvPageSpec[] = [
  {
    id: "EV-17",
    key: "multi-sites",
    path: "/espace-vert/multi-sites",
    type: "process",
    primaryKw: "gestion multi-sites espaces verts",
    seoTitle: "Multi-sites espaces verts — portefeuille, retards, filtres",
    seoDesc: "30 à 200+ sites : vision retards, filtres commune/type, priorités semaine. Différent des grands parcs (1 site N zones). Essai 15 j.",
    crumbLabel: "Multi-sites",
    h1Lead: "Multi-sites espaces verts",
    h1: "quand le carnet grossit, gardez une vision claire des sites",
    sub: "120 sites, 4 communes, 3 types de contrats : sans vue portefeuille, vous pilotez au téléphone. Excel « filtrable » devient un mensonge dès que le terrain bouge.",
    claimBefore: "Un portefeuille",
    claimHighlight: "lisible",
    claimSub: "gestion multi-sites espaces verts",
    productStrip: "Multi-sites · vision · priorités",
    empathyH2: "Le problème n’est pas d’avoir des sites : c’est de voir les 8 critiques",
    empathyBody: "Parmi 120 fiches, 8 ont un retard, 3 un accès refusé, 2 un renew dans 30 jours. Si vous ne les sortez pas en 2 minutes, vous subissez la semaine au lieu de la diriger.",
    showcaseTitle: "Portefeuille EV en un coup d’œil",
    showcaseSub: "Sites, statuts de la semaine, alertes retards.",
    showcaseBadgeLeft: { title: "78 sites", sub: "5 secteurs" },
    showcaseBadgeRight: "3 alertes",
    proofH2: "Ce que change une vraie vision multi-sites",
    proofQuote: "Moins d’oublis, meilleure densité de tournée, priorités assumées.",
    proofItems: [
      { title: "Cartographie opérationnelle", text: "Secteurs / typologies / clients." },
      { title: "Alertes", text: "Retards de fréquence visibles avant la réclamation." },
      { title: "Croissance", text: "Intégrer de nouveaux sites sans casser le système." },
    ],
    vsTitle: "Carnet d’adresses Excel vs portefeuille EV",
    demo: d(
      "Démo produit · multi-sites",
      "Repérer en 30 secondes les sites en retard de fréquence",
      "Cas croissance : 78 sites, 3 alertes « fréquence dépassée » avant que le client n’appelle.",
      "PME passée de 30 à 78 sites en 18 mois. Le gérant ouvre le lundi et veut les exceptions, pas la liste complète.",
      [
        s("Vue portefeuille", "Filtrer « retard vs fréquence contractuelle »."),
        s("Trier", "Priorité syndic / collectivité d’abord."),
        s("Action", "Insérer rattrapage dans la tournée du jour."),
        s("Contrôle", "Alerte levée dès pointage effectué."),
      ],
      "Portefeuille · Alertes S19",
      [
        r("Résidence Acacias", "Tonte due depuis 4 j", "Alerte"),
        r("Mairie — square Nord", "Désherbage dû", "Alerte"),
        r("ZA Horizon — bande A", "Haies dues S18", "Alerte"),
        r("Autres 75 sites", "Dans les clous", "OK"),
      ],
      "Le multi-sites se pilote par exceptions — pas en relisant 78 lignes.",
      "Essai — mon portefeuille",
      "Voir planning équipes",
      "split"
    ),
    bodySections: [
      {
        h2: "Cas — Portefeuille 120 sites, lundi 7h",
        body: "Filtre : retard > 7 j + commune + type tonte. Liste des 8 critiques. Arbitrage : 5 rattrapages, 2 reports clients informés, 1 litige preuves. Le reste de la semaine redevient exécutable.",
        bullets: [
          "Filtres métier (pas seulement alpha)",
          "Retards = objets actionnables",
          "Reporting client sur extrait, pas sur tout le portefeuille",
        ],
      },
      {
        h2: "≠ grands parcs",
        body: "Grands parcs = 1 adresse, N zones. Multi-sites = N adresses. Intentions Google différentes.",
      },
      {
        h2: "Objection Excel",
        body: "Le filtre Excel est froid : il n’inclut pas le pointage de 9h ni le statut mobile.",
      }
    ],
    faq: [
      {
        q: "Combien de sites avant que ça vaille le coup ?",
        a: "Dès 25–30, la vue portefeuille bat le tableur. À 100+, c’est vital.",
      },
      {
        q: "Multi-sociétés / multi-dépôts ?",
        a: "Organisez par équipes/secteurs ; l’essai montre le bon découpage.",
      },
      {
        q: "Y a-t-il une cartographie pour « gestion multi-sites espaces verts » ?",
        a: "L’essentiel est la liste actionnable + planning ; la carte ne remplace pas les statuts.",
      },
      {
        q: "Lien collectivités multi-sites ?",
        a: "Oui — même logique, reporting marché en plus.",
      },
      {
        q: "Puis-je tester PROGESTI sur mon cas « gestion multi-sites espaces verts » ?",
        a: "15 jours — importez un extrait réel (30 sites min).",
      },
    ],
    gridItems: [
      link("Petites entreprises", "Si vous démarrez plus petit", "/espace-vert/petites-entreprises"),
      link("Grands parcs", "Un site, beaucoup de zones", "/espace-vert/grands-parcs"),
      link("Planning équipes", "Exécuter le portefeuille", "/espace-vert/planning-equipes"),
      link("Logiciel EV", "Pilier", "/logiciel-espace-vert"),
    ],
    ctaPrimaryLabel: "Essai — portefeuille multi-sites",
    ctaSecondaryLabel: "Démo alertes retards",
  },
  {
    id: "EV-18",
    key: "toulouse-occitanie",
    path: "/espace-vert/toulouse-occitanie",
    type: "local",
    primaryKw: "logiciel espaces verts Toulouse",
    seoTitle: "Logiciel espaces verts Toulouse & Occitanie — éditeur local",
    seoDesc: "PME EV Toulouse métropole / Occitanie : essai sur vos sites périurbains, support joignable en 31. Pas une landing ville fantôme.",
    crumbLabel: "Toulouse & Occitanie",
    h1Lead: "Logiciel espaces verts à Toulouse & en Occitanie",
    h1: "un éditeur local qui parle tournées, météo et chantiers du Sud-Ouest",
    sub: "Tournefeuille, Blagnac, sud Tarn : le climat, les pousses et les clients ne sont pas ceux d’une slide parisienne. Vous voulez un éditeur qui connaît le terrain sud-ouest.",
    claimBefore: "Un outil EV",
    claimHighlight: "ancré à Toulouse",
    claimSub: "logiciel espaces verts Toulouse",
    productStrip: "Toulouse · Occitanie · support FR",
    empathyH2: "« Cloud » n’empêche pas d’avoir besoin d’humain à Toulouse",
    empathyBody: "Quand le paramétrage bloque un lundi de mars, vous ne voulez pas un ticket anonyme à 6 fuseaux horaires. Support FR, exemples locaux, essai sur de vrais sites de la métropole.",
    showcaseTitle: "Proximité + logiciel terrain",
    showcaseSub: "Essai sur vos sites d’Occitanie, support basé en Haute-Garonne.",
    showcaseBadgeLeft: { title: "Tournefeuille (31)", sub: "Support FR" },
    showcaseBadgeRight: "Essai local",
    proofH2: "Pourquoi une page locale ?",
    proofQuote: "Intent local réel + preuve de proximité (NAP) — pas du city-spam.",
    proofItems: [
      { title: "Ancrage", text: "MSNE SAS — Tournefeuille (31170), téléphone 05 82 95 09 19." },
      { title: "Usage", text: "Mêmes modules planning / pointage / factu, contextualisés EV." },
      { title: "Accompagnement", text: "Prise en main possible avec des exemples de tournées locales." },
    ],
    vsTitle: "Éditeur lointain vs support Toulouse",
    demo: d(
      "Démo produit · local Toulouse",
      "Prise en main sur un portefeuille type agglo toulousaine",
      "Scénario : 20 sites entre Toulouse, Blagnac, Tournefeuille, Labège — mix syndics + entreprises.",
      "Entreprise EV 18 salariés basée près de Toulouse. Premier paramétrage : importer / créer 20 sites représentatifs pour l’essai 15 jours.",
      [
        s("Sites pilotes", "5 syndics, 10 particuliers / petits lots, 5 entreprises ZA."),
        s("Tournées", "Secteur nord / sud / ouest — logique km réels."),
        s("Pointage", "Équipe terrain teste 3 jours."),
        s("Bilan", "Appel support Toulouse pour ajuster fréquences."),
      ],
      "Essai · Portefeuille 31",
      [
        r("Secteur Blagnac", "6 sites", "Actif"),
        r("Secteur Sud-Est", "7 sites", "Actif"),
        r("Tournefeuille / Colomiers", "7 sites", "Actif"),
        r("Support", "05 82 95 09 19", "Local"),
      ],
      "La page locale n’invente pas une usine toulousaine : elle assume la proximité réelle de l’éditeur.",
      "Essai depuis l’Occitanie",
      "Appeler le support",
      "list"
    ),
    bodySections: [
      {
        h2: "Cas — PME Tournefeuille, 22 salariés, 38 sites périurbains",
        body: "Import de 10 sites pilotes (résidences + ZA). Première semaine rejouée avec orage local. Support joignable pour caler fréquences et mobile.",
        bullets: [
          "Ancre locale réelle (pas 50 landings SEO)",
          "Essai sur votre géographie",
          "Vocabulaire clients sud : résidences, lotissements, ZA",
        ],
      },
      {
        h2: "Ce que cette page n’est pas",
        body: "Pas une copie du pilier. Angle local + confiance éditeur. Le produit reste le même ; le parcours d’essai est ancré 31/Occitanie.",
      },
      {
        h2: "Suite",
        body: "Après l’essai local → pilier / process (planning, preuves) selon douleur.",
      }
    ],
    faq: [
      {
        q: "Vous ne couvrez que Toulouse ?",
        a: "Non — le produit est national. Cette page existe parce que beaucoup cherchent un ancrage local et un support accessible.",
      },
      {
        q: "Démo sur site ?",
        a: "Démo guidée à distance + essai sur vos données. Déplacements selon contexte.",
      },
      {
        q: "Données hébergées où ?",
        a: "Cadre PROGESTI standard — détails en essai / échange commercial.",
      },
      {
        q: "Références locales ?",
        a: "On parle cas d’usage terrain sud-ouest pendant l’essai ; pas de name-dropping inventé ici.",
      },
      {
        q: "Comment démarrer sur « gestion multi-sites espaces verts » ?",
        a: "Essai 15 j — 10 sites périurbains Toulouse métropole.",
      },
    ],
    gridItems: [
      link("Logiciel EV", "Pilier national", "/logiciel-espace-vert"),
      link("Remplacer Excel", "Cas typique TPE/PME", "/espace-vert/remplacer-excel"),
      link("Contact", "Nous joindre", "/contact"),
      link("Tarifs", "Prix public", "/tarifs"),
    ],
    ctaPrimaryLabel: "Essai 15 jours",
    ctaSecondaryLabel: "Contacter Toulouse",
  },
  {
    id: "EV-19",
    key: "remplacer-excel",
    path: "/espace-vert/remplacer-excel",
    type: "probleme",
    primaryKw: "remplacer Excel espaces verts",
    seoTitle: "Remplacer Excel & WhatsApp en espaces verts — méthode",
    seoDesc: "Passez de Excel+WhatsApp à une source de vérité EV : pilote 25 sites, coupez le groupe planning, gardez WA informal. Essai 15 jours.",
    crumbLabel: "Remplacer Excel",
    h1Lead: "Remplacer Excel & WhatsApp en espaces verts",
    h1: "quand le tableur devient le risque n°1 de l’entreprise",
    sub: "Votre OS actuel : Planning_S18_final_V2.xlsx + groupe « Tournées ». Ça marche jusqu’à la première absence du gérant ou le premier litige syndic.",
    claimBefore: "Sortir du",
    claimHighlight: "tableur",
    claimSub: "remplacer Excel espaces verts",
    productStrip: "Migration · Excel · WhatsApp → PROGESTI",
    empathyH2: "Excel n’est pas l’ennemi — en faire un OS d’entreprise l’est",
    empathyBody: "Excel est excellent pour calculer. Horrible pour synchroniser 4 équipes à 7h10. WhatsApp est excellent pour la vie d’équipe. Horrible comme registre de preuves. Le remplacement se fait par pilote, pas par big bang.",
    showcaseTitle: "Avant / après opérationnel",
    showcaseSub: "Même métier, une seule source de vérité.",
    showcaseBadgeLeft: { title: "Avant", sub: "3 Excel + WA" },
    showcaseBadgeRight: "Après: 1 outil",
    proofH2: "Une migration réaliste — pas un « big bang »",
    proofQuote: "On commence par les sites critiques, pas par la perfection.",
    proofItems: [
      { title: "Semaine 1", text: "Sites pilotes + planning + pointage." },
      { title: "Semaine 2", text: "Étendre aux tournées denses." },
      { title: "Ensuite", text: "Devis / facture quand le terrain est fluide." },
    ],
    vsTitle: "Excel & WhatsApp vs PROGESTI (checklist terrain)",
    demo: d(
      "Démo produit · anti-Excel",
      "Migrer 15 sites critiques en une après-midi",
      "Atelier guidé : sortir du tableur sans arrêter l’activité.",
      "Gérant + assistante. Objectif essai : 15 sites qui font 60% des réclamations / du CA entretien.",
      [
        s("Inventaire", "Extraire du Excel : nom site, fréquence, jour habituel, équipe."),
        s("Création", "Fiches sites + fréquences dans PROGESTI."),
        s("Parallel run", "3 jours Excel + PROGESTI pour sécuriser."),
        s("Couper Excel", "Ces 15 sites ne vivent plus que dans l’outil."),
      ],
      "Migration · Sites pilotes",
      [
        r("Excel maître", "Figé en lecture seule", "Archivé"),
        r("15 sites pilotes", "Actifs PROGESTI", "Live"),
        r("Pointage équipe A", "Obligatoire pilotes", "Règle"),
        r("Reste du carnet", "Vague 2 semaine suivante", "Plan"),
      ],
      "On ne « digitalise » pas une boîte EV en un week-end : on retire le risque site par site.",
      "Démarrer la migration",
      "Voir FAQ EV",
      "split"
    ),
    bodySections: [
      {
        h2: "Méthode — 25 sites pilotes, 14 jours",
        body: "J1–2 import. J3–5 double run (Excel encore là). J6–10 mobile obligatoire sur le pilote. J11–14 : le groupe WA « planning » passe en lecture seule puis archivé. WA informal reste pour la pause café.",
        bullets: [
          "Périmètre pilote visible",
          "Critère de succès : 0 planning parallèle",
          "Mesure : appels gérant 18h en baisse",
        ],
      },
      {
        h2: "≠ pilier money",
        body: "Le pilier vend le logiciel global. Ici on vend la sortie de crise Excel/WA.",
      },
      {
        h2: "Risques à anticiper",
        body: "Chef d’équipe qui re-crée un Excel fantôme, commercial qui promet hors système, photos encore sur téléphone perso.",
      }
    ],
    faq: [
      {
        q: "Faut-il tout migrer d’un coup ?",
        a: "Non. 25 sites, une vraie saison ou une vraie montée de charge, puis élargissement.",
      },
      {
        q: "On garde WhatsApp ?",
        a: "Oui pour le social / urgence humaine. Non pour l’ordre de tournée officiel.",
      },
      {
        q: "Et les anciens historiques Excel ?",
        a: "Archivez-les. Le neuf commence à la date d’essai ; pas besoin de réécrire 5 ans.",
      },
      {
        q: "Résistance terrain ?",
        a: "Montrez que ça réduit les appels. L’adoption suit le soulagement, pas la slide.",
      },
      {
        q: "L’essai couvre-t-il vraiment « gestion multi-sites espaces verts » ?",
        a: "15 jours — pilote 25 sites exactement sur cette méthode.",
      },
    ],
    gridItems: [
      link("FAQ espaces verts", "Questions fréquentes", "/espace-vert/faq"),
      link("Petites entreprises", "TPE / indépendants", "/espace-vert/petites-entreprises"),
      link("Guide organiser entretien", "Méthode", "/espace-vert/guide-organiser-entretien"),
      link("Logiciel EV", "Pilier", "/logiciel-espace-vert"),
    ],
    ctaPrimaryLabel: "Essai — sortir d’Excel",
    ctaSecondaryLabel: "Parler migration",
  },
  {
    id: "EV-20",
    key: "faq",
    path: "/espace-vert/faq",
    type: "faq",
    primaryKw: "FAQ logiciel espaces verts",
    seoTitle: "FAQ logiciel espaces verts — réponses terrain",
    seoDesc: "Prix, mobile, météo, preuves, migration Excel, verticalité EV vs propreté : réponses concrètes avant essai. FAQ 100 % espaces verts.",
    crumbLabel: "FAQ espaces verts",
    h1Lead: "FAQ — logiciel espaces verts PROGESTI",
    h1: "les vraies questions des entreprises d’entretien et de paysagisme",
    sub: "Avant de lancer l’essai, les mêmes 6 questions reviennent. Voici des réponses de chef d’exploitation — pas de brochure.",
    claimBefore: "Des réponses",
    claimHighlight: "terrain",
    claimSub: "FAQ logiciel espaces verts",
    productStrip: "FAQ · EV · objections",
    empathyH2: "Vos vraies questions, sans langue de bois",
    empathyBody: "« C’est un soft de nettoyage ? » « Le terrain va pointer ? » « On est trop petits ? » Si on élude, vous le sentez. Cette FAQ est volontairement EV, distincte de la FAQ globale du site.",
    showcaseTitle: "Objections → pages de détail",
    showcaseSub: "Chaque réponse majeure renvoie vers un angle traité en profondeur.",
    showcaseBadgeLeft: { title: "FAQ EV", sub: "Intent réponse" },
    showcaseBadgeRight: "Maillage",
    proofH2: "Comment lire cette FAQ",
    proofQuote: "Une réponse courte ici, une page sœur si vous voulez le détail opérationnel.",
    proofItems: [
      { title: "Produit", text: "Planning, pointage, devis, facture." },
      { title: "Métiers", text: "Entretien, paysagisme, audiences." },
      { title: "Achat", text: "Prix, essai, support." },
    ],
    vsTitle: "FAQ générique SaaS vs FAQ métier EV",
    demo: d(
      "Démo produit · FAQ interactive",
      "Trois objections → trois écrans produit",
      "Parcours : choisir une objection et voir le module PROGESTI qui y répond.",
      "Atelier commercial interne : former un commercial EV à répondre sans blabla.",
      [
        s("Objection pointage", "Montrer l’écran mobile arrivée/départ."),
        s("Objection météo", "Montrer replanification d’une tournée."),
        s("Objection facture", "Montrer réalisé → ligne facturable."),
      ],
      "FAQ → Produit",
      [
        r("« Ils ne pointeront pas »", "→ Pointage simple", "Module"),
        r("« La pluie casse tout »", "→ Replanif", "Module"),
        r("« On oublie des lignes »", "→ Factu réalisé", "Module"),
        r("« On est en collectivité »", "→ Reporting", "Page"),
      ],
      "La FAQ n’est pas une fin : c’est un aiguillage vers la preuve produit.",
      "Passer à l’essai",
      "Voir le pilier logiciel",
      "checklist"
    ),
    bodySections: [
      {
        h2: "Les 6 objections qui bloquent l’essai",
        body: "Verticalité EV, prix, adoption mobile, temps de paramétrage, peur du flicage, comparaison Excel. Chaque réponse renvoie vers une page sœur quand l’intent est plus profond.",
        bullets: [
          "Oui, verticale espaces verts dédiée",
          "Essai 15 j sans CB sur vos sites",
          "Paramétrage progressif (pilote)",
        ],
      },
      {
        h2: "Parcours recommandé après la FAQ",
        body: "Pilier si vision globale · Remplacer Excel si vous voulez la méthode · Preuves si litige · Collectivités/syndics si donneur d’ordre.",
      },
      {
        h2: "Ce que vous ne trouverez pas ici",
        body: "Pas de ROI % inventé, pas d’« IA qui planifie toute seule », pas de mélange propreté/sécu.",
      }
    ],
    faq: [
      {
        q: "PROGESTI espaces verts, c’est la même chose que la propreté ?",
        a: "Non. Vocabulaire, démos et pages sont EV (tournée, fréquence, engins, AV/AP). Les autres métiers ont leurs hubs.",
      },
      {
        q: "On est 6 personnes : trop petit ?",
        a: "Non — page TPE dédiée. L’essai sur 15–20 clients se juge vite.",
      },
      {
        q: "Et si la haute saison empêche de paramétrer ?",
        a: "Paramétrez un pilote hors pic ou 1 h/jour. Ne visez pas 100 sites la première semaine.",
      },
      {
        q: "Les preuves, c’est du flicage ?",
        a: "C’est une protection mutuelle bureau/terrain/client. Le geste mobile reste minimal.",
      },
      {
        q: "Quel tarif pour « gestion multi-sites espaces verts » ?",
        a: "Dès 29,99 € HT/mois — /tarifs. Essai 15 jours sans CB.",
      },
    ],
    gridItems: [
      link("Remplacer Excel", "Migration concrète", "/espace-vert/remplacer-excel"),
      link("Tarifs", "Prix public", "/tarifs"),
      link("Collectivités", "Angle marché public", "/espace-vert/collectivites"),
      link("Guide entretien", "Méthode d’organisation", "/espace-vert/guide-organiser-entretien"),
    ],
    ctaPrimaryLabel: "Essai 15 jours",
    ctaSecondaryLabel: "Voir tarifs",
  },
  {
    id: "EV-21",
    key: "guide-organiser-entretien",
    path: "/espace-vert/guide-organiser-entretien",
    type: "guide",
    primaryKw: "organiser entretien espaces verts",
    seoTitle: "Guide — organiser l’entretien d’espaces verts sans chaos",
    seoDesc: "Méthode en 6 étapes : inventaire sites → fréquences → tournées → pointage → preuves → facture. Pour nouveaux responsables d’exploitation EV.",
    crumbLabel: "Guide organiser entretien",
    h1Lead: "Guide — organiser l’entretien d’espaces verts",
    h1: "une méthode terrain en 6 étapes, sans jargon de consultant",
    sub: "Vous venez de reprendre l’exploitation. Les sites sont « dans la tête de Michel ». Voici l’ordre des opérations pour sortir du folklore sans tout casser.",
    claimBefore: "De la méthode au",
    claimHighlight: "système",
    claimSub: "guide entretien espaces verts",
    productStrip: "Guide · méthode · entretien EV",
    empathyH2: "Structurer n’est pas « mettre un logiciel » : c’est une séquence",
    empathyBody: "Installer un outil sur un inventaire flou produit un bel outil flou. Inventoriez, cadrez les fréquences, puis seulement automatisez la semaine. Ce guide est éducatif — le pilier reste la money page.",
    showcaseTitle: "Méthode en 6 étapes",
    showcaseSub: "Inventaire → fréquences → tournées → pointage → preuves → facture.",
    showcaseBadgeLeft: { title: "Guide EV", sub: "6 étapes" },
    showcaseBadgeRight: "Actionnable",
    proofH2: "Ce guide n’est pas une brochure",
    proofQuote: "Chaque étape a un livrable — et un écran produit associé si vous êtes sur PROGESTI.",
    proofItems: [
      { title: "Livrables", text: "Liste sites, fréquences, règles de priorité." },
      { title: "Rituals", text: "Point lundi 15 min, revue retards." },
      { title: "Outil", text: "Le logiciel porte la méthode au quotidien." },
    ],
    vsTitle: "Conseils génériques vs méthode EV opérationnelle",
    demo: d(
      "Démo produit · guide",
      "Étape 3 → écran tournées : transformer des fréquences en semaine réelle",
      "Le guide devient interactif : vous appliquez l’étape 3 dans PROGESTI sur 10 sites.",
      "Vous avez fini l’inventaire (étapes 1–2). Place à la construction de la tournée type du mardi.",
      [
        s("Charger fréquences", "10 sites entretien actifs."),
        s("Grouper", "Secteur ouest — densité km."),
        s("Règles", "Syndics avant particuliers si arbitrage."),
        s("Verrouiller", "Modèle de semaine réutilisable."),
      ],
      "Guide · Étape 3 Tournées",
      [
        r("Inventaire sites", "Fait", "✓"),
        r("Fréquences", "Fait", "✓"),
        r("Tournées", "En cours démo", "→"),
        r("Pointage / preuves / facture", "Étapes 4–6", "Suite"),
      ],
      "Un guide utile se termine dans l’outil — pas dans un PDF oublié.",
      "Appliquer le guide en essai",
      "Voir entretien EV",
      "timeline"
    ),
    bodySections: [
      {
        h2: "Les 6 étapes (ordre non négociable)",
        body: "1) Inventaire sites/accès. 2) Fréquences par prestation. 3) Découpage tournées/secteurs. 4) Pointage minimal. 5) Preuves sur les sites litige. 6) Facture du réalisé. Sautez une étape → vous reviendrez la faire sous stress.",
        bullets: [
          "Semaine 1–2 : inventaire + fréquences",
          "Semaine 3 : tournée pilote",
          "Semaine 4 : preuves + facture",
        ],
      },
      {
        h2: "Pièges classiques",
        body: "Tout paramétrer en haute saison, exiger 12 photos/site dès J1, laisser Excel vivre en parallèle « au cas où ».",
      },
      {
        h2: "Maillage process",
        body: "Après le guide → planning, pointage, preuves, devis/factu, remplacer Excel.",
      }
    ],
    faq: [
      {
        q: "Combien de temps pour un portefeuille de 40 sites ?",
        a: "Comptez 2–3 semaines en demi-teinte (1–2 h/jour), pas un week-end héroïque.",
      },
      {
        q: "Je dois tout faire avant l’essai ?",
        a: "Non. L’essai accélère les étapes 3–6 sur un pilote.",
      },
      {
        q: "Qui anime la méthode en interne ?",
        a: "Un responsable exploitation + un binôme terrain volontaire. Pas le stagiaire seul.",
      },
      {
        q: "Lien avec contrats annuels ?",
        a: "Quand l’exécution est propre, le renew devient un dossier, pas une angoisse.",
      },
      {
        q: "Et après ?",
        a: "Essai 15 j sur 10 sites — appliquez les 6 étapes pour de vrai.",
      },
    ],
    gridItems: [
      link("Entretien EV", "Page service", "/espace-vert/entretien-espaces-verts"),
      link("Planning équipes", "Étape tournées", "/espace-vert/planning-equipes"),
      link("Preuves de passage", "Étape litiges", "/espace-vert/preuves-passages"),
      link("Contrats annuels", "Cadre contractuel", "/espace-vert/contrats-annuels"),
    ],
    ctaPrimaryLabel: "Essai — appliquer le guide",
    ctaSecondaryLabel: "Démo étape tournées",
  },
  {
    id: "EV-22",
    key: "preuves-passages",
    path: "/espace-vert/preuves-passages",
    type: "probleme",
    primaryKw: "preuves de passage espaces verts",
    seoTitle: "Preuves de passage espaces verts — dossier litige en 1 écran",
    seoDesc: "Mail « vous n’êtes pas venus » : historique, pointages, photos, reports motivés. Protégez renew et équipes. Essai 15 jours.",
    crumbLabel: "Preuves de passage",
    h1Lead: "Preuves de passage espaces verts",
    h1: "finir les litiges « vous n’êtes pas venus »",
    sub: "17h02, mail syndic en majuscules. Vous avez 12 minutes avant que le commercial promette n’importe quoi. Il vous faut un dossier, pas un fil WhatsApp.",
    claimBefore: "Des passages",
    claimHighlight: "prouvés",
    claimSub: "preuves de passage espaces verts",
    productStrip: "Preuves · historique · litiges EV",
    empathyH2: "Le litige se gagne avant le litige : pendant le passage",
    empathyBody: "La preuve ne se crée pas à 17h. Elle se capture à 8h42. Cette page assemble le dossier ; la page pointage capture ; la page photos ajoute l’AV/AP ; la page syndic parle audience.",
    showcaseTitle: "Historique de passages exploitable",
    showcaseSub: "Filtres site / prestation / période — prêt à transmettre.",
    showcaseBadgeLeft: { title: "Historique", sub: "30 jours" },
    showcaseBadgeRight: "Litige clos",
    proofH2: "Une preuve utile est datée, située, attribuée",
    proofQuote: "Pas un roman : un fait. Qui / où / quand.",
    proofItems: [
      { title: "Pointage", text: "Horodatage d’intervention." },
      { title: "Historique", text: "Série de passages sur la période contestée." },
      { title: "Contexte", text: "Reports météo documentés si besoin." },
    ],
    vsTitle: "Parole contre parole vs preuve structurée",
    demo: d(
      "Démo produit · preuves",
      "Constituer un dossier de réponse en 90 secondes",
      "Réponse factuelle à une réclamation — sans fouiller WhatsApp.",
      "Cas litige syndic : plainte « pas de tonte depuis 3 semaines » — réalité : 2 passages + 1 report orage.",
      [
        s("Période", "Derniers 21 jours sur le site."),
        s("Filtre", "Prestation tonte."),
        s("Lecture", "2 pointages + 1 statut reporté météo."),
        s("Réponse", "Envoyer le fait au syndic avec dates."),
      ],
      "Preuve · Litige Tilleuls",
      [
        r("Tonte 09/05", "Pointé", "Fait"),
        r("Tonte 02/05", "Pointé", "Fait"),
        r("Tonte 28/04", "Orage — reporté", "Documenté"),
        r("Réclamation", "Clos", "OK"),
      ],
      "Le but n’est pas de « gagner contre le client » : c’est d’arrêter l’hémorragie d’énergie.",
      "Essai — preuves sur mes sites",
      "Voir photos AV/AP",
      "checklist"
    ),
    bodySections: [
      {
        h2: "Cas — Réponse en un écran, Résidence des Tilleuls",
        body: "Derniers passages, motif S17 pluie, photo haies S18, prochaine date. Pièce jointe envoyée. Ton factuel. Le conseil syndical reçoit des faits.",
        bullets: [
          "Horodatage + site + équipe",
          "Motifs de report opposables",
          "Visuel si configuré",
        ],
      },
      {
        h2: "Objection « flicage »",
        body: "Sans preuve, c’est l’équipe qui trinque sous accusation. La preuve protège aussi le terrain.",
      },
      {
        h2: "Livrable",
        body: "PDF/historique période + exceptions + prochain créneau.",
      }
    ],
    faq: [
      {
        q: "Différence avec pointage ?",
        a: "Pointage = capture. Preuves = assemblage et usage litige/renew.",
      },
      {
        q: "Sans photo, la preuve suffit ?",
        a: "Souvent oui (horodatage). La photo tranche les débats de rendu.",
      },
      {
        q: "Accès refusé ?",
        a: "Statut + photo du blocage = meilleure défense.",
      },
      {
        q: "Durée de conservation ?",
        a: "Alignez-vous sur vos besoins renew / litige — à cadrer en essai.",
      },
      {
        q: "Comment démarrer un essai orienté gestion multi-sites espaces verts ?",
        a: "15 jours — activez preuves sur 5 sites « chauds ».",
      },
    ],
    gridItems: [
      link("Pointage terrain", "Capturer la preuve", "/espace-vert/pointage-terrain"),
      link("Syndics & copro", "Audience réclamations", "/espace-vert/syndics-coproprietes"),
      link("Photos avant/après", "Preuve visuelle", "/espace-vert/photos-avant-apres"),
      link("Collectivités", "Reporting public", "/espace-vert/collectivites"),
    ],
    ctaPrimaryLabel: "Essai — finir les litiges",
    ctaSecondaryLabel: "Démo dossier preuve",
  },
  {
    id: "EV-23",
    key: "petites-entreprises",
    path: "/espace-vert/petites-entreprises",
    type: "audience",
    primaryKw: "logiciel espaces verts TPE",
    seoTitle: "Logiciel paysagiste TPE & indépendants — simple et abordable",
    seoDesc: "TPE EV < 10 personnes : finis les soirées Excel, oublis client, facture du dimanche. Simplicité + essai 15 j. Dès 29,99 € HT.",
    crumbLabel: "TPE & indépendants",
    h1Lead: "Logiciel espaces verts pour TPE & indépendants",
    h1: "simple à prendre en main — sans équipe admin dédiée",
    sub: "Malik, indépendant + 2 salariés, 18 clients. Il connaît tout par cœur — jusqu’à la haie oubliée et la soirée facture de 3 heures.",
    claimBefore: "Un outil EV",
    claimHighlight: "à taille humaine",
    claimSub: "logiciel espaces verts TPE",
    productStrip: "TPE · simplicité · prix public",
    empathyH2: "Trop petit pour un logiciel ? Trop grand pour le cahier",
    empathyBody: "Le pilier parle PME 15–40. Ici l’angle est radicalement TPE : peu d’écrans, rentabilité rapide, zéro usine à gaz. Le prix ne doit pas faire plus peur que le dimanche Excel.",
    showcaseTitle: "Parcours TPE en essai",
    showcaseSub: "Créer 8 sites, planifier la semaine, pointer, facturer.",
    showcaseBadgeLeft: { title: "TPE", sub: "8 sites pilotes" },
    showcaseBadgeRight: "1h setup",
    proofH2: "Pourquoi les TPE abandonnent les logiciels",
    proofQuote: "Trop de boutons, trop de paramétrage, trop cher. On a calibré l’inverse.",
    proofItems: [
      { title: "Prix lisible", text: "Dès 29,99 € HT/mois — voir tarifs." },
      { title: "Essai sans CB", text: "15 jours pour juger sur vos sites." },
      { title: "Support humain", text: "Pas un chatbot opaque." },
    ],
    vsTitle: "Usine logicielle vs outil TPE EV",
    demo: d(
      "Démo produit · TPE",
      "Setup express : de zéro à tournée de la semaine",
      "Parcours dimanche soir : paramétrer juste assez pour démarrer lundi.",
      "Indépendant + 2 salariés. Objectif : remplacer le carnet papier ce week-end.",
      [
        s("Créer 8 sites", "Clients récurrents seulement."),
        s("Fréquences", "Tonte / haies selon vos habitudes."),
        s("Semaine", "Affecter lundi–vendredi."),
        s("Pointage", "Tester 2 jours terrain."),
      ],
      "Setup TPE · Dimanche soir",
      [
        r("8 fiches sites", "Créées", "OK"),
        r("Semaine type", "Remplie", "OK"),
        r("App mobile", "Installée équipe", "OK"),
        r("Facture", "Vague suivante", "Plus tard"),
      ],
      "Si le setup demande une formation de 3 jours, ce n’est pas un outil de TPE.",
      "Essai TPE 15 jours",
      "Voir tarifs",
      "list"
    ),
    bodySections: [
      {
        h2: "Cas — 18 clients, une haie oubliée, un dimanche sauvé",
        body: "Malik voit la semaine sur mobile, pointe, photo haie, facture le forfait + 1 ponctuel. Temps admin : une demi-heure, pas trois.",
        bullets: [
          "Paramétrage express",
          "Mobile first",
          "Facture simple",
        ],
      },
      {
        h2: "Objection prix",
        body: "Une haie oubliée + une soirée stress coûtent plus cher qu’un mois d’abonnement. L’essai sans CB tranche.",
      },
      {
        h2: "Quand passer au mode PME",
        body: "Au-delà de ~12 personnes / 40 sites, ouvrez planning engins et multi-sites avancé.",
      }
    ],
    faq: [
      {
        q: "Je suis seul : ça sert ?",
        a: "Oui pour ne plus oublier et facturer proprement — surtout si vous grossissez.",
      },
      {
        q: "Formation longue ?",
        a: "Non. Objectif : être opérationnel en une après-midi sur 10 clients.",
      },
      {
        q: "Différence avec le pilier ?",
        a: "Même produit, angle simplicité/prix/TPE. Le pilier = vision PME complète.",
      },
      {
        q: "Faut-il encore WhatsApp avec « gestion multi-sites espaces verts » ?",
        a: "Gardez-le pour vos clients si besoin ; plus comme planning d’équipe.",
      },
      {
        q: "Quel tarif pour « gestion multi-sites espaces verts » ?",
        a: "Dès 29,99 € HT/mois — essai 15 j.",
      },
    ],
    gridItems: [
      link("Tarifs", "Prix public", "/tarifs"),
      link("Remplacer Excel", "Migration douce", "/espace-vert/remplacer-excel"),
      link("Devis & facturation", "Gagner des soirées", "/espace-vert/devis-facturation"),
      link("Logiciel EV", "Vue d’ensemble", "/logiciel-espace-vert"),
    ],
    ctaPrimaryLabel: "Essai TPE — 15 jours",
    ctaSecondaryLabel: "Voir les tarifs",
  },
  {
    id: "EV-24",
    key: "grands-parcs",
    path: "/espace-vert/grands-parcs",
    type: "audience",
    primaryKw: "gestion grands parcs espaces verts",
    seoTitle: "Grands parcs & sites étendus — planning par zones",
    seoDesc: "1 adresse, N zones (parc 28 ha, campus, domaine) : priorisez entrée, playground, massifs fond. ≠ multi-sites. Essai 15 j.",
    crumbLabel: "Grands parcs",
    h1Lead: "Grands parcs & sites étendus",
    h1: "zones, équipes et suivi — quand un seul « site » est un territoire",
    sub: "Parc des Moulins, 28 ha, 12 zones, 2 équipes. L’entrée Instagram est impeccable ; le fond de parc est une jungle. Sans zones, pas de pilotage.",
    claimBefore: "Un territoire",
    claimHighlight: "découpé et suivi",
    claimSub: "grands parcs espaces verts",
    productStrip: "Grands sites · zones · équipes",
    empathyH2: "Un grand site n’est pas « un gros client » : c’est une carte",
    empathyBody: "Multi-sites = N adresses. Ici 1 adresse, N zones avec priorités différentes. Les équipes se perdent, les priorités aussi, si tout est coché « parc OK ».",
    showcaseTitle: "Site étendu découpé en zones",
    showcaseSub: "Priorités, fréquences et équipes par zone.",
    showcaseBadgeLeft: { title: "Parc 12 ha", sub: "7 zones" },
    showcaseBadgeRight: "Zone 3 due",
    proofH2: "Découper pour maîtriser",
    proofQuote: "Un grand site sans zones est un angle mort permanent.",
    proofItems: [
      { title: "Zones", text: "Entrée, pelouses, boisements, parkings, aires de jeux…" },
      { title: "Fréquences différenciées", text: "L’entrée n’a pas la même exigence que l’arrière." },
      { title: "Équipes", text: "Spécialiser ou faire tourner selon charge." },
    ],
    vsTitle: "Un site fourre-tout vs zones pilotées",
    demo: d(
      "Démo produit · grands parcs",
      "Découper un parc de 12 ha en 7 zones actionnables",
      "Cas régie / prestataire : rendre le « parc central » gérable au planning hebdo.",
      "Parc urbain 12 ha. Plainte habitants zone aire de jeux. Aujourd’hui tout est un seul site « Parc Central » dans Excel.",
      [
        s("Créer zones", "Entrée / pelouse centrale / aire jeux / boisement / parking / berges / événements."),
        s("Fréquences", "Aire jeux + entrée plus élevées."),
        s("Planning", "2 équipes sur zones prioritaires le mardi."),
        s("Preuve", "Pointage par zone — fini le « on a fait le parc »."),
      ],
      "Parc Central · Zones",
      [
        r("Zone entrée", "Hebdo · priorité image", "Due"),
        r("Aire de jeux", "Bihebdo · sécurité perçue", "Due"),
        r("Boisement", "Mensuel", "OK"),
        r("Parking PL", "Mensuel désherbage", "Planifié"),
      ],
      "Dès qu’on parle zones, on peut enfin arbitrer et prouver.",
      "Essai — mon grand site",
      "Voir collectivités",
      "board"
    ),
    bodySections: [
      {
        h2: "Cas — 12 zones, prioriser entrée + playground",
        body: "Matin : zones A/B (entrée, jeux). Après-midi : massifs fond si charge OK. Orage : on protège les zones usagers, on reporte le fond.",
        bullets: [
          "Zones nommément planifiées",
          "Priorités usagers vs fond",
          "2 équipes sans collision",
        ],
      },
      {
        h2: "≠ multi-sites",
        body: "Ne cannibalisez pas : intents et démos différents.",
      },
      {
        h2: "Livrable direction de parc",
        body: "État des zones de la semaine + photos des zones usagers.",
      }
    ],
    faq: [
      {
        q: "Combien de zones max ?",
        a: "Autant que nécessaire pour piloter — 8 à 20 est courant sur 20–40 ha.",
      },
      {
        q: "Engins sur grand site ?",
        a: "Affectez par zone pour éviter que deux équipes se croisent sur la même allée.",
      },
      {
        q: "Public / billetterie / événements ?",
        a: "Bloquez des fenêtres « événement » sur les zones concernées.",
      },
      {
        q: "Lien collectivités ?",
        a: "Souvent oui si parc public — reporting DST en plus.",
      },
      {
        q: "Y a-t-il un essai sans engagement pour gestion multi-sites espaces verts ?",
        a: "15 jours — découpez votre parc en zones réelles.",
      },
    ],
    gridItems: [
      link("Collectivités", "Souvent le cadre des grands parcs", "/espace-vert/collectivites"),
      link("Multi-sites", "Beaucoup d’adresses", "/espace-vert/multi-sites"),
      link("Cimetières & voiries", "Autres sites publics", "/espace-vert/cimetieres-voirie"),
      link("Planning équipes", "Affecter par zone", "/espace-vert/planning-equipes"),
    ],
    ctaPrimaryLabel: "Essai — sites étendus",
    ctaSecondaryLabel: "Démo découpage zones",
  },
];
