/* eslint-disable */
import { link, type EvPageSpec } from "./build";

const d = (
  eyebrow: string,
  h2: string,
  lead: string,
  scenario: string,
  steps: EvPageSpec["demo"]["steps"],
  uiLabel: string,
  uiRows: EvPageSpec["demo"]["uiRows"],
  takeaway: string,
  primaryCtaLabel?: string,
  secondaryCtaLabel?: string,
  variant?: EvPageSpec["demo"]["variant"],
): EvPageSpec["demo"] => ({
  eyebrow, h2, lead, scenario, steps, uiLabel, uiRows, takeaway, primaryCtaLabel, secondaryCtaLabel, variant,
});
const s = (label: string, detail: string) => ({ label, detail });
const r = (left: string, right: string, status?: string) => ({ left, right, status });

/** EV-25 → EV-32 (dont 7 nouvelles niches) */
export const evSpecsPart4: EvPageSpec[] = [
  {
    id: "EV-25",
    key: "contrats-annuels",
    path: "/espace-vert/contrats-annuels",
    type: "process",
    primaryKw: "contrat annuel entretien espaces verts",
    seoTitle: "Contrats annuels entretien EV — suivi d’exécution & renew",
    seoDesc: "Novembre, renew 28 k€ : bilan d’exécution, exceptions, dossier conseil. Cycle de vie contrat ≠ simple facturation. Essai 15 j.",
    crumbLabel: "Contrats annuels",
    h1Lead: "Contrats annuels d’entretien espaces verts",
    h1: "tenir la promesse toute l’année — pas seulement à la signature",
    sub: "Le PDF du contrat ne dit pas si vous l’avez honoré. Six semaines avant échéance, le commercial a besoin d’un bilan — pas d’une impression.",
    claimBefore: "Du contrat signé à l’",
    claimHighlight: "exécution prouvée",
    claimSub: "contrat annuel entretien espaces verts",
    productStrip: "Contrats · exécution · renew",
    empathyH2: "Le renew se joue sur l’exécution de l’année, pas sur le déjeuner",
    empathyBody: "Exceptions météo, accès refusés, ponctuels offerts : sans historique, vous négociez à découvert. Cette page = cycle de vie. L’entretien opère ; la factu facture ; ici on prépare le renew.",
    showcaseTitle: "Exécution de contrat visible",
    showcaseSub: "Fréquences tenues, exceptions documentées, factures alignées.",
    showcaseBadgeLeft: { title: "Contrat 2026", sub: "Exécution 94%" },
    showcaseBadgeRight: "Renew prêt",
    proofH2: "Ce qu’un bon suivi de contrat change",
    proofQuote: "Moins de stress en fin d’année, plus d’arguments factuels au renew.",
    proofItems: [
      { title: "Exécution", text: "Le planning porte les obligations du contrat." },
      { title: "Exceptions", text: "Reports météo / accès : tracés, pas oubliés." },
      { title: "Renew", text: "Historique propre à sortir avant la négociation." },
    ],
    vsTitle: "Contrat PDF vs contrat vivant dans le planning",
    demo: d(
      "Démo produit · contrats annuels",
      "Préparer le dossier de renouvellement 6 semaines avant échéance",
      "Revue d’exécution annuelle exportable à partir du réel.",
      "Contrat syndic 28 000 €/an, échéance 31/12. Début novembre : préparer le bilan d’exécution pour le conseil syndical.",
      [
        s("Période", "01/01 → 31/10 sur le site / contrat."),
        s("Taux", "% de fréquences tenues par prestation."),
        s("Exceptions", "Liste reports + motifs."),
        s("Pitch renew", "Faits + proposition fréquences année suivante."),
      ],
      "Renew · Contrat Les Tilleuls",
      [
        r("Tonte", "96% fréquences tenues", "Solide"),
        r("Haies", "4/4 passages", "OK"),
        r("Désherbage", "1 retard · rattrapé", "Documenté"),
        r("Réclamations", "2 · toutes clos avec preuve", "Maîtrisé"),
      ],
      "Le renew n’est plus un exercice de séduction : c’est un bilan d’exécution.",
      "Essai — suivre mes contrats",
      "Voir entretien EV",
      "checklist"
    ),
    bodySections: [
      {
        h2: "Cas — Contrat 28 k€, dossier renew J-42",
        body: "Taux de tenue des fréquences, liste des reports motivés, photos clés, ponctuels facturés vs offerts. Pitch : transparence + ajustement de cadence si besoin.",
        bullets: [
          "Bilan quantifié",
          "Exceptions assumées",
          "Proposition d’avenant argumentée",
        ],
      },
      {
        h2: "Journée type commercial + exploitation",
        body: "Export bilan → revue à deux → envoi syndic → RDV conseil.",
      },
      {
        h2: "Objection « le PDF suffit »",
        body: "Le PDF décrit la promesse. Le renew juge la tenue.",
      }
    ],
    faq: [
      {
        q: "Différence avec devis/facturation ?",
        a: "Factu = pièces. Renew = récit d’exécution + négociation.",
      },
      {
        q: "Et si l’année a été chaotique ?",
        a: "Mieux vaut un bilan honnête avec motifs qu’un silence — vous proposez un plan S1.",
      },
      {
        q: "Gère-t-on le multi-contrats pour « contrat annuel entretien espaces verts » ?",
        a: "Portefeuille renew filtré par échéance.",
      },
      {
        q: "Lien preuves ?",
        a: "Le dossier renew s’appuie sur les preuves de la saison.",
      },
      {
        q: "Puis-je tester PROGESTI sur mon cas « contrat annuel entretien espaces verts » ?",
        a: "15 jours — construisez le bilan d’un contrat qui renew bientôt.",
      },
    ],
    gridItems: [
      link("Entretien EV", "Opérations récurrentes", "/espace-vert/entretien-espaces-verts"),
      link("Devis & facturation", "Forfaits & ponctuels", "/espace-vert/devis-facturation"),
      link("Preuves de passage", "Argument renew", "/espace-vert/preuves-passages"),
      link("Saison automne-hiver", "Préparer les renew", "/espace-vert/saison-automne-hiver"),
    ],
    ctaPrimaryLabel: "Essai — exécution de contrats",
    ctaSecondaryLabel: "Démo dossier renew",
  },
  {
    id: "EV-26",
    key: "engins-materiel",
    path: "/espace-vert/engins-materiel",
    type: "process",
    primaryKw: "gestion engins espaces verts",
    seoTitle: "Planning engins espaces verts — conflits autoportée & mini-pelle",
    seoDesc: "Anti double-booking engins EV : autoportée, nacelle, mini-pelle. Détectez le conflit avant le chantier bloqué. Pas une GMAO. Essai 15 j.",
    crumbLabel: "Engins & matériel",
    h1Lead: "Engins & matériel espaces verts",
    h1: "ne plus découvrir à 7h que l’autoportée est déjà partie",
    sub: "Mardi 10h : la mini-pelle est réservée sur deux chantiers. Personne au téléphone n’avait la vue complète. Un chantier plantation attendra — trop tard.",
    claimBefore: "Des ressources",
    claimHighlight: "arbitrées",
    claimSub: "gestion engins espaces verts",
    productStrip: "Engins · matériel · planning EV",
    empathyH2: "L’engin rare dicte le planning — pas l’inverse",
    empathyBody: "Ce n’est pas une GMAO industrielle avec stocks de pièces. C’est un garde-fou dans le planning EV : qui a la machine, quand, et quel chantier saute si panne.",
    showcaseTitle: "Planning avec contrainte engins",
    showcaseSub: "Équipes + ressources critiques sur la même semaine.",
    showcaseBadgeLeft: { title: "Nacelle", sub: "Jeu 8h–12h" },
    showcaseBadgeRight: "Conflit évité",
    proofH2: "Le matériel est un acteur du planning",
    proofQuote: "Autant que les salariés — surtout quand il est loué à la demi-journée.",
    proofItems: [
      { title: "Conflits visibles", text: "Deux besoins sur la même ressource = alerte avant le jour J." },
      { title: "Location", text: "Alignez créneau de location et chantier." },
      { title: "Pannes", text: "Basculer les sites compatibles poussée / autre engin." },
    ],
    vsTitle: "Mémoire du magasinier vs contrainte engins dans le planning",
    demo: d(
      "Démo produit · engins",
      "Détecter un double booking nacelle avant la location",
      "Cas jeudi : élagage voie publique + taille grands sujets en copro — une seule nacelle réservée.",
      "Le commercial a confirmé l’élagage. L’exploitation a glissé une taille « rapide » le même créneau. La location est déjà commandée.",
      [
        s("Ressource", "Nacelle louée — créneau jeu 8h–12h."),
        s("Conflit", "2 interventions taguées nacelle sur le créneau."),
        s("Arbitrage", "Priorité voie publique ; reporter copro au vendredi + adapter location."),
        s("Confirm", "Équipes et fournisseur nacelle alignés."),
      ],
      "Ressources · Jeudi",
      [
        r("Nacelle location", "8h–12h", "Réservée"),
        r("Élagage voie publique", "Priorité sécurité", "Garde"),
        r("Taille copro grands sujets", "Report vendredi", "Déplacé"),
        r("Autoportée #2", "Garage — panne", "HS"),
      ],
      "Une ressource rare gérée à l’oral est une ressource déjà perdue.",
      "Essai — contraintes engins",
      "Voir planning équipes",
      "board"
    ),
    bodySections: [
      {
        h2: "Cas — Conflit mini-pelle, plantation vs reprise",
        body: "Alerte conflit. Arbitrage : plantation Clarines garde le créneau (jalon livraison plants), reprise ZA Nord glisse de 24 h. Notification des deux chefs.",
        bullets: [
          "Ressources engins sur les interventions",
          "Alerte conflit",
          "Panne = indispo + sites impactés",
        ],
      },
      {
        h2: "≠ absences équipes",
        body: "Humains vs machines — pages sœurs.",
      },
      {
        h2: "Objection « on se téléphone »",
        body: "Le téléphone ne scale pas à 3 dépôts et 12 machines.",
      }
    ],
    faq: [
      {
        q: "Maintenance préventive ?",
        a: "Bloquez des créneaux atelier. Pour une GMAO profonde, gardez votre outil dédié si besoin.",
      },
      {
        q: "Location engins ?",
        a: "Créez la ressource « loc » sur la période louée.",
      },
      {
        q: "Permis / habilitations ?",
        a: "Couplez avec compétences personnes sur le planning équipes.",
      },
      {
        q: "Télémétrie IoT ?",
        a: "Hors scope — focus anti-conflit planning.",
      },
      {
        q: "L’essai couvre-t-il vraiment « contrat annuel entretien espaces verts » ?",
        a: "15 jours — déclarez vos 5 engins critiques.",
      },
    ],
    gridItems: [
      link("Élagage", "Souvent lié à nacelle", "/espace-vert/elagage"),
      link("Tonte", "Autoportée / poussée", "/espace-vert/tonte-pelouse"),
      link("Planning équipes", "Affectation globale", "/espace-vert/planning-equipes"),
      link("Paysagisme", "Mini-pelle & chantiers", "/espace-vert/paysagisme"),
    ],
    ctaPrimaryLabel: "Essai — planning + engins",
    ctaSecondaryLabel: "Démo conflit nacelle",
  },
  {
    id: "EV-27",
    key: "photos-avant-apres",
    path: "/espace-vert/photos-avant-apres",
    type: "process",
    primaryKw: "photos avant après espaces verts",
    seoTitle: "Photos avant/après espaces verts — preuves visuelles chantier",
    seoDesc: "AV/AP haies, massifs, élagage : photos rattachées à l’intervention, plus dans WhatsApp. Complète les preuves horodatées. Essai 15 j.",
    crumbLabel: "Photos avant/après",
    h1Lead: "Photos avant/après espaces verts",
    h1: "des preuves visuelles rattachées au bon chantier — pas perdues dans la galerie du téléphone",
    sub: "Le rendu se discute. L’horodatage dit « on est venus » ; la photo dit « voilà le résultat ». Si l’AP est dans la galerie du stagiaire, elle n’existe pas.",
    claimBefore: "Des photos",
    claimHighlight: "exploitables",
    claimSub: "photos avant après espaces verts",
    productStrip: "Photos AV/AP · preuves · chantiers",
    empathyH2: "La photo orpheline ne sauve aucun conseil syndical",
    empathyBody: "Cette page ≠ preuves horodatage pures. Ici le geste visuel AV/AP, surtout haies et création. Le terrain doit pouvoir shooter sans friction.",
    showcaseTitle: "AV/AP rattachés à l’intervention",
    showcaseSub: "Avant le geste, après le geste — sur la fiche chantier/site.",
    showcaseBadgeLeft: { title: "AV 08:05", sub: "Élagage peuplier" },
    showcaseBadgeRight: "AP 11:40",
    proofH2: "Quand la photo change la donne",
    proofQuote: "Litige voisinage, valorisation devis, reporting client image.",
    proofItems: [
      { title: "Élagage / création", text: "AV/AP quasi systématiques." },
      { title: "Clients sensibles", text: "Syndics / sièges avec exigence image." },
      { title: "Commercial", text: "Montrer le savoir-faire sur chantiers similaires." },
    ],
    vsTitle: "Galerie téléphone vs preuves visuelles structurées",
    demo: d(
      "Démo produit · photos AV/AP",
      "Checklist photo sur un chantier d’élagage",
      "Parcours mobile : l’ouvrier ne peut pas clôturer sans AV + AP.",
      "Chantier peuplier en limite de propriété. Risque voisinage élevé. Consignes : 2 photos AV (vue rue + vue jardin), 2 photos AP, pointage.",
      [
        s("Arrivée", "Pointage + capture AV obligatoires."),
        s("Exécution", "Taille selon devis."),
        s("AP", "Mêmes angles que l’AV."),
        s("Clôture", "Intervention « faite » seulement si checklist photo OK."),
      ],
      "Chantier · Checklist photo",
      [
        r("AV vue rue", "08:05", "OK"),
        r("AV vue jardin", "08:06", "OK"),
        r("AP vue rue", "11:38", "OK"),
        r("AP vue jardin", "11:40", "OK"),
      ],
      "Une photo non rattachée n’est pas une preuve : c’est une charge mentale.",
      "Essai — preuves photos",
      "Voir élagage",
      "split"
    ),
    bodySections: [
      {
        h2: "Cas — Taille haies syndic, AV 07:55 / AP 11:20",
        body: "Photos rattachées à l’intervention. Le syndic conteste la hauteur : l’AP tranche. Temps ajouté : 40 secondes.",
        bullets: [
          "Rattachement obligatoire à l’intervention",
          "Exigence configurable par type",
          "Fin des chasses dans WA",
        ],
      },
      {
        h2: "Objection « trop long »",
        body: "40 secondes vs 40 minutes de litige. Exigez AV/AP où ça compte (haies, massifs), pas sur chaque tonte.",
      },
      {
        h2: "Livrable",
        body: "Galerie par site / période pour renew ou réception chantier.",
      }
    ],
    faq: [
      {
        q: "Stockage / poids des médias ?",
        a: "Compression raisonnable ; détail pratique en essai.",
      },
      {
        q: "Obligatoire pour toutes interventions ?",
        a: "Non — paramétrez par type (haies oui, tonte optionnel).",
      },
      {
        q: "Différence avec preuves-passages ?",
        a: "Preuves = dossier litige global. Photos = brique visuelle.",
      },
      {
        q: "Droit à l’image riverains ?",
        a: "Évitez les personnes ; focus végétation / ouvrage.",
      },
      {
        q: "Comment démarrer un essai orienté contrat annuel entretien espaces verts ?",
        a: "15 jours — activez AV/AP sur haies uniquement.",
      },
    ],
    gridItems: [
      link("Élagage", "Cas d’usage n°1", "/espace-vert/elagage"),
      link("Preuves de passage", "Preuve horodatée", "/espace-vert/preuves-passages"),
      link("Paysagisme", "Créations à valoriser", "/espace-vert/paysagisme"),
      link("Syndics", "Clients sensibles image", "/espace-vert/syndics-coproprietes"),
    ],
    ctaPrimaryLabel: "Essai — AV/AP structurés",
    ctaSecondaryLabel: "Démo checklist photo",
  },
  {
    id: "EV-28",
    key: "replanification-meteo",
    path: "/espace-vert/replanification-meteo",
    type: "probleme",
    primaryKw: "replanifier tournée espaces verts pluie",
    seoTitle: "Replanification météo espaces verts — playbook orage",
    seoDesc: "Pluie, orage, sol détrempé : marquer reports, basculer haies prioritaires, sync mobile, garder fréquences. Playbook dédié. Essai 15 j.",
    crumbLabel: "Replanification météo",
    h1Lead: "Replanification météo espaces verts",
    h1: "basculer une tournée mouillée sans perdre une journée — ni un client",
    sub: "Le pilier montre la vision globale. Ici uniquement le playbook pluie : ce que le planificateur fait entre 7h10 et 7h40 quand le ciel a décidé.",
    claimBefore: "Une tournée",
    claimHighlight: "replanifiée proprement",
    claimSub: "replanifier tournée pluie espaces verts",
    productStrip: "Météo · report · priorités",
    empathyH2: "Improviser sous la pluie coûte des clients par beau temps",
    empathyBody: "Reports en chaîne, clients non prévenus, fréquences perdues : la météo n’est pas un aléa rare en EV. C’est un mode de travail. Sans playbook, chaque orage réinvente l’organisation.",
    showcaseTitle: "Bascule météo en règles",
    showcaseSub: "Reports tagués, priorités gardées, terrain informé.",
    showcaseBadgeLeft: { title: "Orage 6h", sub: "9 reports" },
    showcaseBadgeRight: "Repriorisé",
    proofH2: "La météo exige un playbook",
    proofQuote: "Qui on reporte, qui on garde, qui on prévient — avant 7h30.",
    proofItems: [
      { title: "Tag report", text: "La fréquence n’est pas effacée : elle est décalée." },
      { title: "Priorités", text: "Syndics / écoles / clients image d’abord." },
      { title: "Alternative", text: "Basculer sur haies / intérieurs d’entretien possibles." },
    ],
    vsTitle: "Chaos WhatsApp matinal vs playbook météo",
    demo: d(
      "Démo produit · météo",
      "Playbook orage : 9 pelouses impraticables avant 7h20",
      "Le gérant applique 3 règles : tag report, garder 2 priorités couvertes, basculer le reste sur haies.",
      "Même scénario que le pilier, zoomé sur le process météo — page problème dédiée pour l’intent « pluie / replanifier ».",
      [
        s("Règle 1", "Tag « reporté météo » sur tonte impraticable."),
        s("Règle 2", "Maintenir 2 clients non reportables (école + syndic hot)."),
        s("Règle 3", "Réaffecter équipes sur tailles de haies / désherbage abrité."),
        s("Comms", "Terrain à jour ; notes pour prévenir les reports clients si besoin."),
      ],
      "Playbook · Orage matin",
      [
        r("9 tontes", "Reportées · fréquence conservée", "Tag"),
        r("École — pelouse", "Maintenue si fenêtre", "Priorité"),
        r("Haies secteur ouest", "Avancées", "Bascule"),
        r("Terrain", "Planning mobile rafraîchi", "Sync"),
      ],
      "La pluie reste chiante. Le chaos, lui, est optionnel.",
      "Essai — playbook météo",
      "Voir saison printemps",
      "board"
    ),
    bodySections: [
      {
        h2: "Playbook 30 minutes — orage nocturne",
        body: "1) Marquer impraticables. 2) Conserver fréquences. 3) Basculer travail faisable (haies, plantations reportables non). 4) Notifier. 5) Sync mobile. 6) Buffer lendemain.",
        bullets: [
          "Statut report météo standardisé",
          "Bascules d’équipe guidées",
          "Trace client",
        ],
      },
      {
        h2: "≠ tonte service ≠ pilier",
        body: "Intent pluie/replanif pur. Les autres pages citent la météo ; celle-ci l’opère.",
      },
      {
        h2: "Objection « météo auto ? »",
        body: "Pas de magie IA. Aide à exécuter le playbook humain plus vite.",
      }
    ],
    faq: [
      {
        q: "Y a-t-il une intégration météo automatique ?",
        a: "Le cœur est le playbook opérationnel. Les alertes automatiques ne remplacent pas le jugement terrain (sol détrempé local).",
      },
      {
        q: "Clients toujours notifiés ?",
        a: "Selon vos règles : SMS/mail sur reports des sites sensibles (syndics, marchés).",
      },
      {
        q: "Fréquences perdues après 3 reports ?",
        a: "Non — backlog visible, rattrapage planifiable.",
      },
      {
        q: "Lien saison printemps ?",
        a: "Au printemps, élargissez le buffer météo du playbook.",
      },
      {
        q: "Y a-t-il un essai sans engagement pour contrat annuel entretien espaces verts ?",
        a: "15 jours — rejouez votre dernier lundi pluvieux.",
      },
    ],
    gridItems: [
      link("Planning équipes", "Support de la bascule", "/espace-vert/planning-equipes"),
      link("Tonte pelouse", "Prestation la plus touchée", "/espace-vert/tonte-pelouse"),
      link("Saison printemps", "Pic + orages", "/espace-vert/saison-printemps"),
      link("Logiciel EV", "Pilier", "/logiciel-espace-vert"),
    ],
    ctaPrimaryLabel: "Essai — replanif météo",
    ctaSecondaryLabel: "Démo playbook orage",
  },
  {
    id: "EV-29",
    key: "amenageurs-promoteurs",
    path: "/espace-vert/amenageurs-promoteurs",
    type: "audience",
    primaryKw: "espaces verts aménageurs promoteurs",
    seoTitle: "Espaces verts aménageurs & promoteurs — jalons & réception",
    seoDesc: "Sous-traitance EV lotissements / promotions : jalons engazonnement, PV réception, preuves promoteur. ≠ entretien sites privés. Essai 15 j.",
    crumbLabel: "Aménageurs & promoteurs",
    h1Lead: "Espaces verts pour aménageurs & promoteurs",
    h1: "livrer des lots paysagers dans les délais — avec preuves de réception",
    sub: "Livraison de lotissement : 3 jalons, un promoteur pressé, un PV à signer. Ce n’est pas de l’entretien de siège social.",
    claimBefore: "Des livraisons",
    claimHighlight: "documentées",
    claimSub: "EV aménageurs & promoteurs",
    productStrip: "Promo · lots · réceptions",
    empathyH2: "Le promoteur achète des jalons tenus, pas une « belle équipe »",
    empathyBody: "Retards plants, pluie, réception partielle : sans timeline partagée, vous découvrez l’écart au PV. Page distincte des sites privés B2B récurrents.",
    showcaseTitle: "Chantier promo suivi jusqu’à réception",
    showcaseSub: "Jalons, équipes, preuves, reprises.",
    showcaseBadgeLeft: { title: "Lot C", sub: "Réception J" },
    showcaseBadgeRight: "PV prêt",
    proofH2: "Ce que la promo exige vraiment",
    proofQuote: "Dates tenues + preuves de finition + réactivité sur réserves.",
    proofItems: [
      { title: "Jalons", text: "Préparation, plantations, finitions, réception." },
      { title: "Preuves", text: "Photos et pointages pour lever les réserves." },
      { title: "Reprises", text: "Planifier les levées de réserve sans perdre le fil." },
    ],
    vsTitle: "Chantier suivi à l’oral vs livraison promo documentée",
    demo: d(
      "Démo produit · aménageurs",
      "Préparer une réception de lot paysager demain 10h",
      "Checklist : finitions faites, photos AP, pointages, liste réserves éventuelles.",
      "Lotissement phase 2 — espaces communs. Réception promoteur demain. Il reste un massif à reprendre et les photos AP du parking végétalisé.",
      [
        s("Jalons", "Voir ce qui est « fait » vs « en réserve »."),
        s("Reprise flash", "Affecter 2 ouvriers ce jour 14h–17h sur massif."),
        s("Photos", "AP parking + entrée de lot."),
        s("Dossier", "Historique prêt pour le conducteur de travaux."),
      ],
      "Réception · Lot C",
      [
        r("Plantations communes", "Faites · pointées", "OK"),
        r("Massif entrée", "Reprise 14h–17h", "En cours"),
        r("Photos AP parking", "À capturer fin de jour", "Checklist"),
        r("Réserves", "1 ouverte → clôture ce soir", "Watch"),
      ],
      "En promo, la qualité sans preuve arrive souvent trop tard pour la trésorerie.",
      "Essai — chantiers promo",
      "Voir paysagisme",
      "timeline"
    ),
    bodySections: [
      {
        h2: "Cas — Lotissement, 3 jalons jusqu’au PV",
        body: "Préparation → engazonnement → reprises. Preuves à chaque jalon. Réception partielle documentée si une zone attend.",
        bullets: [
          "Jalons promoteur",
          "Preuves pour PV",
          "Écarts météo tracés",
        ],
      },
      {
        h2: "≠ paysagisme exécutant pur",
        body: "Angle relation aménageur/promoteur et réception. La page paysagisme couvre le chantier côté entreprise EV.",
      },
      {
        h2: "Livrable",
        body: "Dossier réception : timeline + photos + réserves.",
      }
    ],
    faq: [
      {
        q: "CCTP / DOE ?",
        a: "Le logiciel suit l’exécution et les preuves ; il ne remplace pas vos pièces marchés.",
      },
      {
        q: "Plusieurs lots / tranches ?",
        a: "Un chantier par tranche ou zones — comme un mini portefeuille jalons.",
      },
      {
        q: "Garanties reprises ?",
        a: "Contrôle J+21 planifié dans le même dossier.",
      },
      {
        q: "Facturation d’avancement ?",
        a: "Oui via réalisé des jalons — voir devis/factu.",
      },
      {
        q: "Puis-je essayer avant d’engager mon équipe sur contrat annuel entretien espaces verts ?",
        a: "15 jours — 1 chantier aménageur en cours.",
      },
    ],
    gridItems: [
      link("Paysagisme", "Devis & chantiers", "/espace-vert/paysagisme"),
      link("Photos AV/AP", "Preuves de livraison", "/espace-vert/photos-avant-apres"),
      link("Devis & facturation", "Jalons & factures", "/espace-vert/devis-facturation"),
      link("Engins & matériel", "Ressources chantier", "/espace-vert/engins-materiel"),
    ],
    ctaPrimaryLabel: "Essai — livraisons promo",
    ctaSecondaryLabel: "Démo réception lot",
  },
  {
    id: "EV-30",
    key: "taille-haies",
    path: "/espace-vert/taille-haies",
    type: "service",
    primaryKw: "planning taille de haies",
    seoTitle: "Taille de haies multi-sites — tournées, accès, saison",
    seoDesc: "42 haies / trimestre, 2 équipes, accès riverains : planifiez, documentez refus, gardez la fréquence. ≠ élagage arbres. Essai 15 j.",
    crumbLabel: "Taille de haies",
    h1Lead: "Taille de haies multi-sites",
    h1: "un poste de charge majeur — trop souvent planifié « s’il reste du temps »",
    sub: "Saison courte, volume haut, riverain qui refuse l’accès : la taille de haies ressemble à de la tonte… jusqu’au premier litige de hauteur.",
    claimBefore: "Des haies",
    claimHighlight: "planifiées",
    claimSub: "planning taille de haies",
    productStrip: "Haies · fréquences · évacuation",
    empathyH2: "La haie oubliée se voit depuis la rue — et sur Facebook",
    empathyBody: "≠ élagage (grimpe, créneau chirurgical). ≠ entretien global. Ici volume multi-sites, accès, photo AV/AP, saison compressée.",
    showcaseTitle: "Tournée taille de haies",
    showcaseSub: "Sites, hauteur/accès, évacuation, statut.",
    showcaseBadgeLeft: { title: "Haies S22", sub: "11 sites" },
    showcaseBadgeRight: "Évacuation OK",
    proofH2: "Traiter les haies comme une prestation pleine",
    proofQuote: "Fréquence, accès, déchets, preuve — les 4 infos qui manquent dans WhatsApp.",
    proofItems: [
      { title: "Cadence", text: "2× / 3× / 4× par an selon essence et exigence." },
      { title: "Accès", text: "Nacelle / escabeau / limite de propriété." },
      { title: "Déchets", text: "Prévoir évacuation / broyage dans le créneau." },
    ],
    vsTitle: "Haies « à la fin de la tonte » vs tournée dédiée",
    demo: d(
      "Démo produit · taille haies",
      "Créer une tournée haies distincte de la tonte",
      "Cas printemps : 11 haies prioritaires syndic, hors tournée tonte du mardi.",
      "Les haies étaient « collées » en fin de tonte — donc souvent reportées. Décision : tournée vendredi dédiée + évacuation.",
      [
        s("Séparer", "Prestation taille haies ≠ tonte sur les fiches."),
        s("Fréquences", "4×/an sur syndics sensibles."),
        s("Tournée", "Vendredi secteur — broyeur + benne."),
        s("Preuve", "Pointage + photo AP sur 3 clients chroniques."),
      ],
      "Tournée haies · Vendredi",
      [
        r("Résidence Acacias — périphérie", "Équipe C + broyeur", "Planifié"),
        r("ZA Les Pins — clôture nord", "Accès nacelle", "Ressource"),
        r("Maison individuelle — mitoyenneté", "Photo AP obligatoire", "Sensible"),
        r("Évacuation déchets", "Benne tournée", "Inclus"),
      ],
      "Quand la haie a sa tournée, elle cesse d’être la variable d’ajustement de la tonte.",
      "Essai — tournées haies",
      "Voir saison printemps",
      "checklist"
    ),
    bodySections: [
      {
        h2: "Cas — 42 haies, accès refusé n°17",
        body: "Tournée trimestre. Site 17 : véhicule gênant. Statut accès refusé + photo. Report sans perdre la fréquence. Relance syndic.",
        bullets: [
          "Volume + saison",
          "Accès documenté",
          "AV/AP recommandés",
        ],
      },
      {
        h2: "Livrable",
        body: "Avancement tournée haies + exceptions accès + photos.",
      },
      {
        h2: "Objection « comme l’entretien »",
        body: "L’entretien mélange les prestations. Les recherches « taille de haies » veulent ce playbook précis.",
      }
    ],
    faq: [
      {
        q: "Hauteur / voisinage ?",
        a: "Photo AV/AP + consigne hauteur sur fiche. Le logiciel documente ; le droit de voisinage reste le vôtre.",
      },
      {
        q: "Nacelle sur haies hautes ?",
        a: "Ressource engin sur l’intervention — voir engins.",
      },
      {
        q: "Déchets de coupe ?",
        a: "Lier benne — page déchets verts.",
      },
      {
        q: "Cadence annuelle ?",
        a: "2 à 4 passages selon contrats ; densifiez au printemps.",
      },
      {
        q: "L’essai suffit-il pour valider mon besoin contrat annuel entretien espaces verts ?",
        a: "15 jours — votre tournée trimestre en cours.",
      },
    ],
    gridItems: [
      link("Entretien EV", "Multi-prestations", "/espace-vert/entretien-espaces-verts"),
      link("Élagage", "Sujets arborés", "/espace-vert/elagage"),
      link("Engins & matériel", "Nacelle / broyeur", "/espace-vert/engins-materiel"),
      link("Saison automne-hiver", "Fenêtres de taille", "/espace-vert/saison-automne-hiver"),
    ],
    ctaPrimaryLabel: "Essai — taille de haies",
    ctaSecondaryLabel: "Démo tournée haies",
  },
  {
    id: "EV-31",
    key: "absences-remplacements",
    path: "/espace-vert/absences-remplacements",
    type: "process",
    primaryKw: "remplacement absence équipe espaces verts",
    seoTitle: "Absences & remplacements équipes EV — trou comblé avant 7h",
    seoDesc: "Arrêt maladie 6h40 : backup, compétences, tournée sauvée. Focus opérationnel planning — pas un SIRH. Essai 15 jours.",
    crumbLabel: "Absences & remplacements",
    h1Lead: "Absences & remplacements équipes espaces verts",
    h1: "couvrir les sites quand un conducteur tombe malade à 6h40",
    sub: "6h40, SMS : le conducteur d’autoportée est en arrêt. La tournée tonte part à 7h15. Sans backup préparé, 9 clients voient un no-show.",
    claimBefore: "Des backups",
    claimHighlight: "sans improvisation",
    claimSub: "remplacement absence espaces verts",
    productStrip: "Absences · backups · sites couverts",
    empathyH2: "Le remplacement se joue avant l’absence, pas pendant",
    empathyBody: "Pas un SIRH (congés, paie). Un playbook : qui peut conduire quoi, quels sites sont sensibles, qui prévenir. L’intérim mal affecté casse autant qu’un trou.",
    showcaseTitle: "Couverture d’absence dans le planning",
    showcaseSub: "Absent tagué, backup affecté, sites arbitrés.",
    showcaseBadgeLeft: { title: "Absent 6h40", sub: "Backup 6h55" },
    showcaseBadgeRight: "Sites couverts",
    proofH2: "Un backup n’est utile que s’il est anticipable",
    proofQuote: "Compétences, secteurs, priorités — préparés avant l’absence.",
    proofItems: [
      { title: "Compétences", text: "Qui peut quoi (engins, élagage, secteur)." },
      { title: "Arbitrage", text: "Que reporte-t-on en premier ?" },
      { title: "Trace", text: "Le client prioritaire reste couvert — documenté." },
    ],
    vsTitle: "Appels paniqués vs matrice de remplacement",
    demo: d(
      "Démo produit · absences",
      "Remplacer un conducteur autoportée en 15 minutes",
      "Cas : 11 tontes secteur est, 1 seul backup formé, 3 haies reportables.",
      "Mardi 6h40. Conducteur équipe B en arrêt. Backup disponible mais il était sur haies ouest.",
      [
        s("Tag absence", "Conducteur B — jour J."),
        s("Identifier backup", "Profil autoportée + permis."),
        s("Arbitrer", "Reporter haies ouest ; garder tontes syndics."),
        s("Notifier", "Planning mobile mis à jour avant départ."),
      ],
      "Absence · Mardi",
      [
        r("Conducteur B", "Arrêt", "Absent"),
        r("Backup Leroy", "Réaffecté secteur est", "OK"),
        r("Haies ouest", "Report mercredi", "Report"),
        r("Syndics est", "Couvert", "Priorité"),
      ],
      "L’absence restera un stress. L’oubli de site, non.",
      "Essai — backups équipes",
      "Voir planning équipes",
      "board"
    ),
    bodySections: [
      {
        h2: "Cas — Remplacement express avant départ tournée",
        body: "Alerte absence. Backup avec permis autoportée. Sites sensibles gardés au titulaire restant ; intérim sur sites faciles. Notification mobile 6h55.",
        bullets: [
          "Compétences backup",
          "Tri sites sensibles",
          "Sync immédiate",
        ],
      },
      {
        h2: "≠ planning construction semaine",
        body: "Ici last minute. Le planning équipes construit ; celui-ci répare.",
      },
      {
        h2: "Objection « on appelle »",
        body: "Appeler ne met pas à jour le mobile de toute l’équipe ni l’historique.",
      }
    ],
    faq: [
      {
        q: "Lien SIRH ?",
        a: "Non. Vous notez l’indispo opérationnelle ; la paie reste ailleurs.",
      },
      {
        q: "Intérim récurrent ?",
        a: "Fiches backup avec consignes ; limitez J1 aux sites simples.",
      },
      {
        q: "Plusieurs absences le même jour ?",
        a: "Priorisez sites renew / marchés ; reportez le reste avec motif.",
      },
      {
        q: "Astreinte chef d’équipe ?",
        a: "Définissez qui arbitre avant 7h — le logiciel exécute l’arbitrage.",
      },
      {
        q: "Puis-je tester PROGESTI sur mon cas « contrat annuel entretien espaces verts » ?",
        a: "15 jours — simulez un arrêt sur votre tournée réelle.",
      },
    ],
    gridItems: [
      link("Planning équipes", "Écran principal", "/espace-vert/planning-equipes"),
      link("Saison printemps", "Pression absences", "/espace-vert/saison-printemps"),
      link("Engins & matériel", "Compétences engins", "/espace-vert/engins-materiel"),
      link("Multi-sites", "Quels sites sauver", "/espace-vert/multi-sites"),
    ],
    ctaPrimaryLabel: "Essai — remplacements",
    ctaSecondaryLabel: "Démo backup 6h40",
  },
  {
    id: "EV-32",
    key: "cimetieres-voirie",
    path: "/espace-vert/cimetieres-voirie",
    type: "service",
    primaryKw: "entretien cimetières voiries espaces verts",
    seoTitle: "Entretien cimetières & voiries végétalisées — priorités usagers",
    seoDesc: "Cimetières, terre-pleins, abords sensibles : planning, discrétion, reporting DST. Niche collectivité souvent sous-couverte. Essai 15 j.",
    crumbLabel: "Cimetières & voiries",
    h1Lead: "Cimetières & voiries végétalisées",
    h1: "des sites publics sensibles — à traiter avec méthode et discrétion",
    sub: "Un cimetière mal tondu un 1er novembre, c’est une crise locale. Les terre-pleins oubliés aussi. Sensibilité usagers ≠ ZA classique.",
    claimBefore: "Des sites sensibles",
    claimHighlight: "tenus",
    claimSub: "entretien cimetières & voiries",
    productStrip: "Cimetières · voiries · collectivités",
    empathyH2: "Ici la qualité se juge avec émotion — pas seulement en m²",
    empathyBody: "Créneaux, discrétion engins, priorités calendaires (Toussaint), reporting élus : cette niche mérite son intent. Proche collectivités, mais recherche dédiée.",
    showcaseTitle: "Sites sensibles au planning communal",
    showcaseSub: "Cimetières, ronds-points, terre-pleins — statuts et fréquences.",
    showcaseBadgeLeft: { title: "Cimetière sud", sub: "Désherbage dû" },
    showcaseBadgeRight: "Passage fait",
    proofH2: "Pourquoi isoler ces niches",
    proofQuote: "Sensibilité usagers + visibilité politique = besoin de cadence et de preuve.",
    proofItems: [
      { title: "Cadences dédiées", text: "Souvent plus exigeantes que le « reste de la ville »." },
      { title: "Consignes", text: "Horaires, accès, respect des lieux." },
      { title: "Reporting", text: "État d’avancement pour DST / élus." },
    ],
    vsTitle: "Sites dilués dans Excel vs niches publiques suivies",
    demo: d(
      "Démo produit · cimetières/voirie",
      "Semaine type : cimetière + 8 ronds-points",
      "Tournée sensible du mercredi matin pour une commune de 18k hab.",
      "Prestataire marché public. Mercredi : cimetière sud (désherbage allées) + 8 ronds-points sur axe d’entrée de ville. Exigence photo sur 2 ronds-points « vitrine ».",
      [
        s("Prioriser", "Cimetière en premier créneau (accès / discrétion)."),
        s("Voirie", "Enchaîner ronds-points géographiquement."),
        s("Preuve", "Pointages + photos sur 2 sites vitrine."),
        s("Reporting", "Statuts remontés pour le point DST."),
      ],
      "Tournée sensible · Mercredi",
      [
        r("Cimetière sud — allées", "Désherbage · 7h–9h30", "Priorité"),
        r("RP entrée ville nord", "Tonte + photo", "Vitrine"),
        r("RP ZA", "Tonte", "Planifié"),
        r("Terre-plein RD", "Désherbage", "Suite"),
      ],
      "Les sites les plus sensibles méritent leur propre rythme — pas les miettes du planning.",
      "Essai — sites sensibles",
      "Voir collectivités",
      "list"
    ),
    bodySections: [
      {
        h2: "Cas — Cimetière sud + 8 terre-pleins, semaine de Toussaint",
        body: "Priorité absolue abords allées et monuments. Engins discrets matin tôt. Terre-pleins en secondaire. Reporting DST avant le week-end.",
        bullets: [
          "Calendrier sensible",
          "Zones honneur vs secondaires",
          "Reporting élu/DST",
        ],
      },
      {
        h2: "≠ désherbage générique",
        body: "Le désherbage transverse existe ; ici le contexte cimetière/voirie et l’opinion publique.",
      },
      {
        h2: "Livrable",
        body: "État des zones sensibles + photos points de contrôle + motifs reports.",
      }
    ],
    faq: [
      {
        q: "Horaires / bruit ?",
        a: "Consignes sur fiche site ; créneaux matinaux recommandés.",
      },
      {
        q: "Fleurs / fleurissement ?",
        a: "Interventions saisonnières planifiables — souvent hors forfait tonte.",
      },
      {
        q: "Sécurité agents ?",
        a: "Consignes accès ; pas un logiciel SS3.",
      },
      {
        q: "Lien marché public ?",
        a: "Oui — page collectivités pour la vue marché.",
      },
      {
        q: "L’essai couvre-t-il vraiment « contrat annuel entretien espaces verts » ?",
        a: "15 jours — cimetière + terre-pleins pilotes.",
      },
    ],
    gridItems: [
      link("Collectivités", "Cadre marchés / régie", "/espace-vert/collectivites"),
      link("Désherbage", "Prestation fréquente sur ces sites", "/espace-vert/desherbage"),
      link("Preuves de passage", "Reporting élus / DST", "/espace-vert/preuves-passages"),
      link("Grands parcs", "Autres sites publics étendus", "/espace-vert/grands-parcs"),
    ],
    ctaPrimaryLabel: "Essai — cimetières & voiries",
    ctaSecondaryLabel: "Démo tournée sensible",
  },
];
