/* eslint-disable */
/** Nouvelles pages SEO Sécurité — SEC-33 → SEC-36 (gaps réels) */
import type { SecPageSpec } from "./build";
import { link } from "./build";

export const secSpecsNew: SecPageSpec[] = [
  {
    id: "SEC-33",
    key: "reporting-client",
    path: "/securite/reporting-client",
    type: "process",
    primaryKw: "reporting client gardiennage",
    seoTitle: "Reporting client gardiennage — synthèse donneur d’ordre",
    seoDesc:
      "Reporting client gardiennage : présences, rondes, incidents, synthèse périodique pour le donneur d’ordre. Essai 15 j sans CB.",
    crumbLabel: "Reporting client",
    h1Lead: "Reporting client / donneur d’ordre",
    h1: "une synthèse périodique — pas une archéologie WhatsApp",
    sub: "Chaque semaine ou chaque mois : vacations tenues, écarts, passages de ronde, main courante. Le donneur d’ordre lit une synthèse ; vous ne reconstruisez plus le fil.",
    claimBefore: "Du réalisé à la",
    claimHighlight: "synthèse DO",
    claimSub: "reporting client · gardiennage",
    productStrip: "Période · sites · présences · incidents · export",
    empathyH2: "Le reporting client du lundi se prépare toute la semaine — ou se bricole à 23h",
    empathyBody: "Couverture, incidents, écarts : si les preuves vivent au fil de l’eau, le rapport part en extraction. Sinon c’est une nuit blanche avant le comité.",
    showcaseTitle: "Synthèse hebdo Usine Nord : prête avant 9h",
    showcaseSub: "Présences, rondes, 1 incident — déjà packagés.",
    showcaseBadgeLeft: { title: "Hebdo S12", sub: "Usine Nord" },
    showcaseBadgeRight: "Envoyée 08:52",
    proofH2: "Reporting = cadence + preuves déjà là",
    proofQuote: "Un bon reporting ne se rédige pas : il s’agrège.",
    proofItems: [
      { title: "Cadence", text: "Hebdo / mensuelle selon contrat." },
      { title: "Contenu", text: "Vacations, écarts, rondes, MC." },
      { title: "Export", text: "Format lisible facility / RSSI." },
    ],
    vsTitle: "Rapport bricolé vs reporting agrégé PROGESTI",
    demo: {
      eyebrow: "Démo · reporting donneur d’ordre",
      h2: "Lundi 08h40 : générer la synthèse S12",
      lead: "Filtre site + période → présences + rondes + incidents → envoi.",
      scenario:
        "Contrat Usine Nord. Le facility manager attend chaque lundi la synthèse de la semaine : postes tenus, anomalies, incidents. L’exploitation génère et envoie avant 9h.",
      steps: [
        { label: "Périmètre", detail: "Usine Nord · S12." },
        { label: "Agrégats", detail: "7/7 vacations · 1 remplacement · rondes OK." },
        { label: "Incidents", detail: "1 entrée MC déjà connue client." },
        { label: "Envoi", detail: "Synthèse exportée 08h52." },
      ],
      uiLabel: "Reporting · Usine Nord · S12",
      uiToolbar: "Cadence hebdo · Donneur d’ordre · Export",
      variant: "split",
      uiSplitLabels: ["Indicateurs", "Détail"],
      uiRows: [
        {
          left: "Vacations tenues",
          right: "7/7 · 1 remplacement tracé",
          status: "OK",
          tone: "ok",
          meta: "174 h pointées",
        },
        {
          left: "Rondes",
          right: "Points validés · 0 manquant ouvert",
          status: "OK",
          tone: "ok",
          meta: "2 tours/nuit",
        },
        {
          left: "Main courante",
          right: "Quai B 02h14 · escalade faite",
          status: "Inclus",
          tone: "info",
          meta: "Déjà signalé",
        },
        {
          left: "Envoi DO",
          right: "Facility manager · 08h52",
          status: "Envoyé",
          tone: "ok",
          meta: "Hebdo S12",
        },
      ],
      uiHint: "Reporting récurrent — distinct du dossier preuves sur audit ciblé.",
      takeaway: "Le client reçoit une cadence — vous arrêtez de reconstruire.",
      primaryCtaLabel: "Essai reporting client",
      secondaryCtaLabel: "Démo synthèse DO",
    },
    bodySections: [
      {
        h2: "Reporting vs preuves-intervention vs copro",
        body: "Reporting = cadence récurrente multi-contextes. Preuves-intervention = audit/demande ciblée. Copro = angle syndic. Trois pages, trois intents.",
        bullets: ["Cadence", "Audit ciblé", "Syndic"],
      },
      {
        h2: "Ce que le donneur d’ordre veut vraiment",
        body: "Pas un roman : postes tenus, exceptions, incidents, tendance. Gardez le jargon vacation / ronde / main courante.",
      },
      {
        h2: "Objection « on envoie déjà un mail »",
        body: "Un mail sans agrégats sourcés redevient un débat. La synthèse issue du réalisé coupe court.",
      },
    ],
    faq: [
      {
        q: "Que contient un reporting client exploitable ?",
        a: "Vacations tenues vs prévues, incidents main courante, écarts de pointage validés, preuves de ronde si exigées — sur la période demandée.",
      },
      {
        q: "Différence avec preuves d’intervention ?",
        a: "Preuves = dossier d’un fait. Reporting = consolidation périodique pour le donneur d’ordre.",
      },
      {
        q: "Grands comptes vs PME ?",
        a: "Même base de faits ; le grand compte exige souvent plus de consolidation multi-sites.",
      },
      {
        q: "Qui génère le rapport ?",
        a: "L’exploitation / le chargé de compte. L’outil fournit les données ; vous choisissez le format client.",
      },
      {
        q: "Par quel pilote démarrer pour « reporting client gardiennage » ?",
        a: "Un client, un cycle de reporting complet (semaine ou mois), sans Excel parallèle.",
      },
    ],
    gridItems: [
      link("Preuves intervention", "Audit ciblé.", "/securite/preuves-intervention"),
      link("Main courante", "Incidents.", "/securite/main-courante"),
      link("Facturation", "Réalisé → facture.", "/securite/facturation-gardiennage"),
      link("Grands comptes", "Reporting national.", "/securite/grands-comptes"),
    ],
    ctaPrimaryLabel: "Essai reporting",
    ctaSecondaryLabel: "Démo synthèse client",
    trustLeft: "Verticale sécurité · reporting DO",
  },
  {
    id: "SEC-34",
    key: "week-end-jours-feries",
    path: "/securite/week-end-jours-feries",
    type: "probleme",
    primaryKw: "planning gardiennage week-end jours fériés",
    seoTitle: "Planning gardiennage week-end & jours fériés",
    seoDesc:
      "Vacations week-end et jours fériés : pool dédié, backups, trous critiques. Essai 15 j sans CB. Dès 29,99 € HT/mois.",
    crumbLabel: "Week-end & jours fériés",
    h1Lead: "Week-end & jours fériés",
    h1: "les vacations où les trous coûtent le plus cher",
    sub: "Dimanches et fériés : pool réduit, désistements plus fréquents, client plus sensible. Anticipez la couverture comme un P1 permanent — pas comme un Excel oublié le vendredi.",
    claimBefore: "Du férié à la",
    claimHighlight: "vacation tenue",
    claimSub: "week-end · jours fériés",
    productStrip: "Pool WE · fériés · backups · alertes",
    empathyH2: "Week-end et fériés : les trous coûtent plus cher — et se voient plus",
    empathyBody: "Majorations, disponibilités rares, sites ouverts : si le planning férié est flou le jeudi, vous le paierez samedi matin.",
    showcaseTitle: "Pont férié : 100 % des P1 confirmés vendredi 16h",
    showcaseSub: "Pool WE, backups, consignes lues.",
    showcaseBadgeLeft: { title: "1er mai", sub: "Nuit + jour" },
    showcaseBadgeRight: "P1 couverts",
    proofH2: "WE/fériés = process à part",
    proofQuote: "Si votre pool week-end = votre fil WhatsApp du mardi, vous allez rater un férié.",
    proofItems: [
      { title: "Pool dédié", text: "Agents OK week-end / fériés." },
      { title: "Confirmation J-2", text: "Pas attendre le vendredi 21h." },
      { title: "Backup nommé", text: "Sur chaque poste P1 férié." },
    ],
    vsTitle: "Excel oublié le vendredi vs couverture férié PROGESTI",
    demo: {
      eyebrow: "Démo · week-end / férié",
      h2: "Vendredi 16h : verrouiller le pont du 1er mai",
      lead: "Scan P1 · confirmations · backups · alertes restantes.",
      scenario:
        "Pont 1er mai. 6 sites P1 (entrées industrielles + 1 retail). Objectif : zéro rouge avant 18h vendredi. Un agent se désiste samedi 19h — backup déjà nommé.",
      steps: [
        { label: "Scan", detail: "Vacations férié + WE · filtre non confirmées." },
        { label: "Pool", detail: "8 agents OK férié · 3 already briefés sites P1." },
        { label: "Verrou", detail: "Titulaire + backup sur chaque P1." },
        { label: "Samedi 19h", detail: "Désistement → backup en 11 min · poste tenu." },
      ],
      uiLabel: "Couverture · Pont 1er mai",
      uiToolbar: "Férié · Pool WE · P1 only",
      uiAlert: "Samedi 19h12 — désistement Site C · backup prêt",
      variant: "board",
      uiRows: [
        {
          left: "Site A — entrée PL",
          right: "Titulaire + backup confirmés",
          status: "Verrouillé",
          tone: "ok",
          meta: "J-2 16:08",
        },
        {
          left: "Site C — retail",
          right: "Désistement samedi · backup intégré",
          status: "Sauvé",
          tone: "warn",
          meta: "19:23 pointage",
        },
        {
          left: "Pool férié",
          right: "8 agents · 2 encore en réserve",
          status: "OK",
          tone: "ok",
          meta: "ETA < 40 min",
        },
        {
          left: "Rouges restants",
          right: "0 sur P1",
          status: "OK",
          tone: "ok",
          meta: "Vendredi 17:55",
        },
      ],
      takeaway: "Les fériés se gagnent avant le week-end — avec un pool et des backups nommés.",
      primaryCtaLabel: "Essai couverture WE/fériés",
      secondaryCtaLabel: "Démo pont férié",
    },
    bodySections: [
      {
        h2: "Pourquoi une page dédiée (anti-cannibalisation)",
        body: "Le planning général traite la semaine. Ici l’intent SEO et le scénario sont WE/fériés : pool réduit, criticité, confirmations anticipées.",
      },
      {
        h2: "Checklist férié (à coller en exploit)",
        body: "Lister P1, confirmer J-2, nommer backups, pousser consignes, scanner rouges vendredi 16h, astreinte exploit joignable.",
        bullets: ["P1 doubles", "Pool férié séparé", "Astreinte bureau", "Lien remplacement urgence"],
      },
      {
        h2: "Objection « on se débrouille toujours »",
        body: "Jusqu’au premier 1er mai où le client ouvre et personne n’est là. La méthode coûte moins cher que le contrat perdu.",
      },
    ],
    faq: [
      {
        q: "Comment anticiper les vacations fériées sans stress du vendredi ?",
        a: "Publiez tôt, nommez backups, vérifiez les trous rouges avant la veille. Les majorations suivent le réalisé pointé.",
      },
      {
        q: "Lien avec astreinte nuit ?",
        a: "Souvent cumulé le week-end. Astreinte = escalade ; ici = couverture calendaire spéciale.",
      },
      {
        q: "Agents qui refusent les fériés ?",
        a: "Le vivier et les compétences aident à trouver qui peut. Le trou doit rester visible, pas caché.",
      },
      {
        q: "Facturation des majorations ?",
        a: "Si le réalisé et les règles sont captés, la facture peut suivre. Sinon le férié se « perd » dans la négociation.",
      },
      {
        q: "Par quel pilote démarrer pour « reporting client gardiennage » ?",
        a: "Un week-end + un jour férié sur 5–8 postes critiques.",
      },
    ],
    gridItems: [
      link("Planning agents", "Process couverture.", "/securite/planning-agents"),
      link("Vacation non pourvue", "Trou rouge.", "/securite/vacation-non-pourvue"),
      link("Remplacement urgence", "Désistement WE.", "/securite/remplacement-urgence"),
      link("Astreinte nuit", "Nuits critiques.", "/securite/astreinte-nuit"),
    ],
    ctaPrimaryLabel: "Essai WE / fériés",
    ctaSecondaryLabel: "Démo couverture férié",
    trustLeft: "Verticale sécurité · week-end & fériés",
  },
  {
    id: "SEC-35",
    key: "heures-contestees",
    path: "/securite/heures-contestees",
    type: "probleme",
    primaryKw: "heures contestées gardiennage",
    seoTitle: "Heures contestées gardiennage — trancher avec le pointage",
    seoDesc:
      "Heures contestées en gardiennage : comparer planning, pointage, vacation. Moins de litiges fin de mois. Essai 15 j sans CB.",
    crumbLabel: "Heures contestées",
    h1Lead: "Heures contestées",
    h1: "trancher avec le réalisé pointé — pas avec des souvenirs",
    sub: "Agent qui conteste, client qui refuse une ligne, écart fin de mois : alignez planning, pointage et vacation. Le débat devient une comparaison d’horodatages.",
    claimBefore: "Du litige à la",
    claimHighlight: "preuve horaire",
    claimSub: "heures contestées · pointage",
    productStrip: "Planning · pointage · écart · décision",
    empathyH2: "Heures contestées : sans pointage, c’est votre parole contre la sienne",
    empathyBody: "Client ou agent : le différend sur les heures se tranche avec un historique, pas avec un souvenir de vacation.",
    showcaseTitle: "Litige agent #M-441 : comparable en 2 minutes",
    showcaseSub: "Planning vs pointage vs vacation.",
    showcaseBadgeLeft: { title: "Litige #M-441", sub: "Nuit 12/03" },
    showcaseBadgeRight: "Tranché",
    proofH2: "Le litige se gagne avec des artefacts",
    proofQuote: "Ce qui n’est pas pointé devient une opinion.",
    proofItems: [
      { title: "Comparaison", text: "Créneau planifié vs pointé." },
      { title: "Contexte", text: "Remplacement, retard, tolérance contrat." },
      { title: "Décision", text: "Heures retenues documentées." },
    ],
    vsTitle: "Dispute WhatsApp vs comparaison horodatée PROGESTI",
    demo: {
      eyebrow: "Démo · heures contestées",
      h2: "Agent conteste −45 min : ouvrez le pointage",
      lead: "Planning 22h–06h · pointage 22h18–06h04 · décision tolérance.",
      scenario:
        "Agent M. conteste une retenue de 45 min sur la nuit du 12/03 (Entrepôt Nord). Exploitation ouvre planning + pointages + éventuel remplacement.",
      steps: [
        { label: "Ouvrir", detail: "Vacation 12/03 · Entrepôt Nord." },
        { label: "Comparer", detail: "Planifié 22h · pointé 22h18 · départ 06h04." },
        { label: "Contexte", detail: "Tolérance contrat 15 min · retard 18 min." },
        { label: "Décision", detail: "3 min hors tolérance retenues · reste accepté · tracé." },
      ],
      uiLabel: "Litige heures · #M-441",
      uiToolbar: "Planning vs pointage · Tolérance contrat",
      uiAlert: "Contestations agent · −45 min demandées · écart réel 18 min",
      variant: "split",
      uiSplitLabels: ["Déclaratif", "Horodaté"],
      uiRows: [
        {
          left: "Planning",
          right: "22h00 → 06h00",
          status: "Réf",
          tone: "info",
          meta: "Créneau publié",
        },
        {
          left: "Pointage agent",
          right: "22h18 → 06h04",
          status: "Horodaté",
          tone: "ok",
          meta: "Mobile site",
        },
        {
          left: "Écart arrivée",
          right: "+18 min · tolérance 15",
          status: "Hors tolérance",
          tone: "warn",
          meta: "3 min retenues",
        },
        {
          left: "Décision exploit",
          right: "7h46 retenues / 8h00 planifiées",
          status: "Tranché",
          tone: "ok",
          meta: "Notifié agent",
        },
      ],
      takeaway: "Le litige d’heures devient une lecture d’écarts — plus une guerre de versions.",
      primaryCtaLabel: "Essai sur un litige réel",
      secondaryCtaLabel: "Démo heures contestées",
    },
    bodySections: [
      {
        h2: "Vs pointage et facturation",
        body: "Pointage = brique. Facturation = émission. Heures contestées = page problème litige (agent ou client).",
      },
      {
        h2: "Process recommandé",
        body: "Ne discuter qu’avec artefacts ouverts. Appliquer la tolérance contrat. Tracer la décision. Alimenter la facture du retenu.",
        bullets: ["Ouvrir vacation", "Comparer horodatages", "Appliquer règle", "Notifier"],
      },
      {
        h2: "Objection « ça va braquer les agents »",
        body: "La transparence protège aussi l’agent honnête. Ce sont les zones grises qui créent le conflit.",
      },
    ],
    faq: [
      {
        q: "Que montrer en cas de contestation client sur 2h ?",
        a: "Pointages début/fin, validations exploitation, éventuelle main courante. Chronologie > discussion.",
      },
      {
        q: "Et si c’est l’agent qui conteste sa vacation ?",
        a: "Même base : horodatages et affectation. Utile aussi pour la paie interne.",
      },
      {
        q: "Quel lien avec la facturation pour « reporting client gardiennage » ?",
        a: "Les heures validées alimentent la facture. Les contestations se traitent avant l’émission idéalement.",
      },
      {
        q: "Délai pour répondre à une contestation ?",
        a: "Minutes si le dossier existe. Demi-journée si vous reconstruisez WhatsApp — signal que le process manque.",
      },
      {
        q: "Par quel pilote démarrer pour « reporting client gardiennage » ?",
        a: "Une semaine de pointage strict + revue des écarts avec l’exploitation.",
      },
    ],
    gridItems: [
      link("Pointage vacations", "Source horodatée.", "/securite/pointage-vacations"),
      link("Facturation gardiennage", "Réalisé → facture.", "/securite/facturation-gardiennage"),
      link("Planning agents", "Créneau de référence.", "/securite/planning-agents"),
      link("Remplacement urgence", "Contexte changement agent.", "/securite/remplacement-urgence"),
    ],
    ctaPrimaryLabel: "Essai litiges heures",
    ctaSecondaryLabel: "Démo comparaison",
    trustLeft: "Verticale sécurité · heures contestées",
  },
  {
    id: "SEC-36",
    key: "chef-exploitation",
    path: "/securite/chef-exploitation",
    type: "audience",
    primaryKw: "chef exploitation société sécurité",
    seoTitle: "Chef d’exploitation sécurité — journée type & couverture",
    seoDesc:
      "Outil pour chef d’exploitation / responsable planning sécurité : alertes couverture, remplacements, reporting. Essai 15 j sans CB.",
    crumbLabel: "Chef d’exploitation",
    h1Lead: "Chef d’exploitation / responsable planning",
    h1: "votre journée type sans fil WhatsApp de 80 messages",
    sub: "Scan des rouges, remplacements, brief consignes, contrôle pointages, préparation reporting : un cockpit vacation — pas cinq Excel et trois groupes.",
    claimBefore: "De l’alerte à la",
    claimHighlight: "vacation tenue",
    claimSub: "chef d’exploitation · gardiennage",
    productStrip: "Journée type · alertes · dispatch · preuves",
    empathyH2: "Le chef d’exploitation vit dans les alertes — pas dans les slides",
    empathyBody: "Trous, remplacements, preuves, reporting : son outil doit prioriser ce qui brûle aujourd’hui, pas afficher un dashboard décoratif.",
    showcaseTitle: "Journée type : 17h scan → 19h zéro rouge nuit",
    showcaseSub: "Alertes, pool, brief, recheck.",
    showcaseBadgeLeft: { title: "Chef exploit", sub: "12 sites" },
    showcaseBadgeRight: "0 rouge 19h",
    proofH2: "Le rôle a besoin d’un cockpit — pas d’un tableur",
    proofQuote: "Si vous apprenez le trou par le client, le process a déjà perdu.",
    proofItems: [
      { title: "Matin", text: "Reprise anomalies nuit + pointages." },
      { title: "17h", text: "Scan couverture nuits." },
      { title: "Astreinte", text: "Remplacements tracés." },
    ],
    vsTitle: "Téléphone + Excel vs cockpit exploit PROGESTI",
    demo: {
      eyebrow: "Démo · journée chef d’exploitation",
      h2: "17h05 → 18h40 : passer de 2 rouges à 0",
      lead: "Scan · priorisation · pool · brief · recheck.",
      scenario:
        "Responsable exploitation, 12 sites, 38 agents. Ritual 17h : vacations 22h–06h. Deux rouges (Entrepôt B, Site retail samedi anticipé). Objectif : 0 rouge avant 19h.",
      steps: [
        { label: "Scan", detail: "2 rouges · 1 orange backup faible." },
        { label: "P1", detail: "Entrepôt B pourvu 17h22." },
        { label: "P2", detail: "Retail : confirmation titulaire + backup." },
        { label: "Recheck", detail: "18h40 · 0 rouge · 1 orange surveillé." },
      ],
      uiLabel: "Cockpit exploit · 17h05",
      uiToolbar: "Chef d’exploitation · 12 sites · Nuit J-0",
      uiAlert: "2 vacations non confirmées · prioriser P1 industriel",
      variant: "timeline",
      uiRows: [
        {
          left: "17h05 — Scan",
          right: "2 rouges · 1 orange",
          status: "Alerte",
          tone: "danger",
          meta: "Nuit 22h–06h",
        },
        {
          left: "17h22 — P1 Entrepôt B",
          right: "Backup L. + consignes",
          status: "Couvert",
          tone: "ok",
          meta: "Brief mobile",
        },
        {
          left: "18h05 — Retail",
          right: "Titulaire confirme · backup nommé",
          status: "OK",
          tone: "ok",
          meta: "Samedi anticipé",
        },
        {
          left: "18h40 — Recheck",
          right: "0 rouge · 1 orange ETA long",
          status: "Sous contrôle",
          tone: "warn",
          meta: "Astreinte briefée",
        },
      ],
      takeaway: "Le chef d’exploitation gagne sa soirée quand les rouges meurent avant 19h.",
      primaryCtaLabel: "Essai cockpit exploit",
      secondaryCtaLabel: "Démo journée type",
    },
    bodySections: [
      {
        h2: "Journée type (template)",
        body: "09h anomalies nuit / pointages. 11h remplacements journée. 14h consignes & briefs. 17h scan nuits. 21h astreinte légère. Lundi : reporting + écarts facture.",
        h3: [
          { title: "Ce qui doit être rouge", body: "Vacation non confirmée, backup absent, consignes non lues sur P1." },
          { title: "Ce que vous ne devez plus faire", body: "Relancer 15 agents en message groupé sans statut de vacation." },
        ],
      },
      {
        h2: "Anti-cannibalisation",
        body: "Planning = process. Vacation non pourvue = problème. Remplacement = urgence. Cette page = persona / journée type du chef d’exploitation.",
      },
      {
        h2: "Objection « je n’ai pas le temps d’un nouvel outil »",
        body: "Le temps part déjà dans WhatsApp. Un cockpit réduit les allers-retours — essai 15 j sur une semaine réelle.",
      },
    ],
    faq: [
      {
        q: "Que doit voir un chef d’explo à 9h et à 17h ?",
        a: "9h : incidents nuit + écarts pointage. 17h : trous de vacation nuit / lendemain encore rouges. Deux rituels, une source de vérité.",
      },
      {
        q: "Différence avec le pilier logiciel ?",
        a: "Le pilier parle au dirigeant / flux global. Ici l’angle est le quotidien du chef d’exploitation.",
      },
      {
        q: "Combien d’écrans différents doit-il ouvrir ?",
        a: "L’idéal : planning + alertes + preuves sans reconstruire trois Excel. Moins de bascules = moins d’oublis.",
      },
      {
        q: "Délégation aux chefs de site / PC ?",
        a: "Oui via PC sécurité / multi-sites. Le chef d’explo garde la priorisation.",
      },
      {
        q: "Par quel pilote démarrer pour « reporting client gardiennage » ?",
        a: "Deux semaines où le chef d’explo n’utilise plus Excel pour les alertes du jour — mesurez le temps récupéré.",
      },
    ],
    gridItems: [
      link("Planning agents", "Couverture.", "/securite/planning-agents"),
      link("Vacation non pourvue", "Trous.", "/securite/vacation-non-pourvue"),
      link("Remplacement urgence", "Dispatch.", "/securite/remplacement-urgence"),
      link("PC sécurité", "Supervision live.", "/securite/pc-securite"),
    ],
    ctaPrimaryLabel: "Essai pour l’exploitation",
    ctaSecondaryLabel: "Démo journée type",
    trustLeft: "Verticale sécurité · chef d’exploitation",
  },
];
