/* eslint-disable */
/** Specs Sécurité — part 1 · pilier / hub / services cœur (SEC-01 → SEC-09) */
import type { SecPageSpec } from "./build";
import { link } from "./build";

export const secSpecsPart1: SecPageSpec[] = [
  {
    id: "SEC-01",
    key: "logiciel-securite-gardiennage",
    path: "/logiciel-securite-gardiennage",
    type: "pilier",
    primaryKw: "logiciel gardiennage",
    seoTitle: "Logiciel gardiennage — vacations, preuves, facture réalisé",
    seoDesc:
      "Logiciel pour sociétés de sécurité privée : planning vacations, pointage, main courante, facture du réalisé. Essai 15 j sans CB. Dès 29,99 € HT/mois.",
    crumbLabel: "Logiciel gardiennage & sécurité",
    h1Lead: "Logiciel pour sociétés de sécurité privée",
    h1: "vacations tenues, preuves terrain, facture du réalisé",
    sub: "Affectez l’agent, couvrez le poste, gardez la main courante et les pointages, facturez ce qui a vraiment été tenu — sans reconstruire le mois sur Excel et WhatsApp.",
    claimBefore: "Du poste à la",
    claimHighlight: "facture",
    claimSub: "logiciel gardiennage · vacations & preuves",
    productStrip: "Vacations · pointage · main courante · facture réalisé",
    empathyH2: "Vendredi 17h45 : la vacation de nuit n’a plus de titulaire",
    empathyBody: "Site Entrepôt Nord, vacation 22h–06h. L’agent prévu se déclare indisponible. Sans backup visible et sans consignes sur mobile, vous improviserez jusqu’à 21h50 — et le client saura. PROGESTI porte la chaîne vacation → présence → facture du réalisé, pas un tableur du lundi matin.",
    showcaseTitle: "Une seule chaîne : vacation → présence → preuve → facture",
    showcaseSub: "Ce que l’agent pointe sur le site alimente ce que vous facturez au donneur d’ordre.",
    showcaseBadgeLeft: { title: "Vacation 22h–06h", sub: "Entrepôt Nord · couverte" },
    showcaseBadgeRight: "Réalisé → facture",
    proofH2: "Conçu pour le rythme d’une société de gardiennage — pas un ERP générique",
    proofQuote: "Si ce n’est pas dans le planning et le pointage, ce n’est pas facturable ni défendable.",
    proofItems: [
      {
        title: "Posts & vacations",
        text: "Titulaire, backup, trou rouge : la couverture est visible avant l’appel client.",
      },
      {
        title: "Preuves terrain",
        text: "Pointages, passages de ronde, main courante — historisés par site et par vacation.",
      },
      {
        title: "Facture du réalisé",
        text: "Les heures tenues alimentent la ligne de facture — moins de litiges de fin de mois.",
      },
    ],
    vsTitle: "Excel + WhatsApp vs chaîne vacation → facture PROGESTI",
    demo: {
      eyebrow: "Démo · flux société de sécurité",
      h2: "Vendredi 17h45 : sauver la nuit, garder la preuve, préparer la facture",
      lead: "Désistement agent → backup briefé → pointage nuit → ligne facture lundi. Un seul fil.",
      scenario:
        "Site « Entrepôt Nord » (donneur d’ordre logistique). Vacation poste entrée 22h–06h. À 17h45, l’agent titulaire M. se désiste. Le chef d’exploitation doit pourvoir, briefer les consignes portail, et s’assurer que le week-end sera exploitable lundi pour le reporting client.",
      steps: [
        {
          label: "Couverture",
          detail: "Trou rouge sur la vacation 22h–06h — backup L. déjà passé sur le site, affecté 17h52.",
        },
        {
          label: "Brief consignes",
          detail: "Fiche site mobile : digicode, contacts chef de quai, ronde parking obligatoire 3×/nuit.",
        },
        {
          label: "Présence & main courante",
          detail: "Pointage 21h58 → 06h04 · incident quai noté 02h14 dans la main courante liée à la vacation.",
        },
        {
          label: "Facture réalisé",
          detail: "Lundi : 8h06 pointées → ligne brouillon contrat cadre Entrepôt Nord.",
        },
      ],
      uiLabel: "Vacation 22h–06h · Entrepôt Nord",
      uiToolbar: "Ven. 14/03 · Exploitation · 12 sites · 1 alerte couverture",
      uiAlert: "17h45 — Titulaire M. indisponible · vacation nuit non confirmée",
      uiHint: "Illustration PROGESTI — organisation vacations / preuves, pas un substitut agrément CNAPS.",
      uiColumns: ["Élément", "Détail", "Statut"],
      variant: "list",
      uiRows: [
        {
          left: "Titulaire prévu",
          right: "Agent M. Dupont — désistement 17h45",
          status: "Alerte",
          tone: "danger",
          meta: "17:45 · SMS reçu exploitation",
        },
        {
          left: "Backup affecté",
          right: "Agent L. Moreau — consignes portail lues",
          status: "Couvert",
          tone: "ok",
          meta: "17:52 · brief mobile OK",
        },
        {
          left: "Pointage réel",
          right: "21h58 → 06h04 · poste entrée tenu",
          status: "Horodaté",
          tone: "ok",
          meta: "GPS site · écart +4 min toléré",
        },
        {
          left: "Main courante",
          right: "02h14 — tentative accès quai B · escalade chef de quai",
          status: "Noté",
          tone: "info",
          meta: "Lié vacation #VN-2206",
        },
        {
          left: "Ligne facture",
          right: "8h06 facturables · brouillon contrat cadre",
          status: "Prêt",
          tone: "ok",
          meta: "Lundi 08:12 · exportable",
        },
      ],
      takeaway:
        "Le client n’a jamais su qu’il y a eu un désistement — et vous avez les preuves pour le reporting et la facture.",
      primaryCtaLabel: "Essayer sur vos vacations",
      secondaryCtaLabel: "Voir le flux en démo",
    },
    bodySections: [
      {
        h2: "Ce que vous structurez en société de gardiennage (sans promesse miracle)",
        body: "Posts fixes, renforts, consignes site, rondes, main courante, historique pour le donneur d’ordre : PROGESTI centralise l’opérationnel. Ce n’est pas un substitut à vos obligations professionnelles ni à l’agrément — c’est l’outil qui évite le chaos administratif entre le terrain et la facture.",
        bullets: [
          "Vacations par site, poste et créneau (jour / nuit / week-end)",
          "Backups nommés avant le trou — pas après l’appel client",
          "Consignes accessibles sur mobile à la prise de poste",
          "Réalisé pointé → base saine pour paie et facturation",
        ],
      },
      {
        h2: "Journée type d’un gérant / chef d’exploitation (15–80 agents)",
        body: "Matin : relecture des alertes couverture J-0 / J-1. Midi : remplacements et briefings. Soir : validation des pointages de la nuit précédente et préparation du reporting client. Sans outil unique, chaque étape rebondit sur Excel et WhatsApp.",
        h3: [
          {
            title: "Avant 18h",
            body: "Les trous de vacation nuit doivent être rouges et traités — pas découverts à 22h par le gardien du site voisin.",
          },
          {
            title: "Lundi matin",
            body: "Le donneur d’ordre demande « qui était là ce week-end ? » — vous exportez, vous ne reconstruisez pas.",
          },
        ],
      },
      {
        h2: "Objections fréquentes des dirigeants de sociétés de sécurité",
        body: "« Excel + WhatsApp suffit » jusqu’au premier trou client. « Les agents ne pointeront pas » — si le pointage conditionne la vacation tenue et la paie, ils pointent. « Trop lourd pour notre taille » — le tarif public démarre pour les TPE. « C’est un outil propreté déguisé » — non : lexique vacations, postes, main courante, rondes.",
        bullets: [
          "Verticale /securite séparée propreté et espaces verts",
          "Essai 15 jours sans CB sur vos vrais sites",
          "Support FR, équipe basée en Occitanie",
        ],
      },
      {
        h2: "Pour qui : de la TPE multi-sites au contrat cadre",
        body: "Même logique pour 12 agents ou 120 : une couverture lisible, des preuves exploitables, une facture alignée. Les pages audience (industriel, retail, event, grands comptes) détaillent les contraintes ; ce pilier tient le flux global vacation → facture.",
      },
    ],
    faq: [
      {
        q: "Comment on couvre une vacation de nuit quand le titulaire lâche à 17h45 ?",
        a: "Vous voyez le trou sur le planning, vous affectez un backup du pool, vous lui poussez les consignes site sur mobile, puis vous gardez le pointage début/fin. Le lundi, la ligne de facture part du réalisé — pas d’une reconstruction WhatsApp.",
      },
      {
        q: "C’est un logiciel de nettoyage renommé ?",
        a: "Non. La verticale /securite est séparée (propreté et espaces verts ont leurs arbres). Ici le vocabulaire est vacation, poste, ronde, main courante, backup, donneur d’ordre.",
      },
      {
        q: "PROGESTI remplace-t-il l’agrément / le cadre CNAPS ?",
        a: "Non. C’est l’outil d’organisation : vacations, preuves, facturation. Pas un conseil juridique ni un substitut à vos obligations professionnelles.",
      },
      {
        q: "Le pointage mobile sert à quoi concrètement en fin de mois ?",
        a: "À aligner les heures facturables sur ce qui s’est passé sur site. Moins d’écarts « on avait dit 8h » vs « il est parti à 5h50 » — le réalisé pointe, la facture suit.",
      },
      {
        q: "On commence comment sans migrer 80 postes d’un coup ?",
        a: "Pilotez 8–12 postes critiques (souvent les nuits et les sites qui appellent). Tenez deux semaines. Puis élargissez. Essai 15 jours sans CB, dès 29,99 € HT/mois.",
      },
    ],
    gridItems: [
      link("Gardiennage site", "Poste fixe & couverture vacations.", "/securite/gardiennage"),
      link("Planning agents", "Trous visibles avant le client.", "/securite/planning-agents"),
      link("Facturation gardiennage", "Heures pointées → facture.", "/securite/facturation-gardiennage"),
      link("Reporting client", "Synthèse donneur d’ordre.", "/securite/reporting-client"),
    ],
    ctaPrimaryLabel: "Essayer sur mes vacations",
    ctaSecondaryLabel: "Voir une démo terrain",
    trustLeft: "Verticale sécurité · vacations & preuves",
  },
  {
    id: "SEC-02",
    key: "hub",
    path: "/securite",
    type: "hub",
    primaryKw: "solutions sécurité PROGESTI",
    seoTitle: "Sécurité & gardiennage — hub solutions",
    seoDesc:
      "Hub sécurité & gardiennage : postes, rondes, planning, preuves, industriel, retail, event, main courante. Essai 15 j sans CB.",
    crumbLabel: "Sécurité & gardiennage",
    h1Lead: "Sécurité & gardiennage",
    h1: "choisissez la page qui correspond à votre terrain",
    sub: "Poste fixe, rondes prouvées, vacation non pourvue, event one-shot, reporting donneur d’ordre : chaque page a un angle SEO et un scénario distinct. Ce hub oriente — il ne mélange pas.",
    claimBefore: "Du besoin terrain à la",
    claimHighlight: "bonne page",
    claimSub: "hub sécurité · anti-cannibalisation",
    productStrip: "Hub · services · audiences · process · problèmes",
    empathyH2: "Une recherche Google ≠ une vacation ≠ une ronde",
    empathyBody: "« Preuve de ronde entrepôt » et « sécurité festival » ne doivent pas atterrir sur la même landing fourre-tout. Ce hub oriente vers la page qui parle votre terrain — puis vers l’essai.",
    showcaseTitle: "Parcours sécurité sans cannibalisation",
    showcaseSub: "Intent → page fille → essai sur vos vrais sites.",
    showcaseBadgeLeft: { title: "Hub /securite", sub: "Navigation par intent" },
    showcaseBadgeRight: "1 page = 1 angle",
    proofH2: "Guider vers le bon scénario — pas tout dire en une page",
    proofQuote: "La bonne page parle de VOTRE vacation — pas d’un SaaS générique.",
    proofItems: [
      {
        title: "Services",
        text: "Gardiennage, rondes, agents, sûreté sites, consignes, main courante.",
      },
      {
        title: "Audiences",
        text: "Industriel, retail, event, copro, BTP, sites sensibles, PME, grands comptes.",
      },
      {
        title: "Process & problèmes",
        text: "Planning, pointage, preuves, factu, PC sécu, vacation non pourvue, remplacement.",
      },
    ],
    vsTitle: "Landing fourre-tout vs hub intent clair",
    demo: {
      eyebrow: "Démo · parcours hub",
      h2: "Trouver la bonne porte en 30 secondes",
      lead: "Trois intentions fréquentes → trois pages filles → un essai.",
      scenario:
        "Un dirigeant tape trois recherches dans la semaine : « logiciel rondes sécurité », « vacation non pourvue », « facturation gardiennage ». Trois pages, trois démos — pas une seule page qui dilue tout.",
      steps: [
        { label: "Service", detail: "Rondes & preuves → /securite/rondes-surveillance" },
        { label: "Problème", detail: "Trou de vacation → /securite/vacation-non-pourvue" },
        { label: "Process", detail: "Facture du réalisé → /securite/facturation-gardiennage" },
        { label: "Essai", detail: "15 j sans CB sur le scénario qui vous brûle vraiment." },
      ],
      uiLabel: "Hub navigation · intents sécurité",
      uiToolbar: "Filtres : Service · Audience · Process · Problème",
      uiHint: "Hub de navigation SEO — pas une page fourre-tout.",
      variant: "board",
      uiRows: [
        {
          left: "Poste fixe / vacation",
          right: "→ /securite/gardiennage",
          status: "Service",
          tone: "ok",
          meta: "Couverture titulaire + backup",
        },
        {
          left: "Rondes & QR passages",
          right: "→ /securite/rondes-surveillance",
          status: "Service",
          tone: "ok",
          meta: "Preuves horodatées",
        },
        {
          left: "Vacation non pourvue",
          right: "→ /securite/vacation-non-pourvue",
          status: "Problème",
          tone: "danger",
          meta: "Trou rouge avant l’appel client",
        },
        {
          left: "Event / one-shot",
          right: "→ /securite/evenementiel",
          status: "Audience",
          tone: "info",
          meta: "Staffing concert / salon",
        },
      ],
      takeaway: "Chaque intent a sa page et sa démo — le hub ne cannibalise pas le pilier money.",
      primaryCtaLabel: "Essai 15 j sans CB",
      secondaryCtaLabel: "Voir le pilier logiciel",
    },
    bodySections: [
      {
        h2: "Comment utiliser ce hub",
        body: "Identifiez votre douleur du moment : trou de vacation, preuve de ronde, facture contestée, site industriel, event. Ouvrez la page fille. Le pilier /logiciel-securite-gardiennage reste la porte « logiciel gardiennage » large.",
        bullets: [
          "Pilier money = intent transactionnel large",
          "Filles = intent précis (service, audience, process, problème)",
          "Maillage tarifs + essai sur chaque page",
        ],
      },
      {
        h2: "Ce que vous ne trouverez pas ici",
        body: "Pas de télésurveillance vidéo vendue comme produit, pas de formation SSIAP, pas de conseil juridique CNAPS, pas de mélange avec la verticale espaces verts ou propreté.",
      },
    ],
    faq: [
      {
        q: "Je cherche à couvrir un poste fixe copro : où aller ?",
        a: "Page gardiennage + copropriétés. Le pilier logiciel si vous voulez le flux global vacation → facture.",
      },
      {
        q: "Je dois prouver des rondes de nuit : quelle page ?",
        a: "Rondes & surveillance, puis preuves d’intervention. L’astreinte nuit couvre l’angle escalade 2h du matin.",
      },
      {
        q: "Pourquoi autant de pages sécurité ?",
        a: "Parce qu’un responsable planning et un organisateur event ne posent pas la même question. Une page unique les fait rebondir tous les deux.",
      },
      {
        q: "Où est la facturation des heures de vacation ?",
        a: "Page facturation gardiennage — branchée sur le pointage, pas sur un Excel de fin de mois.",
      },
      {
        q: "Par où commencer l’essai ?",
        a: "Choisissez la page de votre douleur du mois, ouvrez la démo, puis lancez l’essai sur un petit lot de postes réels.",
      },
    ],
    gridItems: [
      link("Logiciel gardiennage", "Pilier — vacation → facture.", "/logiciel-securite-gardiennage"),
      link("Gardiennage", "Postes fixes & couverture.", "/securite/gardiennage"),
      link("Rondes", "Passages prouvés.", "/securite/rondes-surveillance"),
      link("Vacation non pourvue", "Voir le trou avant.", "/securite/vacation-non-pourvue"),
    ],
    ctaPrimaryLabel: "Trouver ma page sécurité",
    ctaSecondaryLabel: "Parler à un humain",
    trustLeft: "Verticale sécurité · hub intent",
  },
  {
    id: "SEC-03",
    key: "gardiennage",
    path: "/securite/gardiennage",
    type: "service",
    primaryKw: "logiciel société de gardiennage",
    seoTitle: "Logiciel société de gardiennage — postes & vacations",
    seoDesc:
      "Logiciel société de gardiennage : postes fixes, vacations couvertes, backups, preuves de présence. Essai 15 j sans CB.",
    crumbLabel: "Gardiennage site",
    h1Lead: "Logiciel société de gardiennage",
    h1: "tenir le poste — pas seulement le planifier",
    sub: "Poste fixe, vacation nommée, backup visible, pointage réel : la couverture client se joue avant l’ouverture du site, pas dans le fil WhatsApp à 21h.",
    claimBefore: "Du poste à la",
    claimHighlight: "présence prouvée",
    claimSub: "gardiennage site · vacations",
    productStrip: "Poste fixe · vacation · backup · pointage",
    empathyH2: "Un poste sans backup, c’est une alerte client en puissance",
    empathyBody: "Titulaire malade, consignes dans un classeur, horaires flous : le donneur d’ordre ne veut pas votre stress, il veut un poste tenu. Le gardiennage site, c’est de la couverture visible avant 22h — pas une déclaration le lendemain.",
    showcaseTitle: "Couverture de poste : titulaire, backup, confirmation",
    showcaseSub: "Ce que l’exploitation voit avant que le site n’ouvre.",
    showcaseBadgeLeft: { title: "Poste entrée", sub: "Vacation 6h–14h" },
    showcaseBadgeRight: "Couvert ✓",
    proofH2: "Gardiennage = discipline de couverture",
    proofQuote: "Un poste sans backup nommé est un trou en sursis.",
    proofItems: [
      { title: "Vacation claire", text: "Site, poste, créneau, agent — pas une ligne floue « équipe A »." },
      { title: "Backup", text: "Nommé, joignable, idéalement déjà passé sur le site." },
      { title: "Preuve", text: "Pointage début/fin = présence défendable." },
    ],
    vsTitle: "Planning papier vs couverture de poste dans PROGESTI",
    demo: {
      eyebrow: "Démo · poste fixe gardiennage",
      h2: "Lundi 5h50 : le poste entrée doit être tenu à 6h pile",
      lead: "Confirmation vacation, consignes accès, pointage — avant que le chef de site client arrive.",
      scenario:
        "Site « Résidence logistique Sud ». Poste entrée VL 06h–14h. Agent titulaire A. Benali. Backup K. Rossi. Le donneur d’ordre ouvre les quais à 6h15 : l’agent doit déjà être badge + consignes lues.",
      steps: [
        { label: "Planning J-1", detail: "Vacation confirmée · backup nommé · consignes version 12 visibles." },
        { label: "Prise de poste", detail: "Pointage 05h52 · digicode + contacts chef de quai sur mobile." },
        { label: "Contrôle exploit", detail: "Statut « en poste » visible PC / bureau à 06h00." },
        { label: "Fin vacation", detail: "Pointage 14h03 · relève agent suivant déjà confirmée." },
      ],
      uiLabel: "Poste entrée · Résidence logistique Sud",
      uiToolbar: "Lun. 17/03 · 06h–14h · Poste fixe",
      variant: "checklist",
      uiRows: [
        {
          left: "Titulaire A. Benali",
          right: "Vacation confirmée J-1 18h22",
          status: "Confirmé",
          tone: "ok",
          meta: "Compétence site : 14 passages",
        },
        {
          left: "Backup K. Rossi",
          right: "Dispo rayon 25 min · briefé 1×",
          status: "Prêt",
          tone: "ok",
          meta: "Pool nuit/jour distinct",
        },
        {
          left: "Consignes accès",
          right: "Digicode + liste livreurs autorisés",
          status: "Lues",
          tone: "ok",
          meta: "Mobile · v12 · 05:48",
        },
        {
          left: "Pointage entrée",
          right: "05h52 — présence poste",
          status: "Horodaté",
          tone: "ok",
          meta: "Écart −8 min vs planning",
        },
      ],
      uiHint: "Angle poste fixe — distinct des rondes mobiles (autre page).",
      takeaway: "Gardiennage site = couverture + preuve de présence, pas un planning décoratif.",
      primaryCtaLabel: "Essayer sur un poste réel",
      secondaryCtaLabel: "Démo couverture",
    },
    bodySections: [
      {
        h2: "Poste fixe vs ronde : ne pas mélanger les intents",
        body: "Cette page traite la tenue de poste (vacation statique, entrée, accueil, portail). Les passages de ronde avec points QR ont leur page dédiée. Le pilier relie les deux dans le flux facture.",
        bullets: [
          "Ici : couverture vacation poste",
          "Rondes → /securite/rondes-surveillance",
          "Trous → /securite/vacation-non-pourvue",
        ],
      },
      {
        h2: "Process de couverture type (société 20–60 agents)",
        body: "Inventaire des postes critiques, titulaire + backup par créneau, confirmation J-1, alerte rouge si non confirmé, brief consignes à la prise de poste, pointage obligatoire.",
        h3: [
          {
            title: "Posts critiques",
            body: "Ceux où le client voit le trou en moins de 10 minutes (accueil, portail PL, site sensible).",
          },
          {
            title: "Week-end & fériés",
            body: "Pool dédié — voir aussi week-end / jours fériés.",
          },
        ],
      },
      {
        h2: "Objections terrain",
        body: "« On gère au feeling » marche jusqu’au premier contrat cadre multi-sites. « Les backups ne connaissent pas le site » — d’où la fiche consignes mobile obligatoire avant prise de poste.",
      },
    ],
    faq: [
      {
        q: "Comment rendre visibles les trous de poste avant que le client appelle ?",
        a: "Le planning montre titulaire + backup. Un trou non couvert reste rouge. Vous traitez avant la prise de vacation, pas après le mail du facility.",
      },
      {
        q: "Les consignes site peuvent-elles suivre l’agent de backup ?",
        a: "Oui : le brief est sur le poste, pas dans la tête du titulaire. Le backup lit les consignes sur mobile avant d’arriver.",
      },
      {
        q: "Différence avec la page rondes ?",
        a: "Gardiennage = tenir un poste / une vacation. Rondes = prouver un parcours de points. Souvent complémentaires sur le même site.",
      },
      {
        q: "On gère déjà ça sur Excel par site client",
        a: "Excel ne pousse pas le brief au mobile du backup à 18h10. C’est là que les postes lâchent.",
      },
      {
        q: "Par où piloter un premier site ?",
        a: "Un site, deux semaines, titulaire + 2 backups nommés, consignes à jour. Puis vous répliquez le modèle.",
      },
    ],
    gridItems: [
      link("Logiciel gardiennage", "Pilier vacation → facture.", "/logiciel-securite-gardiennage"),
      link("Planning agents", "Anticiper les trous.", "/securite/planning-agents"),
      link("Consignes accès", "Brief avant prise de poste.", "/securite/controle-acces-consignes"),
      link("Remplacement urgence", "Couvrir en minutes.", "/securite/remplacement-urgence"),
    ],
    ctaPrimaryLabel: "Essai sur vos postes",
    ctaSecondaryLabel: "Voir la démo poste",
    trustLeft: "Verticale sécurité · gardiennage site",
  },
  {
    id: "SEC-04",
    key: "rondes-surveillance",
    path: "/securite/rondes-surveillance",
    type: "service",
    primaryKw: "logiciel rondes sécurité",
    seoTitle: "Logiciel rondes sécurité — passages horodatés",
    seoDesc:
      "Logiciel rondes sécurité : points de passage horodatés, alertes ronde manquante, preuves audit client. Essai 15 j sans CB.",
    crumbLabel: "Rondes & surveillance",
    h1Lead: "Logiciel rondes de sécurité",
    h1: "prover le passage — pas « on a fait le tour »",
    sub: "Points de contrôle, horodatage, ronde manquante visible par l’exploitation : ce que le donneur d’ordre demande en audit, vous l’avez déjà.",
    claimBefore: "Du passage à la",
    claimHighlight: "preuve",
    claimSub: "rondes · QR / points de contrôle",
    productStrip: "Ronde · points · horodatage · alerte manquant",
    empathyH2: "« On a fait le tour » ne passe pas un audit du 12 mars",
    empathyBody: "Entrepôt frigo, quai, parking : le client veut des passages horodatés. Une ronde déclarée au téléphone ne tient pas face à un écart sur le point Q7 à 23h41.",
    showcaseTitle: "Ronde de nuit : chaque point compte",
    showcaseSub: "Validé, en retard, manquant — lisible pour l’exploitation.",
    showcaseBadgeLeft: { title: "Ronde N1", sub: "6 points · 2 tours" },
    showcaseBadgeRight: "5/6 validés",
    proofH2: "Preuve de ronde = discipline de passage",
    proofQuote: "Un point non scanné à 00h28 doit alerter à 00h35 — pas à 9h au café.",
    proofItems: [
      { title: "Parcours défini", text: "Points ordonnés par site, liés à la vacation." },
      { title: "Horodatage", text: "Chaque validation laisse une trace exploitable." },
      { title: "Alerte manquant", text: "L’exploitation voit le trou de ronde pendant la nuit." },
    ],
    vsTitle: "Carnet papier vs ronde horodatée PROGESTI",
    demo: {
      eyebrow: "Démo · ronde de nuit",
      h2: "00h12 → 01h05 : tour parking + locaux tech",
      lead: "Cinq points validés, un manquant — alerte exploitation avant la fin de vacation.",
      scenario:
        "Usine Nord, vacation 22h–06h, agent L. Moreau. Ronde obligatoire : portail PL, TGBT, parking VL, quais, local pompes. Le donneur d’ordre exige l’historique des passages sur le mois.",
      steps: [
        { label: "Départ ronde", detail: "00h12 — point A portail PL validé." },
        { label: "Enchaînement", detail: "TGBT 00h28 · parking 00h41 · quais 00h55." },
        { label: "Manquant", detail: "Local pompes non scanné — alerte exploit 01h05." },
        { label: "Clôture", detail: "Agent rappelé · point validé 01h18 · historique complet." },
      ],
      uiLabel: "Ronde N1 · Usine Nord",
      uiToolbar: "Nuit 14→15/03 · Vacation 22h–06h · Agent L. Moreau",
      uiAlert: "01h05 — Point C « local pompes » non scanné · délai dépassé",
      variant: "timeline",
      uiRows: [
        {
          left: "Point A — portail PL",
          right: "Scan agent · photo optionnelle",
          status: "Validé",
          tone: "ok",
          meta: "00:12:04",
        },
        {
          left: "Point B — local TGBT",
          right: "Accès badge + scan",
          status: "Validé",
          tone: "ok",
          meta: "00:28:17",
        },
        {
          left: "Point C — local pompes",
          right: "Non scanné · délai 35 min dépassé",
          status: "Manquant",
          tone: "danger",
          meta: "Alerte exploit 01:05",
        },
        {
          left: "Point C — rattrapage",
          right: "Scan après rappel radio",
          status: "Validé",
          tone: "warn",
          meta: "01:18:42 · hors créneau idéal",
        },
        {
          left: "Export audit mars",
          right: "Passages agrégés pour donneur d’ordre",
          status: "Prêt",
          tone: "ok",
          meta: "Filtre site + période",
        },
      ],
      uiHint: "Preuves de passage via mobile — pas un boîtier hardware vendu ici.",
      takeaway: "La ronde manquante se corrige dans la nuit — pas dans un mail d’excuse le lundi.",
      primaryCtaLabel: "Essayer sur une ronde réelle",
      secondaryCtaLabel: "Démo preuves de passage",
    },
    bodySections: [
      {
        h2: "Ronde ≠ pointage de présence poste",
        body: "Le pointage dit « l’agent est arrivé / parti ». La ronde dit « l’agent est passé aux points sensibles ». Les deux pages sont complémentaires ; celle-ci est SEO « rondes / preuves de passage ».",
      },
      {
        h2: "Ce que demande souvent le donneur d’ordre",
        body: "Historique des passages, exceptions (point manqué, rattrapage), lien avec la vacation et l’agent. PROGESTI structure ces preuves — sans claim « certification » abusive.",
        bullets: [
          "Parcours par site",
          "Alertes délai",
          "Export période pour audit",
        ],
      },
      {
        h2: "Jargon terrain utile",
        body: "Points de contrôle, tour de ronde, vacation porteuse, main courante si anomalie constatée pendant la ronde (intrusion, porte ouverte, fuite).",
      },
    ],
    faq: [
      {
        q: "Le client demande le détail de la ronde du 12 mars 22h–6h : je sors quoi en 2 minutes ?",
        a: "L’historique des points de passage avec horodatage, les écarts éventuels, et l’agent concerné. Pas un récit oral — un dossier exportable.",
      },
      {
        q: "Que se passe-t-il si un point de ronde est sauté ?",
        a: "L’écart apparaît côté exploitation. Vous pouvez relancer l’agent ou documenter la cause avant que le rapport client parte incomplet.",
      },
      {
        q: "QR / NFC obligatoires ?",
        a: "L’important est la validation horodatée des étapes. Le mode de scan dépend de votre déploiement terrain ; la preuve, elle, doit exister.",
      },
      {
        q: "Lien avec la vacation de nuit ?",
        a: "La vacation couvre la présence ; la ronde prouve le parcours. Sur un site industriel, les deux se complètent.",
      },
      {
        q: "Comment démarrer sans cartographier 40 sites ?",
        a: "Commencez par 1–2 sites audit-sensibles (ceux qui demandent déjà des preuves). Stabilisez le modèle de tournée, puis déployez.",
      },
    ],
    gridItems: [
      link("Gardiennage", "Tenue de poste.", "/securite/gardiennage"),
      link("Preuves intervention", "Dossier audit client.", "/securite/preuves-intervention"),
      link("Main courante", "Incidents horodatés.", "/securite/main-courante"),
      link("Sites industriels", "Exigence traçabilité.", "/securite/sites-industriels"),
    ],
    ctaPrimaryLabel: "Essai rondes",
    ctaSecondaryLabel: "Voir la démo ronde",
    trustLeft: "Verticale sécurité · rondes & preuves",
  },
  {
    id: "SEC-05",
    key: "agents-securite",
    path: "/securite/agents-securite",
    type: "service",
    primaryKw: "logiciel gestion agents de sécurité",
    seoTitle: "Gestion agents de sécurité — dispo, compétences, vacations",
    seoDesc:
      "Logiciel gestion agents de sécurité : disponibilités, compétences site, vacations, backups. Essai 15 j sans CB.",
    crumbLabel: "Agents de sécurité",
    h1Lead: "Gestion des agents de sécurité",
    h1: "le bon agent sur le bon poste — pas le premier numéro WhatsApp",
    sub: "Disponibilité, vacation déjà prise, site déjà briefé, contrainte nuit/week-end : affectez avec méthode, remplacez sans improvisation.",
    claimBefore: "De l’effectif à la",
    claimHighlight: "vacation tenue",
    claimSub: "agents · compétences · dispo",
    productStrip: "Effectif · dispo · compétences site · affectation",
    empathyH2: "Affecter n’est pas « envoyer un prénom sur WhatsApp »",
    empathyBody: "Compétences, disponibilités, brief : un agent mal affecté sur un poste SSIAP ou un site sensible, c’est un risque opérationnel avant d’être un souci RH.",
    showcaseTitle: "Pool agents : dispo, site, vacation en cours",
    showcaseSub: "Ce que le chef d’exploitation lit avant d’appeler.",
    showcaseBadgeLeft: { title: "Pool nuit", sub: "8 agents · 3 dispo" },
    showcaseBadgeRight: "1 prioritaire",
    proofH2: "Effectif lié au planning — pas un SIRH fantôme",
    proofQuote: "Compétence site > proximité WhatsApp.",
    proofItems: [
      { title: "Disponibilités", text: "Nuit, week-end, astreinte — visibles." },
      { title: "Historique site", text: "Déjà passé / jamais venu / briefing requis." },
      { title: "Conflits", text: "Vacation déjà prise sur un autre poste." },
    ],
    vsTitle: "Annuaire téléphone vs pool agents PROGESTI",
    demo: {
      eyebrow: "Démo · pool agents nuit",
      h2: "21h10 : qui peut tenir Entrepôt Nord à 22h ?",
      lead: "Trois candidats, un seul déjà briefé et libre — le choix devient évident.",
      scenario:
        "Désistement dernière minute sur Entrepôt Nord 22h–06h. Le chef d’exploitation ouvre le pool nuit : pas le carnet d’adresses, le filtre dispo + compétence site.",
      steps: [
        { label: "Filtre", detail: "Nuit · rayon 40 min · pas déjà en vacation." },
        { label: "Priorité", detail: "A. Benali : 14 passages site · dispo." },
        { label: "Écartés", detail: "L. Moreau déjà sur Usine Est · K. Rossi 1re fois sans brief." },
        { label: "Affectation", detail: "Benali + consignes poussées · confirmation 21h18." },
      ],
      uiLabel: "Pool backup · nuit 22h–06h",
      uiToolbar: "Filtre : Nuit · Dispo · Site Entrepôt Nord",
      variant: "board",
      uiRows: [
        {
          left: "A. Benali",
          right: "Dispo · 14× sur Entrepôt Nord",
          status: "Prioritaire",
          tone: "ok",
          meta: "ETA 25 min · brief OK",
        },
        {
          left: "L. Moreau",
          right: "Vacation Usine Est 22h–06h",
          status: "Indispo",
          tone: "danger",
          meta: "Double booking évité",
        },
        {
          left: "K. Rossi",
          right: "Dispo · 1re fois sur ce site",
          status: "Briefing requis",
          tone: "warn",
          meta: "Consignes non lues",
        },
        {
          left: "S. Diallo",
          right: "Astreinte mais hors rayon",
          status: "Éloigné",
          tone: "info",
          meta: "ETA 70 min · plan B",
        },
      ],
      uiHint: "Gestion d’effectif liée au planning — pas un SIRH complet ni outil CNAPS.",
      takeaway: "Le bon backup, c’est celui qui connaît le poste — pas celui qui répond en premier.",
      primaryCtaLabel: "Essayer avec votre effectif",
      secondaryCtaLabel: "Démo pool agents",
    },
    bodySections: [
      {
        h2: "Ce que cette page n’est pas",
        body: "Pas un logiciel de paie complet, pas un registre CNAPS, pas une marketplace d’intérim. C’est l’effectif opérationnel branché sur vos vacations.",
      },
      {
        h2: "Compétences utiles en affectation",
        body: "Site déjà briefé, vacation nuit OK, SSIAP si le poste l’exige (orga — pas formation), permis si site isolé, langue si accueil.",
        bullets: [
          "Historique de passages par site",
          "Indisponibilités déclarées",
          "Lien remplacement urgence",
        ],
      },
      {
        h2: "Objection « on se connaît tous »",
        body: "Vrai à 8 agents. Faux à 40 avec multi-sites et absences. Le pool évite les oublis et les doubles vacations.",
      },
    ],
    faq: [
      {
        q: "Comment éviter d’affecter un agent sans la compétence du poste ?",
        a: "Le poste porte ses exigences ; l’affectation visible si le profil ne matche pas. Vous corrigez avant la prise de vacation.",
      },
      {
        q: "Différence avec le planning agents ?",
        a: "Ici l’angle est le vivier agents / compétences. Le planning traite la grille horaires et les trous.",
      },
      {
        q: "Les backups sont-ils nominatifs ?",
        a: "Oui, idéalement : un pool nommé bat un « on verra ce soir » pour les postes critiques.",
      },
      {
        q: "Ça remplace mon SIRH ?",
        a: "Non. PROGESTI sert l’affectation opérationnelle. Congés / paie restent dans votre SIRH.",
      },
      {
        q: "Comment gérer un cas SSIAP avec « logiciel gardiennage » ?",
        a: "Voir aussi la page SSIAP : l’orga de poste et la compétence doivent coller — sans promesse réglementaire abusive.",
      },
    ],
    gridItems: [
      link("Planning agents", "Affectation semaine.", "/securite/planning-agents"),
      link("Remplacement urgence", "Process backup.", "/securite/remplacement-urgence"),
      link("Astreinte nuit", "Pool nuit dédié.", "/securite/astreinte-nuit"),
      link("SSIAP", "Orga postes incendie.", "/securite/ssiap"),
    ],
    ctaPrimaryLabel: "Essai effectif agents",
    ctaSecondaryLabel: "Voir la démo pool",
    trustLeft: "Verticale sécurité · agents & vacations",
  },
  {
    id: "SEC-06",
    key: "surete-sites",
    path: "/securite/surete-sites",
    type: "service",
    primaryKw: "logiciel sûreté des sites",
    seoTitle: "Sûreté des sites — consignes, vacations, preuves",
    seoDesc:
      "Sûreté des sites : fiches consignes, vacations, rondes, reporting. Organisation opérationnelle pour prestataires. Essai 15 j sans CB.",
    crumbLabel: "Sûreté des sites",
    h1Lead: "Sûreté des sites",
    h1: "consignes tenues, vacations prouvées, reporting clair",
    sub: "Pour le prestataire qui vend de la sûreté opérationnelle : fiche site, vacation, ronde, main courante — pas un discours « zero risk » marketing.",
    claimBefore: "De la fiche site à la",
    claimHighlight: "preuve",
    claimSub: "sûreté sites · consignes & vacations",
    productStrip: "Fiche site · consignes · vacation · preuves",
    empathyH2: "Des consignes dans un classeur = des consignes invisibles à 21h50",
    empathyBody: "Contrôles d’accès, listes, particularités site : si le backup ne les lit pas avant d’entrer, vous n’avez pas de sûreté site — vous avez de l’espoir.",
    showcaseTitle: "Fiche site = colonne vertébrale de la vacation",
    showcaseSub: "Accès, zones, escalade, rondes — sur mobile à la prise de poste.",
    showcaseBadgeLeft: { title: "Fiche site", sub: "v18 · à jour" },
    showcaseBadgeRight: "Lue 21h51",
    proofH2: "Sûreté opérationnelle = exécution + preuve",
    proofQuote: "Consignes non lues = vacation à risque, même avec un bon agent.",
    proofItems: [
      { title: "Consignes versionnées", text: "L’agent voit la dernière version, pas un PDF de 2019." },
      { title: "Vacations liées", text: "Chaque présence rattache site + consignes + preuves." },
      { title: "Anomalies", text: "Main courante pour ce qui sort du nominal." },
    ],
    vsTitle: "Classeur consignes vs fiche site mobile PROGESTI",
    demo: {
      eyebrow: "Démo · sûreté site",
      h2: "Prise de poste 21h50 : consignes avant d’ouvrir le portail",
      lead: "L’agent ne « commence pas » tant que la fiche n’est pas lue — l’exploitation le voit.",
      scenario:
        "Site sensible léger « DataEdge » (accès restreint, zones interdites, escalade stricte). Vacation 22h–06h, agent R. Nguyen première fois en titulaire après 2 shadowings.",
      steps: [
        { label: "Ouverture fiche", detail: "21h50 — consignes v18 + plan zones." },
        { label: "Lecture obligatoire", detail: "Accès, interdits, chaîne d’alerte, ronde N1." },
        { label: "Confirmation", detail: "Statut « consignes lues » horodaté 21h57." },
        { label: "Vacation", detail: "Pointage 22h01 · première ronde 22h40." },
      ],
      uiLabel: "Fiche site · DataEdge",
      uiToolbar: "Vacation 22h–06h · Agent R. Nguyen · Consignes v18",
      variant: "checklist",
      uiRows: [
        {
          left: "Accès & digicode",
          right: "Codes rotation mensuelle · badge visiteur",
          status: "Lu",
          tone: "ok",
          meta: "21:52",
        },
        {
          left: "Zones interdites",
          right: "Salle baies · local groupes électrogènes",
          status: "Lu",
          tone: "ok",
          meta: "21:54",
        },
        {
          left: "Chaîne escalade",
          right: "Chef de poste → RSSI client → astreinte",
          status: "Lu",
          tone: "ok",
          meta: "21:56",
        },
        {
          left: "Ronde N1",
          right: "4 points · délai 45 min",
          status: "Planifiée",
          tone: "info",
          meta: "Départ 22:40",
        },
      ],
      uiHint: "Organisation consignes — pas un contrôle d’accès physique / badgeuse hardware.",
      takeaway: "Sûreté site = consignes exécutées + vacation prouvée, pas un slogan.",
      primaryCtaLabel: "Essayer sur vos fiches sites",
      secondaryCtaLabel: "Démo consignes",
    },
    bodySections: [
      {
        h2: "Positionnement SEO : sûreté ≠ télésurveillance",
        body: "Cette page parle d’organisation prestataire (vacations, consignes, preuves). La télésurveillance alarmes / vidéo n’est pas le produit. Le PC sécurité a sa page pour la supervision multi-sites.",
      },
      {
        h2: "Lien avec sites sensibles et consignes accès",
        body: "Angle « sûreté des sites » = cadre. Sites sensibles resserre l’exigence. Contrôle-accès-consignes détaille la fiche. Évitez de tout dire ici.",
      },
      {
        h2: "Objections facility / RSSI",
        body: "Ils veulent de la traçabilité. Montrez exports, versions de consignes, historiques de vacation — pas un discours feature SaaS.",
      },
    ],
    faq: [
      {
        q: "Où vivent les consignes pour qu’un backup les voie vraiment ?",
        a: "Sur le poste / le site, accessibles mobile au moment de l’affectation — pas dans un PDF mailé en janvier.",
      },
      {
        q: "Lien avec contrôle d’accès ?",
        a: "La page contrôle d’accès & consignes détaille le brief. Ici l’angle est la présence prouvée dans un cadre de sûreté site.",
      },
      {
        q: "Que journaliser en cas d’anomalie d’accès ?",
        a: "L’incident dans la main courante, rattaché au site et à la vacation — pour le rapport client et votre exploitation.",
      },
      {
        q: "Sites multi-consignes (jour/nuit) ?",
        a: "Séparez les briefs par créneau. L’agent de nuit ne doit pas appliquer le protocole jour par erreur.",
      },
      {
        q: "Par où commencer pour « logiciel gardiennage » ?",
        a: "Un site pilote, consignes à jour, 2 backups briefés, une semaine de preuves de présence.",
      },
    ],
    gridItems: [
      link("Consignes accès", "Fiche site détaillée.", "/securite/controle-acces-consignes"),
      link("Sites sensibles", "Exigence renforcée.", "/securite/sites-sensibles"),
      link("Main courante", "Anomalies notées.", "/securite/main-courante"),
      link("PC sécurité", "Supervision multi-sites.", "/securite/pc-securite"),
    ],
    ctaPrimaryLabel: "Essai sûreté sites",
    ctaSecondaryLabel: "Voir la démo fiche",
    trustLeft: "Verticale sécurité · sûreté opérationnelle",
  },
  {
    id: "SEC-07",
    key: "sites-industriels",
    path: "/securite/sites-industriels",
    type: "audience",
    primaryKw: "gardiennage site industriel logiciel",
    seoTitle: "Gardiennage site industriel — vacations & traçabilité",
    seoDesc:
      "Gardiennage site industriel : vacations entrée/quais, rondes, preuves audit donneur d’ordre. Essai 15 j sans CB.",
    crumbLabel: "Sites industriels",
    h1Lead: "Gardiennage site industriel",
    h1: "vacations strictes, rondes prouvées, audit prêt",
    sub: "Accès PL, horaires atypiques, exigences de preuve : le flou ne survit pas à un audit usine / entrepôt. Structurez vacation, ronde et reporting.",
    claimBefore: "De l’usine à la",
    claimHighlight: "preuve audit",
    claimSub: "industriel · traçabilité",
    productStrip: "Entrée PL · quais · rondes · export audit",
    empathyH2: "La nuit sur entrepôt ne pardonne pas un trou de vacation",
    empathyBody: "Accès quai, consignes frigo, vacation 22h–06h : le facility manager juge sur la couverture et les preuves, pas sur votre charge mentale du vendredi soir.",
    showcaseTitle: "Usine / entrepôt : vacation + ronde + export",
    showcaseSub: "Ce que le responsable site client peut recevoir sans reconstruction.",
    showcaseBadgeLeft: { title: "Poste PL", sub: "18h–06h" },
    showcaseBadgeRight: "Audit OK",
    proofH2: "Traçabilité opérationnelle — claims réalistes",
    proofQuote: "L’audit aime les horodatages, pas les souvenirs.",
    proofItems: [
      { title: "Vacation tenue", text: "Pointage entrée/sortie poste." },
      { title: "Rondes", text: "Points quais / locaux tech historisés." },
      { title: "Export", text: "Période + site pour le donneur d’ordre." },
    ],
    vsTitle: "Reporting bricolé vs historique industriel PROGESTI",
    demo: {
      eyebrow: "Démo · site industriel",
      h2: "Audit surprise semaine 12 : vous sortez l’historique en 4 minutes",
      lead: "Présences poste PL + rondes quais + incidents main courante — même période, même site.",
      scenario:
        "Entrepôt Nord, contrat cadre. Le responsable sûreté client demande le détail des nuits du 10 au 16 mars : qui tenait l’entrée PL, quelles rondes, quels incidents.",
      steps: [
        { label: "Filtre", detail: "Site Entrepôt Nord · 10–16/03." },
        { label: "Vacations", detail: "7 nuits · pointages complets · 1 remplacement tracé." },
        { label: "Rondes", detail: "Passages quais / TGBT exportés." },
        { label: "Incidents", detail: "2 entrées main courante liées — déjà connues du client." },
      ],
      uiLabel: "Audit · Entrepôt Nord · S12",
      uiToolbar: "Export donneur d’ordre · 10–16/03 · Format synthèse",
      variant: "split",
      uiSplitLabels: ["Vacations", "Preuves"],
      uiRows: [
        {
          left: "Poste entrée PL",
          right: "18h–06h · 7/7 tenues",
          status: "OK",
          tone: "ok",
          meta: "1 remplacement 12/03",
        },
        {
          left: "Pointages",
          right: "Écarts < 10 min",
          status: "OK",
          tone: "ok",
          meta: "Tolérance contrat",
        },
        {
          left: "Rondes quais",
          right: "2 tours/nuit · points validés",
          status: "Historisé",
          tone: "ok",
          meta: "1 rattrapage 14/03",
        },
        {
          left: "Main courante",
          right: "Quai B ouvert 02h14 · escalade faite",
          status: "Noté",
          tone: "info",
          meta: "Déjà signalé client",
        },
      ],
      uiHint: "Traçabilité ops — sans claim « conformité certifiée » abusive.",
      takeaway: "L’audit industriel se gagne avant : chaque nuit doit déjà être propre.",
      primaryCtaLabel: "Essai site industriel",
      secondaryCtaLabel: "Démo audit",
    },
    bodySections: [
      {
        h2: "Spécificités industriel vs retail / copro",
        body: "Horaires longs, accès PL, locaux techniques, exigences d’export. Retail = multi-postes fréquentation. Copro = reporting syndic. Ne pas copier-coller le même discours.",
      },
      {
        h2: "Journée type chef d’équipe sur usine",
        body: "Relève, consignes particulières livraison de nuit, contrôle rondes, transmission incidents au responsable site client.",
      },
      {
        h2: "Objection « on a déjà des badges usine »",
        body: "Le badge client ne remplace pas votre planning de vacation ni votre preuve de ronde prestataire. Les deux coexistent souvent.",
      },
    ],
    faq: [
      {
        q: "Comment gérer une vacation nuit industrielle avec backup de dernière minute ?",
        a: "Trou visible → backup affecté → consignes poussées → pointage. Le scénario Entrepôt Nord du pilier est exactement ce flux.",
      },
      {
        q: "Rondes sur site industriel : même page ?",
        a: "Non : utilisez rondes & surveillance pour les parcours. Ici l’angle est la vacation / présence site industriel.",
      },
      {
        q: "Accès badge / consignes quai ?",
        a: "Dans le brief site, visibles mobile. Le backup ne découvre pas le digicode à 21h55 au téléphone.",
      },
      {
        q: "Reporting facility le lundi ?",
        a: "Historique de présence + incidents main courante + rondes si configurées — un dossier, pas trois Excel.",
      },
      {
        q: "Quel pilote conseillez-vous pour « logiciel gardiennage » ?",
        a: "1 site industriel nuit + 1 semaine de backups testés. Puis vous étendez aux autres entrepôts.",
      },
    ],
    gridItems: [
      link("Rondes", "Passages prouvés.", "/securite/rondes-surveillance"),
      link("Reporting client", "Synthèse donneur d’ordre.", "/securite/reporting-client"),
      link("Contrats cadres", "Cadre vs réalisé.", "/securite/contrats-cadres"),
      link("Main courante", "Incidents site.", "/securite/main-courante"),
    ],
    ctaPrimaryLabel: "Essai entrepôt / usine",
    ctaSecondaryLabel: "Démo traçabilité",
    trustLeft: "Verticale sécurité · sites industriels",
  },
  {
    id: "SEC-08",
    key: "centres-commerciaux",
    path: "/securite/centres-commerciaux",
    type: "audience",
    primaryKw: "sécurité centre commercial logiciel",
    seoTitle: "Sécurité centre commercial — multi-postes & vacations",
    seoDesc:
      "Sécurité centre commercial : multi-postes, pics fréquentation, remplacements rapides, preuves. Essai 15 j sans CB.",
    crumbLabel: "Centres commerciaux",
    h1Lead: "Sécurité centre commercial / retail",
    h1: "multi-postes sous pression fréquentation",
    sub: "Entrée, parking, galerie, livraisons : plusieurs vacations en parallèle, renforts samedi, remplacements sans perdre le fil des consignes.",
    claimBefore: "Du pic samedi à la",
    claimHighlight: "couverture tenue",
    claimSub: "retail · multi-postes",
    productStrip: "Entrée · parking · galerie · renforts",
    empathyH2: "Ouverture centre : horaires serrés, zéro place pour l’à-peu-près",
    empathyBody: "Flux clients, multi-postes, créneaux d’ouverture : si un poste lâché n’est pas repris avant l’ouverture, c’est visible dans le mall — et dans le compte-rendu du centre.",
    showcaseTitle: "Samedi : carte des postes du centre",
    showcaseSub: "Qui est où, qui renforce, qui backup.",
    showcaseBadgeLeft: { title: "Samedi 14h–18h", sub: "Pic · 6 postes" },
    showcaseBadgeRight: "Renfort OK",
    proofH2: "Retail = orchestration multi-postes",
    proofQuote: "Un trou à l’entrée se voit en 30 secondes — littéralement.",
    proofItems: [
      { title: "Vue multi-postes", text: "Entrée, parking, galerie, stock." },
      { title: "Renforts", text: "Vacations courtes sur créneaux de pic." },
      { title: "Remplacements", text: "Backup briefé sans casser les autres postes." },
    ],
    vsTitle: "Groupes WhatsApp vs planning multi-postes retail",
    demo: {
      eyebrow: "Démo · centre commercial samedi",
      h2: "13h05 : agent entrée se désiste — pic à 14h",
      lead: "Réaffecter sans dégarnir le parking ni la galerie.",
      scenario:
        "Centre « Les Arcades ». Postes : entrée principale (2), parking -1, galerie, livraisons. Samedi pic 14h–18h. Désistement entrée à 13h05.",
      steps: [
        { label: "Alerte", detail: "Poste entrée −1 agent · statut attention." },
        { label: "Pool", detail: "Renfort prévu 15h avancé · agent galerie bascule 30 min." },
        { label: "Consignes", detail: "Brief entrée (files, consignes éviction) poussé mobile." },
        { label: "Stabilisation", detail: "14h02 : entrée à 2 · parking tenu · historique remplacement." },
      ],
      uiLabel: "Les Arcades · Samedi pic",
      uiToolbar: "Live postes · 13:05 → 14:10 · Exploitation retail",
      uiAlert: "13h05 — Entrée principale à 1/2 agents · pic 14h",
      variant: "board",
      uiRows: [
        {
          left: "Entrée principale",
          right: "2 agents · pic 14h–18h",
          status: "Renforcé",
          tone: "ok",
          meta: "Backup intégré 13:40",
        },
        {
          left: "Parking −1",
          right: "1 agent · rondes horaires",
          status: "OK",
          tone: "ok",
          meta: "Non dégarni",
        },
        {
          left: "Galerie",
          right: "1 agent · bascule temporaire 13:20–13:50",
          status: "Ajusté",
          tone: "warn",
          meta: "Retour galerie 13:50",
        },
        {
          left: "Livraisons arrière",
          right: "Vacation 7h–11h déjà clôturée",
          status: "Clos",
          tone: "info",
          meta: "Hors pic après-midi",
        },
      ],
      takeaway: "En retail, la couverture multi-postes se joue en minutes — avec une vue unique.",
      primaryCtaLabel: "Essai multi-postes retail",
      secondaryCtaLabel: "Démo centre commercial",
    },
    bodySections: [
      {
        h2: "Retail ≠ industriel ≠ event",
        body: "Fréquentation variable, multi-postes simultanés, image client. Industriel = traçabilité longue. Event = one-shot. Gardez l’angle fréquentation ici.",
      },
      {
        h2: "Process renfort week-end",
        body: "Vacations courtes sur pics, pool renfort dédié, consignes entrée spécifiques (files, malveillance courante).",
      },
      {
        h2: "Reporting bailleur / centre",
        body: "Présences postes + incidents main courante — lien page reporting client.",
      },
    ],
    faq: [
      {
        q: "Comment tenir plusieurs postes sur un même centre le samedi ?",
        a: "Planning multi-postes avec backups par zone (parking, mall, livraison). Les trous apparaissent avant l’ouverture, pas à 10h15.",
      },
      {
        q: "Différence avec multi-sites ?",
        a: "Ici un site complexe multi-postes. Multi-sites = portefeuille d’adresses. Les deux se combinent souvent.",
      },
      {
        q: "Horaires d’ouverture variables ?",
        a: "Les vacations suivent le calendrier du centre (nocturnes, inventaires). Le planning doit pouvoir absorber ces exceptions.",
      },
      {
        q: "Preuves pour le gestionnaire du centre ?",
        a: "Présences + incidents + éventuellement rondes parkings — exportables pour le comité de suivi.",
      },
      {
        q: "Par où commencer pour « logiciel gardiennage » ?",
        a: "Un centre, un week-end type, tous les postes du samedi modélisés avec backup.",
      },
    ],
    gridItems: [
      link("Remplacement urgence", "Désistement pic.", "/securite/remplacement-urgence"),
      link("Planning agents", "Semaine + week-end.", "/securite/planning-agents"),
      link("Evenementiel", "One-shot distinct.", "/securite/evenementiel"),
      link("Reporting client", "Synthèse bailleur.", "/securite/reporting-client"),
    ],
    ctaPrimaryLabel: "Essai retail / centre",
    ctaSecondaryLabel: "Démo multi-postes",
    trustLeft: "Verticale sécurité · retail & centres",
  },
  {
    id: "SEC-09",
    key: "evenementiel",
    path: "/securite/evenementiel",
    type: "audience",
    primaryKw: "logiciel sécurité événementielle",
    seoTitle: "Sécurité événementielle — staffing vacations one-shot",
    seoDesc:
      "Sécurité événementielle : postes concert/salon, briefings, vacations one-shot, facture rapide. Essai 15 j sans CB.",
    crumbLabel: "Événementiel",
    h1Lead: "Sécurité événementielle",
    h1: "staffing one-shot, briefings, facture après le rideau",
    sub: "Pas un contrat mensuel flou : devis → postes → affectations → présences → facture de l’événement. Rapide, traçable, distinct du gardiennage site récurrent.",
    claimBefore: "De l’event à la",
    claimHighlight: "facture",
    claimSub: "événementiel · vacations one-shot",
    productStrip: "Postes event · brief · présence · facture",
    empathyH2: "Un festival ne se planifie pas comme un poste fixe annuel",
    empathyBody: "Renforts, créneaux courts, brief express : si l’agent arrive sans savoir où est le poste 4, vous le saurez au premier incident de file d’attente.",
    showcaseTitle: "Event #4821 : postes confirmés, heures agrégées",
    showcaseSub: "Du staffing à la facture post-événement.",
    showcaseBadgeLeft: { title: "Concert 18h–01h", sub: "6 postes" },
    showcaseBadgeRight: "Facture brouillon",
    proofH2: "One-shot ≠ contrat site",
    proofQuote: "Après le rideau, seules les heures prouvées se facturent sans dispute.",
    proofItems: [
      { title: "Postes event", text: "Créneaux et effectifs par zone." },
      { title: "Brief J-1", text: "Consignes spécifiques event sur mobile." },
      { title: "Facture rapide", text: "Heures réalisées agrégées post-event." },
    ],
    vsTitle: "Fil WhatsApp event vs staffing structuré PROGESTI",
    demo: {
      eyebrow: "Démo · staffing concert",
      h2: "J-1 16h : figer les postes avant les premières arrivées agents",
      lead: "6 postes, 12 agents, brief fosses/parking, pointages, facture #4821.",
      scenario:
        "Concert salle 5000 places. Zones : contrôle accès fosse (4), périmètre parking (2), backstage (2), bagagerie (2), renfort sortie (2). Client organisateur veut le décompte dimanche matin.",
      steps: [
        { label: "Staffing", detail: "Affectations confirmées · vacataires inclus." },
        { label: "Brief", detail: "Consignes fosses + plan zones poussés J-1 16h." },
        { label: "Live", detail: "Pointages prise de poste · 1 remplacement parking 19h20." },
        { label: "Facture", detail: "Dimanche 10h : heures agrégées → brouillon event #4821." },
      ],
      uiLabel: "Event #4821 · Concert",
      uiToolbar: "J-1 → J+1 · Staffing one-shot · 12 agents",
      variant: "timeline",
      uiRows: [
        {
          left: "Contrôle accès fosse",
          right: "18h–00h · 4 agents confirmés",
          status: "Confirmé",
          tone: "ok",
          meta: "Brief fosses lu 16:40",
        },
        {
          left: "Périmètre parking",
          right: "17h–01h · 2 agents",
          status: "Remplacé 19h20",
          tone: "warn",
          meta: "Backup intégré 19:28",
        },
        {
          left: "Pointages agrégés",
          right: "47,5 h réalisées",
          status: "OK",
          tone: "ok",
          meta: "Tolérance check-in event",
        },
        {
          left: "Facture event #4821",
          right: "Brouillon → envoi organisateur",
          status: "Prête",
          tone: "ok",
          meta: "Dimanche 10:12",
        },
      ],
      takeaway: "L’événementiel se facture proprement si le staffing a été propre dès J-1.",
      primaryCtaLabel: "Essai staffing event",
      secondaryCtaLabel: "Démo one-shot",
    },
    bodySections: [
      {
        h2: "Anti-cannibalisation : event vs site récurrent",
        body: "Ne parlez pas de contrat cadre mensuel ici. L’angle est one-shot : devis, postes, brief, présence, facture rapide. Le gardiennage site a sa page.",
      },
      {
        h2: "Risques spécifiques event",
        body: "Vacataires peu briefés, créneaux courts, zones sensibles (fosse), sortie de salle. La fiche consignes event et le pointage évitent le flou post-fait.",
      },
      {
        h2: "Objection « c’est trop lourd pour un week-end »",
        body: "Justement : un process léger one-shot évite 3 jours de dépouillement WhatsApp après coup.",
      },
    ],
    faq: [
      {
        q: "Comment briefer vite 20 renforts la veille d’un event ?",
        a: "Postes nommés, créneaux, consignes courtes sur mobile. Le brief n’est plus un PowerPoint oublié dans un groupe WA.",
      },
      {
        q: "Les vacations event se facturent comment ?",
        a: "Comme du réalisé pointé — utile quand les créneaux glissent. Voir aussi facturation gardiennage.",
      },
      {
        q: "Différence avec BTP chantier ?",
        a: "Event = pic court + renforts. BTP = créneaux chantier / accès engins. Pages distinctes.",
      },
      {
        q: "Que journaliser pendant l’event ?",
        a: "Main courante des incidents (files, évacuation partielle, objets trouvés) rattachée au dispositif du jour.",
      },
      {
        q: "Par quel pilote démarrer pour « logiciel gardiennage » ?",
        a: "Un event moyen (pas le plus gros de l’année) pour valider brief + pointage + reporting.",
      },
    ],
    gridItems: [
      link("Facturation gardiennage", "Heures → facture.", "/securite/facturation-gardiennage"),
      link("Agents", "Pool & vacataires.", "/securite/agents-securite"),
      link("Remplacement urgence", "Trou en live event.", "/securite/remplacement-urgence"),
      link("Planning agents", "Affectation J-1.", "/securite/planning-agents"),
    ],
    ctaPrimaryLabel: "Essai event",
    ctaSecondaryLabel: "Démo staffing",
    trustLeft: "Verticale sécurité · événementiel",
  },
];
